import type { NotableBirthEntry } from "../../../types";

export const FR_NOTABLE_BIRTH_BACKFILL_2010_current: NotableBirthEntry[] = [
  {
    year: 2010,
    lang: "fr",
    name: "Lucie Schoonheere",
    birthDate: "2010-01-29",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Lucie_Schoonheere",
    theme: "loisirs",
    gestureRoot: "personnalite",
    editorialScore: 64,
    achievement: "Elle remportera The Voice Belgique et se produira en tournée avec une voix soul remarquée.",
  },
  {
    year: 2011,
    lang: "fr",
    name: "Josephine de Danemark",
    birthDate: "2011-01-01",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Josephine_de_Danemark",
    theme: "loisirs",
    gestureRoot: "personnalite",
    editorialScore: 60,
    achievement: "Quatrième fille du prince héritier Frederik, elle grandira dans la famille royale danoise moderne.",
  },
  {
    year: 2012,
    lang: "fr",
    name: "Athena de Danemark",
    birthDate: "2012-01-24",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Athena_de_Danemark",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Elle est la plus jeune fille du prince héritier Frederik et de la princesse Mary de Danemark.",
  },
  {
    year: 2013,
    lang: "fr",
    name: "Sofía Otero",
    birthDate: "2013-03-31",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Sof%C3%ADa_Otero",
    theme: "loisirs",
    gestureRoot: "acteur",
    editorialScore: 64,
    achievement: "Elle sera révélée par le cinéma espagnol et saluée pour des rôles d'enfant dans des drames primés.",
  },
  {
    year: 2014,
    lang: "fr",
    name: "Leonore de Suède",
    birthDate: "2014-02-20",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Leonore_de_Su%C3%A8de",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Elle est la fille du prince Carl Philip et de la princesse Sofia — cinquième dans l'ordre de succession au trône suédois.",
  },
  {
    year: 2015,
    lang: "fr",
    name: "Charlotte de Cambridge",
    birthDate: "2015-05-02",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Charlotte_de_Cambridge",
    theme: "loisirs",
    gestureRoot: "personnalite",
    editorialScore: 64,
    achievement: "Elle est la fille du prince William et de Catherine, princesse de Galles, et troisième dans l'ordre de succession britannique.",
  },
  {
    year: 2016,
    lang: "fr",
    name: "Jigme Namgyel Wangchuck",
    birthDate: "2016-02-05",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Jigme_Namgyel_Wangchuck",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Il est le prince héritier du Bhoutan, fils du roi Jigme Khesar Namgyel Wangchuck.",
  },
  {
    year: 2017,
    lang: "fr",
    name: "Gabriel de Suède",
    birthDate: "2017-08-31",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Gabriel_de_Su%C3%A8de",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Il est le fils du prince Carl Philip et de la princesse Sofia, dans la famille royale suédoise.",
  },
  {
    year: 2018,
    lang: "fr",
    name: "Ameya Anilkumar",
    birthDate: "2018-01-05",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Ameya_Anilkumar",
    theme: "loisirs",
    gestureRoot: "acteur",
    editorialScore: 64,
    achievement: "Elle sera révélée par le cinéma indien avec des rôles d'enfant et de jeune comédienne.",
  },
  {
    year: 2019,
    lang: "fr",
    name: "Archie Mountbatten-Windsor",
    birthDate: "2019-05-06",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Archie_Mountbatten-Windsor",
    theme: "loisirs",
    gestureRoot: "personnalite",
    editorialScore: 64,
    achievement: "Il est le fils du prince Harry et de Meghan Markle, premier petit-enfant métisse très médiatisé de la famille royale britannique.",
  },
  {
    year: 2020,
    lang: "fr",
    name: "Charles de Luxembourg",
    birthDate: "2020-05-10",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Charles_de_Luxembourg_(2020)",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Il est le fils du grand-duc héritier Guillaume et de la grande-duchesse héritière Stéphanie.",
  },
  {
    year: 2021,
    lang: "fr",
    name: "Julian de Suède",
    birthDate: "2021-03-26",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Julian_de_Su%C3%A8de",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Il est le fils de la princesse Sofia et du prince Carl Philip, dans la famille royale suédoise.",
  },
  {
    year: 2022,
    lang: "fr",
    name: "Vinice Mabansag",
    birthDate: "2022-11-15",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Vinice_Mabansag",
    theme: "loisirs",
    gestureRoot: "personnalite",
    editorialScore: 64,
    achievement: "Symboliquement désignée comme la 100e millionième habitante des Philippines à sa naissance.",
  },
  {
    year: 2023,
    lang: "fr",
    name: "François de Luxembourg",
    birthDate: "2023-03-27",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Fran%C3%A7ois_de_Luxembourg_(2023)",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Il est le fils du grand-duc héritier Guillaume et de la grande-duchesse héritière Stéphanie.",
  },
  {
    year: 2024,
    lang: "fr",
    name: "Princess Iman bint Hussein bin Abdullah",
    birthDate: "2024-08-03",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Princess_Iman_bint_Hussein_bin_Abdullah",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 60,
    achievement: "Elle est la fille du prince héritier Hussein et de Rajwa Al Saif, dans la famille royale hachémite de Jordanie.",
  },
  {
    year: 2025,
    lang: "fr",
    name: "Ines de Suède",
    birthDate: "2025-02-07",
    wikipediaUrl: "https://fr.wikipedia.org/wiki/Ines_de_Su%C3%A8de",
    theme: "famille",
    gestureRoot: "famille_royale",
    editorialScore: 64,
    achievement: "Elle est la fille du prince Carl Philip et de la princesse Sofia, dans la famille royale suédoise.",
  },
];
