import type { CulturalMomentEntry } from "../../../types";

export const FR_CULTURAL_BACKFILL_1826_1924: CulturalMomentEntry[] = [
  {
    id: "fr-1830-revolution-juillet",
    countryQid: "Q142", lang: "fr",
    momentKey: "les-trois-glorieuses-revolution-de-juillet-1830",
    momentLabel: "Les Trois Glorieuses — révolution de Juillet 1830",
    label: "les Trois Glorieuses de 1830",
    category: "foundational_event", theme: "administration", gestureRoot: "revolution_juillet",
    editorialScore: 95,
    date: "1830-07-27", year: 1830, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Insurrection parisienne chassant Charles X et portant Louis-Philippe au trône",
    beforeState: "Avant juillet 1830, Charles X cherche à restaurer l'absolutisme en révoquant la presse et en dissolvant la Chambre.",
    afterState: "Après les Trois Glorieuses, la monarchie constitutionnelle de juillet est instaurée, la liberté de la presse rétablie.",
    gestureChanged: "Tu peux lire à nouveau des journaux d'opposition et voir une monarchie contrôlée par une charte constitutionnelle.",
    materialAnchor: "Barricades de pavés, drapeau tricolore, pistolet de citoyen",
    sceneText: "27 juillet 1830, Paris. Les barricades poussent dans les rues en quelques heures. Des ouvriers, des étudiants, des bourgeois libéraux côte à côte. En trois jours, Charles X a fui. Le tricolore flotte à nouveau sur Notre-Dame. La France change de roi mais pas de régime — elle change les règles du roi.",
    fact: "Les 27, 28 et 29 juillet 1830 (les Trois Glorieuses), l'insurrection parisienne renverse Charles X et instaure la monarchie de Juillet sous Louis-Philippe Ier.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/R%C3%A9volution_de_Juillet", authority: false },
      { label: "BnF Gallica", url: "https://gallica.bnf.fr/", authority: true }
    ],
    tags: ["revolution", "1830", "paris", "barricades"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1833-notre-dame-de-paris-hugo",
    countryQid: "Q142", lang: "fr",
    momentKey: "lire-notre-dame-de-paris-victor-hugo",
    momentLabel: "Notre-Dame de Paris de Victor Hugo — roman historique fondateur",
    label: "Notre-Dame de Paris de Victor Hugo",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "hugo_notre_dame",
    editorialScore: 92,
    date: "1831-03-16", year: 1831, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Publication de Notre-Dame de Paris par Victor Hugo",
    beforeState: "Avant 1831, Notre-Dame de Paris est un monument délabré que beaucoup voudraient démolir.",
    afterState: "Après 1831, le roman de Hugo provoque un mouvement national pour sauvegarder le patrimoine médiéval français.",
    gestureChanged: "Tu peux lire un roman qui te fait ressentir le Paris du Moyen Âge comme un lieu vivant, et comprendre pourquoi des pierres valent d'être sauvées.",
    materialAnchor: "Volume relié de Notre-Dame de Paris, gravure de Quasimodo, façade gothique",
    sceneText: "1831, Paris. Le roman circule de main en main. Quasimodo, Esmeralda, Frollo — trois silhouettes qui font voir autrement la cathédrale debout depuis des siècles. Le livre déclenche un mouvement : on ne laissera pas démolir ce que Hugo vient de ressusciter.",
    fact: "Publié en 1831, Notre-Dame de Paris de Victor Hugo suscite un mouvement de défense du patrimoine gothique et contribue directement à la décision de restaurer la cathédrale, confiée à Viollet-le-Duc en 1844.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Notre-Dame_de_Paris_(roman)", authority: false },
      { label: "BnF", url: "https://gallica.bnf.fr/ark:/12148/bpt6k56526090", authority: true }
    ],
    tags: ["hugo", "notre-dame", "roman", "patrimoine"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1848-revolution-republique",
    countryQid: "Q142", lang: "fr",
    momentKey: "revolution-de-1848-deuxieme-republique",
    momentLabel: "Révolution de 1848 et proclamation de la IIe République",
    label: "la révolution de 1848 et la IIe République",
    category: "foundational_event", theme: "administration", gestureRoot: "revolution_1848",
    editorialScore: 96,
    date: "1848-02-24", year: 1848, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Chute de Louis-Philippe et proclamation de la IIe République",
    beforeState: "Avant février 1848, la monarchie de Juillet gouverne la France avec un suffrage censitaire très restreint.",
    afterState: "Après le 24 février 1848, la IIe République est proclamée, l'esclavage aboli, le suffrage universel masculin instauré.",
    gestureChanged: "Tu peux voter pour la première fois sans condition de fortune, quel que soit ton état.",
    materialAnchor: "Affiche de proclamation républicaine, Marianne, barricades parisiennes",
    sceneText: "24 février 1848, Paris. Louis-Philippe abdique. Sur les barricades, on acclame la République. Lamartine lit la proclamation. Dans les semaines qui suivent : abolition de l'esclavage, suffrage universel, liberté de presse. Le moment dure — mais l'équilibre est fragile.",
    fact: "Le 24 février 1848, la révolution parisienne chasse Louis-Philippe et proclame la IIe République, qui abolit l'esclavage le 27 avril et instaure le suffrage universel masculin le 5 mars.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/R%C3%A9volution_fran%C3%A7aise_de_1848", authority: false },
      { label: "Assemblée nationale histoire", url: "https://www2.assemblee-nationale.fr/decouvrir-l-assemblee/histoire/la-deuxieme-republique", authority: true }
    ],
    tags: ["revolution", "republique", "1848", "suffrage"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1857-madame-bovary-flaubert",
    countryQid: "Q142", lang: "fr",
    momentKey: "lire-madame-bovary-flaubert-proces",
    momentLabel: "Madame Bovary de Flaubert — roman et procès retentissant",
    label: "Madame Bovary et le procès de Flaubert",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "flaubert_bovary",
    editorialScore: 93,
    date: "1857-01-29", year: 1857, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Publication de Madame Bovary et procès pour outrage aux mœurs",
    beforeState: "Avant 1857, le roman réaliste ne décrit pas la vie provinciale ordinaire ni les désirs des femmes avec une telle franchise clinique.",
    afterState: "Après 1857, Madame Bovary définit le réalisme littéraire français et le modèle du roman psychologique moderne.",
    gestureChanged: "Tu peux lire un roman qui décrit la vie d'une femme ordinaire, son ennui, ses désirs, ses erreurs, sans les condamner du regard de Dieu.",
    materialAnchor: "Roman en volume, coupures de presse du procès, portrait de Flaubert",
    sceneText: "1857, Paris. Flaubert est traduit en justice pour Madame Bovary. On l'acquitte, mais le roman est partout. Emma Bovary n'est pas un personnage moral — elle est une femme qui s'ennuie, rêve et se trompe. La littérature française vient de regarder en face quelque chose qu'elle évitait.",
    fact: "Publié en 1857 après une prépublication en revue, Madame Bovary de Gustave Flaubert vaut à son auteur un procès pour 'outrage à la morale publique' dont il sort acquitté, le roman devenant un monument du réalisme.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Madame_Bovary", authority: false },
      { label: "BnF", url: "https://gallica.bnf.fr/ark:/12148/bpt6k6365024b", authority: true }
    ],
    tags: ["flaubert", "roman", "realisme", "proces"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1863-salon-des-refuses",
    countryQid: "Q142", lang: "fr",
    momentKey: "salon-des-refuses-1863-manet",
    momentLabel: "Le Salon des refusés de 1863 et Le Déjeuner sur l'herbe",
    label: "le Salon des refusés de 1863",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "salon_refuses",
    editorialScore: 90,
    date: "1863-05-15", year: 1863, datePrecision: "day",
    placeName: "Palais de l'Industrie, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Ouverture du Salon des refusés par décret de Napoléon III",
    beforeState: "Avant 1863, le Salon officiel est la seule vitrine pour les peintres — être refusé, c'est disparaître de la scène artistique.",
    afterState: "Après 1863, une peinture indépendante du Salon officiel commence à exister, ouvrant la voie à l'impressionnisme.",
    gestureChanged: "Tu peux voir des tableaux refusés par l'Académie et juger toi-même si le jury officiel avait tort.",
    materialAnchor: "Catalogue du Salon des refusés, tableau Le Déjeuner sur l'herbe de Manet, carton d'invitation",
    sceneText: "15 mai 1863, Paris. Le Salon des refusés ouvre dans un couloir adjacent au Salon officiel. Le public vient pour se moquer — et reste, déconcerté. Le Déjeuner sur l'herbe de Manet choque : une femme nue, deux hommes habillés, en plein air. Ce n'est pas un nu mythologique. C'est maintenant.",
    fact: "Le 15 mai 1863, Napoléon III ordonne l'ouverture d'un Salon des refusés où les œuvres écartées par le jury officiel sont exposées, permettant au public de juger. Le Déjeuner sur l'herbe de Manet y devient la pièce la plus commentée.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Salon_des_refus%C3%A9s", authority: false },
      { label: "Musée d'Orsay", url: "https://www.musee-orsay.fr/", authority: true }
    ],
    tags: ["manet", "salon", "peinture", "paris"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1871-commune-de-paris",
    countryQid: "Q142", lang: "fr",
    momentKey: "commune-de-paris-1871",
    momentLabel: "La Commune de Paris — insurrection et semaine sanglante",
    label: "la Commune de Paris de 1871",
    category: "foundational_event", theme: "administration", gestureRoot: "commune_paris",
    editorialScore: 97,
    date: "1871-03-18", year: 1871, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Insurrection de la Commune de Paris",
    beforeState: "Après la défaite de 1870 face à la Prusse, Paris est humilié, affamé, désarmé — la capitulation provoque une insurrection ouvrière.",
    afterState: "Après la Semaine sanglante de mai 1871, la Commune est écrasée dans le sang. Mais ses idées — séparation église-état, droits ouvriers — marqueront la gauche française pour un siècle.",
    gestureChanged: "Tu peux voir comment une ville peut s'autogouverner pendant deux mois, et comment une répression peut laisser une mémoire collective indélébile.",
    materialAnchor: "Mur des Fédérés, drapeau rouge, décrets de la Commune",
    sceneText: "18 mars 1871, Paris. La ville refuse de livrer ses canons au gouvernement de Versailles. La Commune est proclamée. Pendant 72 jours, Paris s'autogère, expérimente, débat. En mai, l'armée entre et massacre. Le Mur des Fédérés reste.",
    fact: "La Commune de Paris, du 18 mars au 28 mai 1871, est la première expérience de gouvernement ouvrier dans une grande capitale occidentale. La répression fait entre 10 000 et 30 000 morts.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Commune_de_Paris_(1871)", authority: false },
      { label: "Musée de Montmartre", url: "https://museedemontmartre.fr/", authority: true }
    ],
    tags: ["commune", "paris", "1871", "insurrection"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1880-fete-nationale-14-juillet",
    countryQid: "Q142", lang: "fr",
    momentKey: "fete-nationale-14-juillet",
    momentLabel: "Premier 14 Juillet comme fête nationale officielle",
    label: "le 14 Juillet, fête nationale républicaine",
    category: "foundational_event", theme: "administration", gestureRoot: "fete_nationale",
    editorialScore: 91,
    date: "1880-07-14", year: 1880, datePrecision: "day",
    placeName: "Paris et villes de France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Première célébration du 14 Juillet comme fête nationale",
    beforeState: "Avant 1880, la France républicaine n'a pas de jour de fête nationale officiel — les régimes qui se succèdent ont leurs propres commémorations.",
    afterState: "Après 1880, le 14 Juillet est la fête nationale de la IIIe République : bals populaires, défilés militaires, feux d'artifice.",
    gestureChanged: "Tu peux participer au bal du 14 Juillet dans ta rue, regarder le feu d'artifice et te sentir français dans un rituel républicain partagé.",
    materialAnchor: "Fanion tricolore, bal populaire, feu d'artifice, lampions",
    sceneText: "14 juillet 1880, Paris. Pour la première fois, le 14 Juillet est jour officiel. La ville danse dans les rues. Des fanfares, des bals, des feux. Ce qui était une date de révolution devient un rituel de paix républicaine. La République se fête elle-même.",
    fact: "Le 6 juillet 1880, le 14 Juillet est institué fête nationale française. Le premier 14 Juillet officiel, le 14 juillet 1880, est célébré dans toute la France avec des bals et des défilés.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/F%C3%AAte_nationale_fran%C3%A7aise", authority: false },
      { label: "Sénat", url: "https://www.senat.fr/evenement/14juillet/histoire.html", authority: true }
    ],
    tags: ["14-juillet", "fete-nationale", "republique", "paris"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1888-affaire-dreyfus",
    countryQid: "Q142", lang: "fr",
    momentKey: "affaire-dreyfus-jaccuse-zola",
    momentLabel: "L'affaire Dreyfus et le J'accuse de Zola",
    label: "l'affaire Dreyfus et le J'accuse de Zola",
    category: "foundational_event", theme: "administration", gestureRoot: "dreyfus",
    editorialScore: 98,
    date: "1898-01-13", year: 1898, datePrecision: "day",
    placeName: "L'Aurore, journal, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Publication du J'accuse d'Émile Zola dans L'Aurore",
    beforeState: "Depuis 1894, Alfred Dreyfus, officier juif, est condamné injustement pour trahison — une erreur judiciaire couverte par l'armée.",
    afterState: "Après le J'accuse, la France se déchire entre dreyfusards et antidreyfusards. L'affaire aboutit à la réhabilitation de Dreyfus et à la loi de séparation de l'Église et de l'État.",
    gestureChanged: "Tu peux prendre parti publiquement dans un débat qui dépasse le cas Dreyfus — il touche à la justice, à l'antisémitisme, à la République.",
    materialAnchor: "Journal L'Aurore avec le J'accuse en manchette, portrait de Dreyfus en uniforme",
    sceneText: "13 janvier 1898. L'Aurore sort avec en première page : J'Accuse ! La lettre de Zola au Président de la République nomme les coupables. Paris se divise. Les familles se déchirent. Ce n'est plus seulement Dreyfus — c'est la France qui choisit ce qu'elle veut être.",
    fact: "Le 13 janvier 1898, Émile Zola publie J'accuse dans L'Aurore, dénonçant le complot de l'armée contre Dreyfus et provoquant une crise politique majeure qui durera jusqu'à la réhabilitation en 1906.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Affaire_Dreyfus", authority: false },
      { label: "BnF Gallica", url: "https://gallica.bnf.fr/ark:/12148/bpt6k701453w", authority: true }
    ],
    tags: ["dreyfus", "zola", "justice", "antisemitisme"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1900-exposition-universelle",
    countryQid: "Q142", lang: "fr",
    momentKey: "exposition-universelle-paris-1900",
    momentLabel: "Exposition universelle de Paris 1900 — le bilan d'un siècle",
    label: "l'Exposition universelle de Paris 1900",
    category: "foundational_event", theme: "loisirs", gestureRoot: "expo_1900",
    editorialScore: 94,
    date: "1900-04-14", year: 1900, datePrecision: "day",
    placeName: "Champ-de-Mars et quais de Seine, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Ouverture de l'Exposition universelle de Paris 1900",
    beforeState: "Avant 1900, aucune exposition n'a encore su rassembler autant de nations et illustrer autant de technologies nouvelles.",
    afterState: "Après 1900, Paris s'impose comme capitale de la modernité — le métro y ouvre, le Grand Palais et le Petit Palais sont inaugurés.",
    gestureChanged: "Tu peux visiter des pavillons du monde entier, voir le cinéma, l'électricité et l'automobile présentés comme les merveilles du nouveau siècle.",
    materialAnchor: "Billet d'entrée, catalogue officiel, palais des machines, lampes électriques",
    sceneText: "14 avril 1900, Paris. Les 50 millions de visiteurs attendus voient un Paris transformé : les quais illuminés à l'électricité, un métro qui vient d'ouvrir, des pavillons de 40 nations alignés. C'est la fête du siècle qui s'achève et du suivant qui commence.",
    fact: "L'Exposition universelle de Paris de 1900 accueille 48 millions de visiteurs, inaugure le Grand Palais, le Petit Palais, le métro et illustre les promesses techniques du XXe siècle.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Exposition_universelle_de_1900", authority: false },
      { label: "Grand Palais", url: "https://www.grandpalais.fr/fr/article/lexposition-universelle-de-1900", authority: true }
    ],
    tags: ["expo", "paris", "1900", "modernite"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1907-cubisme-picasso",
    countryQid: "Q142", lang: "fr",
    momentKey: "demoiselles-davignon-picasso-cubisme",
    momentLabel: "Les Demoiselles d'Avignon de Picasso — naissance du cubisme",
    label: "Les Demoiselles d'Avignon et la naissance du cubisme",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "cubisme",
    editorialScore: 92,
    date: "1907-01-01", year: 1907, datePrecision: "year",
    placeName: "Bateau-Lavoir, Montmartre, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Picasso peint Les Demoiselles d'Avignon, déclenchant le mouvement cubiste",
    beforeState: "Avant 1907, la peinture reste attachée à la représentation du volume et de la perspective héritée de la Renaissance.",
    afterState: "Après 1907, le cubisme fracture la perspective unique et ouvre la modernité picturale du XXe siècle.",
    gestureChanged: "Tu peux voir dans une galerie parisienne des visages peints sous plusieurs angles simultanément — une révolution dans la manière de représenter le réel.",
    materialAnchor: "Toile à l'huile, atelier de Montmartre, facettes géométriques",
    sceneText: "1907, Montmartre. Dans l'atelier du Bateau-Lavoir, Picasso retourne sa toile vers ses amis. Cinq femmes, plusieurs points de vue à la fois, des visages fractionnés. Braque ne comprend pas tout de suite. Apollinaire non plus. Mais quelque chose vient de changer dans l'idée même de ce que voir veut dire.",
    fact: "Peint en 1907 dans l'atelier de Picasso à Montmartre, Les Demoiselles d'Avignon marque la rupture avec la représentation classique et annonce le cubisme, mouvement fondateur de l'art moderne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Les_Demoiselles_d%27Avignon", authority: false },
      { label: "MoMA", url: "https://www.moma.org/collection/works/79766", authority: true }
    ],
    tags: ["picasso", "cubisme", "peinture", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1913-sacre-du-printemps",
    countryQid: "Q142", lang: "fr",
    momentKey: "sacre-du-printemps-stravinsky-nijinski",
    momentLabel: "Le Sacre du printemps — scandale et révolution musicale",
    label: "Le Sacre du printemps de Stravinsky",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "sacre_printemps",
    editorialScore: 91,
    date: "1913-05-29", year: 1913, datePrecision: "day",
    placeName: "Théâtre des Champs-Élysées, Paris", placeType: "site", placeQid: "Q1420060",
    triggerLabel: "Première du Sacre du printemps par les Ballets russes, scandaleuse",
    beforeState: "Avant mai 1913, l'opéra et le ballet reposent sur des codes harmoniques et chorégraphiques établis depuis le XVIIIe siècle.",
    afterState: "Après le 29 mai 1913, le Sacre du printemps fracture les conventions musicales et chorégraphiques — la musique du XXe siècle est née.",
    gestureChanged: "Tu peux entendre des dissonances, des rythmes primitifs et irréguliers dans une salle de concert parisienne — et être dans la salle quand l'histoire de la musique bascule.",
    materialAnchor: "Programme des Ballets russes, partition de Stravinsky, chahut du public",
    sceneText: "29 mai 1913, Théâtre des Champs-Élysées. Dès les premières mesures, des sifflets. La salle se divise. Nijinski gesticule pour que les danseurs entendent les tempos. Stravinsky reste dans les coulisses. Le chahut couvre l'orchestre. Et pourtant cette nuit-là, quelque chose dans la musique occidentale ne reviendra jamais en arrière.",
    fact: "Le 29 mai 1913, la première du Sacre du printemps d'Igor Stravinsky, chorégraphié par Nijinski pour les Ballets russes, provoque un scandale retentissant au Théâtre des Champs-Élysées, marquant le début de la musique moderne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Le_Sacre_du_printemps", authority: false },
      { label: "Philharmonie de Paris", url: "https://philharmoniedeparis.fr/fr/musique/le-sacre-du-printemps", authority: true }
    ],
    tags: ["stravinsky", "ballet", "paris", "scandale"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1916-verdun",
    countryQid: "Q142", lang: "fr",
    momentKey: "bataille-de-verdun-1916",
    momentLabel: "La bataille de Verdun — symbole de la Grande Guerre",
    label: "la bataille de Verdun",
    category: "foundational_event", theme: "administration", gestureRoot: "verdun",
    editorialScore: 99,
    date: "1916-02-21", year: 1916, datePrecision: "day",
    placeName: "Verdun, Meuse", placeType: "site", placeQid: "Q47085",
    triggerLabel: "Début de la bataille de Verdun, la plus longue de la Grande Guerre",
    beforeState: "Avant février 1916, Verdun est une ville de garnison fortifiée — les combats font rage ailleurs sur le front.",
    afterState: "Après Verdun, la ville et ses forts sont devenus le symbole de la résistance et du sacrifice français — 300 000 morts en dix mois.",
    gestureChanged: "Tu ne peux pas ne pas avoir quelqu'un de ta famille dans cette bataille. Verdun n'est pas une bataille parmi d'autres — c'est un mot qui dit toute la guerre.",
    materialAnchor: "Obus, casque Adrian, voie sacrée, forts de Douaumont",
    sceneText: "21 février 1916, Verdun. Le bombardement commence avant l'aube. En dix mois, les deux armées se tuent pour quelques kilomètres de boue. Les blessés arrivent par la Voie sacrée. Les civils entendent le canon à 200 kilomètres. Verdun entre dans la langue comme un mot qui signifie : tout.",
    fact: "La bataille de Verdun (21 février – 19 décembre 1916) est la plus longue de la Première Guerre mondiale. Elle fait environ 300 000 morts et reste le symbole du sacrifice français dans la Grande Guerre.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Bataille_de_Verdun", authority: false },
      { label: "Mémorial de Verdun", url: "https://www.memorial-de-verdun.fr/", authority: true }
    ],
    tags: ["verdun", "guerre", "1916", "sacrifice"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1922-surrealisme-breton",
    countryQid: "Q142", lang: "fr",
    momentKey: "surrealisme-breton-manifeste",
    momentLabel: "Le surréalisme — manifeste d'André Breton",
    label: "le surréalisme d'André Breton",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "surrealisme",
    editorialScore: 88,
    date: "1924-10-15", year: 1924, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Publication du Manifeste du surréalisme par André Breton",
    beforeState: "Avant octobre 1924, Dada a secoué l'art mais sans doctrine nouvelle — le mouvement s'épuise dans la provocation.",
    afterState: "Après le Manifeste, le surréalisme fédère des écrivains et des peintres autour de l'automatisme et du rêve comme matériau artistique.",
    gestureChanged: "Tu peux lire des textes où les mots s'associent librement, sans logique narrative imposée — et voir ça comme de l'art, pas du délire.",
    materialAnchor: "Manifeste du surréalisme, écriture automatique, revue La Révolution surréaliste",
    sceneText: "Octobre 1924, Paris. Le Manifeste du surréalisme circule dans les ateliers et les cafés. Breton y définit l'écriture automatique, le rêve, l'inconscient comme seuls maîtres. Dalí, Ernst, Éluard, Aragon — un mouvement se constitue autour d'un mot nouveau qui dit quelque chose de vrai sur l'époque.",
    fact: "En octobre 1924, André Breton publie le Manifeste du surréalisme, fondant officiellement le mouvement qui réunira Dalí, Éluard, Aragon, Ernst et influencera l'art mondial pendant des décennies.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Surr%C3%A9alisme", authority: false },
      { label: "Centre Pompidou", url: "https://www.centrepompidou.fr/fr/parcours/le-surrealisme", authority: true }
    ],
    tags: ["surrealisme", "breton", "paris", "art"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
];
