import type { CulturalMomentEntry } from "../../../types";

/** Couverture culturelle ciblée : une entrée par année listée dans catalog_gap_report (year = année affichée). */
export const FR_CULTURAL_FILL3_1826_1924: CulturalMomentEntry[] = [
  {
    id: "fr-1826-vigny-cinq-mars",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "vigny-cinq-mars-roman-1826",
    momentLabel: "Alfred de Vigny publie Cinq-Mars",
    label: "Cinq-Mars d'Alfred de Vigny",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "vigny_cinq_mars",
    editorialScore: 86,
    date: "1826-01-01",
    year: 1826,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Publication du roman historique Cinq-Mars",
    beforeState: "Le roman historique français reste encore marqué par le modèle classique.",
    afterState: "Cinq-Mars impose une fiction politique et psychologique sur la Fronde et Richelieu.",
    gestureChanged: "Tu peux lire un roman qui mêle intrigue de cour, passion et destin individuel sous Richelieu.",
    materialAnchor: "Volume en reliure, feuilleton, salon littéraire",
    sceneText: "1826, Paris. Cinq-Mars paraît en librairie. Vigny raconte la conjuration du favori de Louis XIII. Le roman historique gagne en densité psychologique — la cour de France devient matière de tragédie moderne.",
    fact: "En 1826, Alfred de Vigny publie Cinq-Mars, roman historique sur la conjuration de Cinq-Mars contre Richelieu, qui marque le romantisme du roman français.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Cinq-Mars_(roman)", authority: false }],
    tags: ["vigny", "roman", "romantisme", "richelieu"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1828-salon-delacroix-mort-sardanapale",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "salon-1828-delacroix",
    momentLabel: "Le Salon de 1828 et la peinture romantique",
    label: "Le Salon de 1828 à Paris",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "salon_1828",
    editorialScore: 84,
    date: "1828-05-01",
    year: 1828,
    datePrecision: "month",
    placeName: "Louvre, Paris",
    placeType: "site",
    placeQid: "Q188223",
    triggerLabel: "Salon annuel des Beaux-Arts sous la Restauration",
    beforeState: "Le Salon reste le lieu officiel où se joue la carrière d'un peintre en France.",
    afterState: "Les romantiques y affichent des toiles de plus en plus colorées et dramatiques.",
    gestureChanged: "Tu peux te presser devant les grands formats et débattre du mérite des couleurs et du dessin.",
    materialAnchor: "Catalogue du Salon, toile encadrée, foule dans les salles",
    sceneText: "1828, Paris. Sous les voûtes du Louvre, le Salon attire bourgeois, artistes et critiques. Delacroix, Scheffer, les noms se disputent l'attention. La peinture française se transforme sous les yeux du public.",
    fact: "Le Salon de peinture et de sculpture de 1828 se tient au Louvre ; c'est l'événement annuel majeur de la vie artistique parisienne sous la Restauration.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Salon_de_peinture_et_de_sculpture", authority: false }],
    tags: ["salon", "peinture", "louvre", "restauration"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1836-musset-confession-enfant-siecle",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "musset-confession-1836",
    momentLabel: "La Confession d'un enfant du siècle d'Alfred de Musset",
    label: "La Confession d'un enfant du siècle",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "musset_confession",
    editorialScore: 90,
    date: "1836-01-01",
    year: 1836,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Publication du roman autobiographique de Musset",
    beforeState: "Le roman français peine encore à dire le désenchantement intime de la génération post-révolutionnaire.",
    afterState: "Musset donne voix au mal du siècle et à la passion brisée.",
    gestureChanged: "Tu peux lire un récit à la première personne qui mêle amour, mélancolie et désillusion après 1830.",
    materialAnchor: "Volume broché, portrait de George Sand, fumée de cigare au café",
    sceneText: "1836, Paris. La Confession d'un enfant du siècle circule. Octave erre entre le vertige et le dégoût. La génération de Musset se reconnaît dans ce ton — ni héros, ni saints, seulement des cœurs égarés.",
    fact: "En 1836, Alfred de Musset publie La Confession d'un enfant du siècle, roman autobiographique emblématique du mal du siècle après les journées de Juillet 1830.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/La_Confession_d%27un_enfant_du_si%C3%A8cle", authority: false }],
    tags: ["musset", "roman", "mal-du-siecle", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1840-exposition-nationale-industrie",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "exposition-industrie-paris-1840",
    momentLabel: "Exposition des produits de l'industrie nationale à Paris",
    label: "L'exposition de l'industrie française de 1840",
    category: "venue_opening",
    theme: "travail",
    gestureRoot: "expo_industrie_1840",
    editorialScore: 82,
    date: "1840-03-01",
    year: 1840,
    datePrecision: "month",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Onzième exposition des produits de l'industrie française",
    beforeState: "L'industrie française se découvre encore timidement au grand public.",
    afterState: "Les expositions nationales célèbrent machines, textiles et savoir-faire.",
    gestureChanged: "Tu peux voir machines à vapeur, tissus et prototypes dans un même lieu — la culture technique devient spectacle.",
    materialAnchor: "Hall d'exposition, machine à vapeur, médailles d'argent",
    sceneText: "1840, Paris. L'exposition de l'industrie attire curieux et ingénieurs. On compare les métiers à tisser, les outils, les modèles réduits. La France entière se mesure à travers ses fabriques.",
    fact: "En 1840 s'ouvre à Paris la onzième exposition des produits de l'industrie française, grand rendez-vous de la mécanique et des arts industriels sous la monarchie de Juillet.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Exposition_des_produits_de_l%27industrie_fran%C3%A7aise", authority: false }],
    tags: ["exposition", "industrie", "paris", "technique"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1842-heine-chateaubriand-scene-litteraire",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "scene-litteraire-paris-1842",
    momentLabel: "Paris, carrefour des écrivains européens",
    label: "La vie littéraire parisienne en 1842",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "scene_litteraire_1842",
    editorialScore: 80,
    date: "1842-01-01",
    year: 1842,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Cafés, revues et salons sous la monarchie de Juillet",
    beforeState: "La capitale concentre déjà journaux et éditeurs.",
    afterState: "Les échanges entre romantiques et réalistes naissants structurent la vie des lettres.",
    gestureChanged: "Tu peux croiser critiques, poètes et romanciers dans les mêmes cafés — la réputation se fait par les revues.",
    materialAnchor: "Café de la Régence, journal plié, pipe et encrier",
    sceneText: "1842, Paris. Les revues se disputent les feuilletons. Balzac, Sand, les journaux politiques et littéraires se croisent. La ville est une scène où l'on publie, attaque, se rétracte — jour après jour.",
    fact: "Sous la monarchie de Juillet, Paris est le centre de la presse et du roman-feuilleton ; en 1842, la vie littéraire s'organise autour des revues et des salons parisiens.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Monarchie_de_Juillet", authority: false }],
    tags: ["litterature", "paris", "revues", "romantisme"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1843-balzac-illusions-perdues-suite",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "balzac-comedie-humaine-1843",
    momentLabel: "Balzac et la Comédie humaine en expansion",
    label: "Balzac poursuit la Comédie humaine",
    category: "work_release",
    theme: "loisirs",
    gestureRoot: "balzac_1843",
    editorialScore: 88,
    date: "1843-01-01",
    year: 1843,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Nouveaux volumes de la Comédie humaine",
    beforeState: "Le lecteur suit déjà des centaines de personnages balzaciens.",
    afterState: "La fresque de la société française se densifie roman après roman.",
    gestureChanged: "Tu peux retrouver un personnage croisé dans un autre volume — la comédie humaine devient un univers refermé.",
    materialAnchor: "Édition Furne, arbre des personnages, boulevard des Italiens",
    sceneText: "1843, Paris. Balzac alimente les librairies. Rastignac, Vautrin, Balthazar Claës — les figures se recoupent. La France de la monarchie de Juillet tient dans des volumes reliés de vert.",
    fact: "En 1843, Honoré de Balzac poursuit la publication de la Comédie humaine, cycle romanesque visant à peindre toute la société française sous la Restauration et la monarchie de Juillet.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/La_Com%C3%A9die_humaine", authority: false }],
    tags: ["balzac", "roman", "comedie-humaine", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1844-daumier-lithographie",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "daumier-caricature-1844",
    momentLabel: "Daumier et la gravure d'actualité à Paris",
    label: "Honoré Daumier et la caricature politique",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "daumier_1844",
    editorialScore: 85,
    date: "1844-01-01",
    year: 1844,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Lithographies et charges dans la presse parisienne",
    beforeState: "L'image d'actualité reste un outil politique puissant mais artisanal.",
    afterState: "Daumier immortalise députés et bourgeois pour des milliers de lecteurs.",
    gestureChanged: "Tu peux reconnaître un ministère entier en silhouettes grotesques sur une feuille pliée.",
    materialAnchor: "Lithographie, presse satirique, buste de Robert Macaire",
    sceneText: "1844, Paris. Les kiosques vendent le Charivari. Daumier décape les poses. Le rire et la colère se lisent en traits de crayon — l'opinion publique a un visage.",
    fact: "Honoré Daumier est l'un des maîtres de la lithographie politique et sociale à Paris au milieu du XIXe siècle ; ses séries pour Le Charivari marquent la vie visuelle de la monarchie de Juillet.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Honor%C3%A9_Daumier", authority: false }],
    tags: ["daumier", "lithographie", "presse", "satire"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1845-michelet-histoire-france",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "michelet-histoire-de-france-1845",
    momentLabel: "Jules Michelet poursuit son Histoire de France",
    label: "L'Histoire de France de Jules Michelet",
    category: "work_release",
    theme: "loisirs",
    gestureRoot: "michelet_histoire",
    editorialScore: 87,
    date: "1845-01-01",
    year: 1845,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Publication des volumes de l'Histoire de France",
    beforeState: "L'histoire nationale se raconte encore souvent comme chronique des rois.",
    afterState: "Michelet fait de l'histoire une épopée du peuple et du paysage français.",
    gestureChanged: "Tu peux lire la France comme un personnage vivant — forêts, villes, soulèvements.",
    materialAnchor: "Volumes reliés, carte de France, bureau de professeur",
    sceneText: "1845, Paris. Michelet compile archives et passions. Son Histoire de France déplace le regard du trône vers la foule. Les librairies expédient les tomes — l'école républicaine lira plus tard ces pages.",
    fact: "Jules Michelet publie entre 1833 et 1867 son Histoire de France en plusieurs volumes ; au milieu du siècle, l'œuvre façonne l'imaginaire national sous la monarchie de Juillet.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Histoire_de_France_(Jules_Michelet)", authority: false }],
    tags: ["michelet", "histoire", "nation", "livre"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1850-mort-balzac",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "mort-balzac-1850",
    momentLabel: "La mort d'Honoré de Balzac",
    label: "La mort d'Honoré de Balzac en 1850",
    category: "foundational_event",
    theme: "loisirs",
    gestureRoot: "mort_balzac",
    editorialScore: 92,
    date: "1850-08-18",
    year: 1850,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Décès du romancier Honoré de Balzac",
    beforeState: "Balzac alimente encore la Comédie humaine de projets et de corrections.",
    afterState: "La France perd son romancier le plus prolifique du siècle.",
    gestureChanged: "Tu peux voir tout un pan de la vie parisienne résumé en funérailles nationales et hommages.",
    materialAnchor: "Cercueil, Père-Lachaise, deuil littéraire",
    sceneText: "18 août 1850, Paris. Balzac s'éteint rue Fortunée. Hugo pleure un géant. La Comédie humaine reste inachevée — mais le pays a désormais sa fresque dans des milliers de pages.",
    fact: "Honoré de Balzac meurt le 18 août 1850 à Paris ; ses funérailles au Père Lachaise rassemblent une foule immense et consacrent le romancier comme figure centrale de la littérature française.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Honor%C3%A9_de_Balzac", authority: false }],
    tags: ["balzac", "mort", "litterature", "paris"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1852-comedie-francaise-siege",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "comedie-francaise-second-empire",
    momentLabel: "La Comédie-Française sous le Second Empire",
    label: "Le théâtre français au début du Second Empire",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "comedie_1852",
    editorialScore: 80,
    date: "1852-12-02",
    year: 1852,
    datePrecision: "day",
    placeName: "Comédie-Française, Paris",
    placeType: "site",
    placeQid: "Q273528",
    triggerLabel: "Institution théâtrale et censure sous Napoléon III",
    beforeState: "Le théâtre officiel français reste une référence européenne.",
    afterState: "Le Second Empire encadre spectacles et répertoires.",
    gestureChanged: "Tu peux t'abonner aux loges tout en sachant que la censure lit les manuscrits avant la première.",
    materialAnchor: "Fauteuil de parterre, lustre, rideau de velours",
    sceneText: "1852, Paris. Le coup d'État est passé ; le théâtre se remplit. La Comédie-Française joue le classique et le neuf. Les auteurs dosent provocation et prudence — la salle applaudit, la police note.",
    fact: "Sous le Second Empire, la Comédie-Française demeure l'institution théâtrale centrale de Paris, avec un répertoire soumis à la surveillance des autorités.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Com%C3%A9die-Fran%C3%A7aise", authority: false }],
    tags: ["theatre", "comedie-francaise", "second-empire", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1853-flaubert-bovary-revue",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "flaubert-bovary-revue-1853",
    momentLabel: "Flaubert prépare Madame Bovary en feuilleton",
    label: "Madame Bovary en gestation",
    category: "work_release",
    theme: "loisirs",
    gestureRoot: "flaubert_bovary_prep",
    editorialScore: 86,
    date: "1853-01-01",
    year: 1853,
    datePrecision: "year",
    placeName: "Croisset, Normandie",
    placeType: "site",
    placeQid: null,
    triggerLabel: "Flaubert peaufine son roman sur la province",
    beforeState: "Le roman de mœurs provinciales reste rarement clinique.",
    afterState: "Flaubert travaille une prose qui fera date.",
    gestureChanged: "Tu peux imaginer l'auteur cherchant la phrase juste pendant des mois — le style comme laboratoire.",
    materialAnchor: "Manuscrit griffonné, vue sur la Seine, horloge du salon",
    sceneText: "1853, Croisset. Flaubert grogne, rature, recommence. Madame Bovary mûrit dans le silence normand. Croisset devient un atelier de précision — chaque mot pesé.",
    fact: "Entre 1851 et 1856, Gustave Flaubert rédige Madame Bovary à Croisset ; en 1853, le roman est en pleine élaboration avant sa publication en feuilleton en 1856.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Madame_Bovary", authority: false }],
    tags: ["flaubert", "bovary", "roman", "normandie"],
    quality: { strictPlace: false, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1854-baudelaire-salon",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "baudelaire-critique-salon-1854",
    momentLabel: "Baudelaire critique d'art au Salon",
    label: "Charles Baudelaire critique d'art",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "baudelaire_critique",
    editorialScore: 87,
    date: "1854-01-01",
    year: 1854,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Chroniques de Salon et modernité picturale",
    beforeState: "La critique d'art reste souvent périodique et moralisante.",
    afterState: "Baudelaire théorise la modernité et le peintre de la vie parisienne.",
    gestureChanged: "Tu peux lire un compte-rendu qui parle de vitesse, foule et lumière — pas seulement de sujets nobles.",
    materialAnchor: "Revue illustrée, chevalet vu du dos, flâneur",
    sceneText: "1854, Paris. Baudelaire arpente le Salon et la rue. Il cherche le peintre de la modernité — celui qui saisira le boulevard, la pluie, la foule. La poésie et la critique se rejoignent.",
    fact: "Charles Baudelaire publie des chroniques de Salon et des textes sur la modernité picturale au milieu des années 1850, influençant la réception du réalisme et de l'impressionnisme naissant.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Charles_Baudelaire", authority: false }],
    tags: ["baudelaire", "critique", "art", "salon"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1855-exposition-universelle-paris",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "exposition-universelle-1855",
    momentLabel: "Exposition universelle de Paris 1855",
    label: "L'Exposition universelle de 1855",
    category: "venue_opening",
    theme: "loisirs",
    gestureRoot: "expo_1855",
    editorialScore: 91,
    date: "1855-05-15",
    year: 1855,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Première exposition universelle organisée à Paris",
    beforeState: "Les grandes expositions industrielles restent nationales ou sectorielles.",
    afterState: "Paris accueille nations et pavillons sur les Champs-Élysées.",
    gestureChanged: "Tu peux voir machines, tableaux et produits coloniaux dans un même parcours — le monde entier sous verrière.",
    materialAnchor: "Palais de l'Industrie, plan de l'exposition, foule internationale",
    sceneText: "1855, Paris. Le Palais de l'Industrie ouvre ses nefs. On vient de toute l'Europe. Courbet accroche son pavillon personnel à l'écart — la modernité se discute aussi hors du officiel.",
    fact: "La première exposition universelle à Paris s'ouvre en 1855 près des Champs-Élysées ; elle consacre la capitale comme vitrine industrielle et culturelle de l'Europe.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Exposition_universelle_de_1855", authority: false }],
    tags: ["exposition", "paris", "industrie", "monde"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1858-offenbach-orphee-aux-enfers",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "offenbach-orphee-1858",
    momentLabel: "Orphée aux enfers d'Offenbach",
    label: "Orphée aux enfers au Théâtre des Bouffes-Parisiens",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "offenbach_orphee",
    editorialScore: 89,
    date: "1858-10-21",
    year: 1858,
    datePrecision: "day",
    placeName: "Théâtre des Bouffes-Parisiens, Paris",
    placeType: "site",
    placeQid: null,
    triggerLabel: "Création d'Orphée aux enfers",
    beforeState: "L'opérette reste un genre léger mais encore marginal.",
    afterState: "Offenbach fait du Second Empire une scène de satire musicale brillante.",
    gestureChanged: "Tu peux rire des dieux de l'Olympe en galop — la légende devient cancan.",
    materialAnchor: "Partition, cancan, décor de nuages peints",
    sceneText: "21 octobre 1858, Paris. Orphée aux enfers dérape la mythologie. Le public applaudit le galop final. Offenbach devient le son de la ville — ironie, rythme, lumière.",
    fact: "Le 21 octobre 1858, Jacques Offenbach crée Orphée aux enfers au Théâtre des Bouffes-Parisiens ; l'œuvre devient un emblème de l'opérette du Second Empire.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Orph%C3%A9e_aux_enfers", authority: false }],
    tags: ["offenbach", "operette", "paris", "cancan"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1860-goncourt-journal",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "goncourt-journal-1860",
    momentLabel: "Edmond et Jules de Goncourt tiennent leur Journal",
    label: "Le Journal des Goncourt",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "goncourt_journal",
    editorialScore: 86,
    date: "1860-01-01",
    year: 1860,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Chronique intime de la vie littéraire parisienne",
    beforeState: "Les mémoires d'écrivains restent souvent posthumes et édulcorés.",
    afterState: "Le Journal des Goncourt fixe ragots, portraits et détails du Tout-Paris.",
    gestureChanged: "Tu peux lire ce qu'on murmurait dans les salons — nommément.",
    materialAnchor: "Carnet de notes, invitation pliée, cigare",
    sceneText: "1860, Paris. Les frères Goncourt notent tout : Zola jeune, le Salon, les dîners. Le Journal deviendra un trésor pour l'histoire littéraire — la vie des lettres au jour le jour.",
    fact: "Edmond et Jules de Goncourt rédigent à partir de 1851 leur Journal, chronique minutieuse de la vie littéraire et artistique parisienne ; l'œuvre est publiée après leur mort.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Journal_des_Goncourt", authority: false }],
    tags: ["goncourt", "journal", "litterature", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1862-hugo-misérables",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "hugo-miserables-1862",
    momentLabel: "Les Misérables de Victor Hugo",
    label: "Publication des Misérables",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "hugo_miserables",
    editorialScore: 96,
    date: "1862-03-30",
    year: 1862,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Parution du roman-fleuve de Victor Hugo",
    beforeState: "Le roman social existe mais pas encore à cette échelle populaire.",
    afterState: "Les Misérables font pleurer et débattre des millions de lecteurs.",
    gestureChanged: "Tu peux suivre Jean Valjean, Cosette et les barricades — la France entière en feuilleton.",
    materialAnchor: "Volume épais, gravure de barricade, larmes au coin de l'œil",
    sceneText: "30 mars 1862, Paris. Les Misérables sortent. Les files devant les librairies serpentent. Hugo a mis vingt ans à écrire l'épopée du misérable — la France lit la même histoire au même moment.",
    fact: "Les Misérables de Victor Hugo paraissent en 1862 ; le roman devient un succès international et un monument de la littérature engagée du XIXe siècle.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Les_Mis%C3%A9rables", authority: false }],
    tags: ["hugo", "miserables", "roman", "second-empire"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1865-lautreamont-maldoror",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "comte-lautreamont-maldoror-1865",
    momentLabel: "Les Chants de Maldoror",
    label: "Les Chants de Maldoror (Lautréamont)",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "lautreamont",
    editorialScore: 88,
    date: "1865-01-01",
    year: 1865,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Publication anonyme des premières parties des Chants de Maldoror",
    beforeState: "La prose française reste encore souvent classique et lisible au sens académique.",
    afterState: "Maldoror ouvre la langue à l'hallucination et à la violence poétique.",
    gestureChanged: "Tu peux lire des pages qui mêlent rêve, épouvante et lyrisme — la littérature bascule.",
    materialAnchor: "Brochure noire, nuit, figure hybride",
    sceneText: "1865, Paris. Paraissent les premières parties des Chants de Maldoror. Personne ne sait encore qui est Isidore Ducasse — mais le texte frappe comme un coup de foudre noir.",
    fact: "En 1865 paraissent les premières parties des Chants de Maldoror du comte de Lautréamont, texte qui influencera le surréalisme et la littérature moderne.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Les_Chants_de_Maldoror", authority: false }],
    tags: ["lautreamont", "maldoror", "poesie", "moderne"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1866-verne-voyage-ballon",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "verne-voyage-ballon-1866",
    momentLabel: "Jules Verne et les Voyages extraordinaires",
    label: "Le voyage en ballon dans les Voyages extraordinaires",
    category: "work_release",
    theme: "loisirs",
    gestureRoot: "verne_ballon",
    editorialScore: 85,
    date: "1866-01-01",
    year: 1866,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Suite des publications Hetzel — imaginaire scientifique",
    beforeState: "Le roman d'aventure scientifique reste confidentiel.",
    afterState: "Verse et Hetzel rendent l'exploration accessible à la jeunesse et au grand public.",
    gestureChanged: "Tu peux offrir à un enfant un volume où la science et le récit s'associent.",
    materialAnchor: "Cartonnage Hetzel, gravure de ballon, globe",
    sceneText: "1866, Paris. Les libraires étalent les cartonnages Hetzel. Jules Verne enchaîne les aventures — la France lit l'exploration comme on lit une carte.",
    fact: "Au milieu des années 1860, Jules Verne poursuit les Voyages extraordinaires chez Hetzel, popularisant le roman d'aventures scientifiques en France.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Jules_Verne", authority: false }],
    tags: ["verne", "science-fiction", "hetzel", "roman"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1867-zola-therese-raquin",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "zola-therese-raquin-1867",
    momentLabel: "Thérèse Raquin d'Émile Zola",
    label: "Thérèse Raquin",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "zola_therese",
    editorialScore: 89,
    date: "1867-01-01",
    year: 1867,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Publication du roman naturaliste de Zola",
    beforeState: "Le roman psychologique criminel reste encore dominé par le feuilleton romantique.",
    afterState: "Zola expérimente le naturalisme sur la passion et la culpabilité.",
    gestureChanged: "Tu peux lire un récit où le milieu et les nerfs expliquent le crime.",
    materialAnchor: "Passage couvert, vitre laiteuse, bougie",
    sceneText: "1867, Paris. Thérèse Raquin sort des imprimeries. Zola observe la mécanique du désir et de la honte — le naturalisme trouve un de ses premiers chefs-d'œuvre.",
    fact: "En 1867, Émile Zola publie Thérèse Raquin, roman naturaliste qui marque ses débuts littéraires avant les Rougon-Macquart.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Th%C3%A9r%C3%A8se_Raquin", authority: false }],
    tags: ["zola", "naturalisme", "roman", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1870-guerre-siege-culture-paris",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "culture-paris-siege-1870",
    momentLabel: "Paris assiégé — théâtre et presse sous les bombes",
    label: "La vie culturelle pendant le siège de Paris",
    category: "foundational_event",
    theme: "loisirs",
    gestureRoot: "siege_1870",
    editorialScore: 88,
    date: "1870-09-19",
    year: 1870,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Début du siège de Paris pendant la guerre franco-prussienne",
    beforeState: "Les salles et les journaux fonctionnent encore normalement.",
    afterState: "La capitale vit au rythme des bombes et du rationnement — la culture se réorganise.",
    gestureChanged: "Tu peux assister à des concerts de circonstance ou lire des feuilles réduites — la vie des lettres ne s'arrête pas.",
    materialAnchor: "Journal au format réduit, salle chauffée au bois, ballon monté",
    sceneText: "19 septembre 1870, Paris. Le siège commence. Les théâtres jouent encore ; les journaux paraissent. Les écrivains notent chaque jour — la culture tient sous le feu.",
    fact: "Pendant le siège de Paris (septembre 1870 – janvier 1871), théâtres, journaux et éditeurs maintiennent une activité culturelle malgré les conditions extrêmes.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Si%C3%A8ge_de_Paris_(1870-1871)", authority: false }],
    tags: ["siege", "guerre", "paris", "1870"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1876-deuxieme-exposition-impressionnistes",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "exposition-impressionnistes-1876",
    momentLabel: "La deuxième exposition des impressionnistes",
    label: "Deuxième exposition du groupe impressionniste",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "impressionnistes_1876",
    editorialScore: 91,
    date: "1876-04-01",
    year: 1876,
    datePrecision: "month",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Exposition collective des artistes impressionnistes",
    beforeState: "La première exposition du groupe date de 1874.",
    afterState: "Les impressionnistes s'affichent à nouveau sans le Salon officiel.",
    gestureChanged: "Tu peux voir Monet, Degas, Renoir hors du palais — la peinture de plein air s'impose.",
    materialAnchor: "Catalogue d'exposition, cadre sans dorure, lumière du jour",
    sceneText: "1876, Paris. La deuxième exposition des impressionnistes ouvre ses portes. Le public découvre encore ce nom — impressionnisme — qui résume une révolution.",
    fact: "En avril 1876 à Paris se tient la deuxième exposition du groupe impressionniste, après celle de 1874, consolidant les réseaux alternatifs au Salon officiel.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Impressionnisme", authority: false }],
    tags: ["impressionnisme", "exposition", "monet", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1878-exposition-universelle-paris",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "exposition-universelle-1878",
    momentLabel: "Exposition universelle de Paris 1878",
    label: "L'Exposition universelle de 1878",
    category: "venue_opening",
    theme: "loisirs",
    gestureRoot: "expo_1878",
    editorialScore: 90,
    date: "1878-05-01",
    year: 1878,
    datePrecision: "month",
    placeName: "Champ-de-Mars, Paris",
    placeType: "site",
    placeQid: "Q2415831",
    triggerLabel: "Exposition universelle de 1878 sur le Champ-de-Mars",
    beforeState: "Paris a déjà accueilli des expositions universelles.",
    afterState: "La Trocadéro et les grandes nefs célèbrent la IIIe République naissante.",
    gestureChanged: "Tu peux voir machines électriques et pavillons coloniaux dans un même parcours.",
    materialAnchor: "Palais du Trocadéro, plan de visite, foule",
    sceneText: "1878, Paris. Le Champ-de-Mars fourmille. L'électricité éblouit le public. La République affiche sa modernité — et son empire.",
    fact: "L'Exposition universelle de 1878 se tient à Paris sur le Champ-de-Mars ; elle consacre les avancées technologiques et la présence de la IIIe République.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Exposition_universelle_de_1878", authority: false }],
    tags: ["exposition", "paris", "republique", "electricite"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1879-marseillaise-hymne",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "marseillaise-hymne-1879",
    momentLabel: "La Marseillaise devient hymne national",
    label: "La Marseillaise hymne national (1879)",
    category: "foundational_event",
    theme: "administration",
    gestureRoot: "marseillaise_1879",
    editorialScore: 86,
    date: "1879-02-14",
    year: 1879,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "La IIIe République adopte la Marseillaise comme hymne",
    beforeState: "Les hymnes officiels ont changé selon les régimes.",
    afterState: "La Marseillaise devient le symbole sonore de la République.",
    gestureChanged: "Tu peux entendre le même chant dans les écoles et les cérémonies publiques.",
    materialAnchor: "Partition, drapeau, pupitre d'école",
    sceneText: "1879, France. La Marseillaise est désormais l'hymne national. Les Républicains l'enseignent — la Révolution entre dans la voix collective.",
    fact: "En 1879, la IIIe République confirme l'usage de La Marseillaise comme hymne national français.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/La_Marseillaise", authority: false }],
    tags: ["marseillaise", "hymne", "republique", "musique"],
    quality: { strictPlace: false, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1882-rodin-porte-enfer",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "rodin-porte-enfer-1882",
    momentLabel: "Rodin travaille sur la Porte de l'Enfer",
    label: "Auguste Rodin et la Porte de l'Enfer",
    category: "work_release",
    theme: "loisirs",
    gestureRoot: "rodin_porte",
    editorialScore: 91,
    date: "1882-01-01",
    year: 1882,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Rodin poursuit la Porte de l'Enfer pour le musée des Arts décoratifs",
    beforeState: "La sculpture monumentale reste attachée aux commandes officielles classiques.",
    afterState: "Rodin réinvente la sculpture expressive et le fragment.",
    gestureChanged: "Tu peux voir des corps tordus qui sortent du bronze comme d'un cauchemar dantesque.",
    materialAnchor: "Atelier de sculpture, argile, Le Penseur",
    sceneText: "1882, Paris. Rodin modèle la Porte de l'Enfer. Dante devient masse humaine. Le musée attend — l'œuvre ne cessera de muter pendant des décennies.",
    fact: "Auguste Rodin travaille sur la Porte de l'Enfer à partir de 1880 ; au début des années 1880, le projet occupe son atelier et regroupe des figures comme Le Penseur.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/La_Porte_de_l%27Enfer", authority: false }],
    tags: ["rodin", "sculpture", "dante", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1883-maupassant-une-vie",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "maupassant-une-vie-1883",
    momentLabel: "Une vie de Guy de Maupassant",
    label: "Une vie de Guy de Maupassant",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "maupassant_une_vie",
    editorialScore: 90,
    date: "1883-01-01",
    year: 1883,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Publication du premier roman de Maupassant",
    beforeState: "Maupassant est surtout connu pour ses nouvelles.",
    afterState: "Une vie lance le roman naturaliste de Maupassant.",
    gestureChanged: "Tu peux suivre Jeanne de Lamare dans la Normandie — la province devient drame intime.",
    materialAnchor: "Volume relié, manoir normand, lettre de rupture",
    sceneText: "1883, Paris. Une vie paraît. Maupassant prouve qu'il sait tenir un long roman — la Normandie et le malheur conjugal tiennent en un souffle.",
    fact: "En 1883, Guy de Maupassant publie Une vie, roman naturaliste sur la vie d'une femme dans la province normande, premier grand roman de l'auteur.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Une_vie", authority: false }],
    tags: ["maupassant", "roman", "naturalisme", "normandie"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1884-zola-joie-de-vivre",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "zola-joie-de-vivre-1884",
    momentLabel: "La Joie de vivre d'Émile Zola",
    label: "La Joie de vivre d'Émile Zola",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "zola_joie",
    editorialScore: 88,
    date: "1884-01-01",
    year: 1884,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Publication du roman dans les Rougon-Macquart",
    beforeState: "Le cycle des Rougon-Macquart explore déjà la société française.",
    afterState: "La Joie de vivre interroge la dépression et la vitalité face à la mort.",
    gestureChanged: "Tu peux lire un roman où le pessimisme et la résistance se mesurent au fil des jours.",
    materialAnchor: "Maison de campagne, pharmacie, chambre de malade",
    sceneText: "1884, Paris. Zola publie La Joie de vivre. Les Rougon-Macquart avancent — cette fois, c'est le courage face à l'abandon qui tient le roman.",
    fact: "En 1884, Émile Zola publie La Joie de vivre, douzième volume des Rougon-Macquart, portrait de la famille Chanteau et de la lutte contre le découragement.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/La_Joie_de_vivre", authority: false }],
    tags: ["zola", "rougon-macquart", "roman", "naturalisme"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1886-van-gogh-paris",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "van-gogh-paris-1886",
    momentLabel: "Van Gogh à Paris",
    label: "Vincent van Gogh à Paris",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "vangogh_paris",
    editorialScore: 84,
    date: "1886-03-01",
    year: 1886,
    datePrecision: "month",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Arrivée de Van Gogh à Paris — contact avec les impressionnistes",
    beforeState: "Van Gogh peint encore aux Pays-Bas.",
    afterState: "Paris lui révèle impressionnistes et couleur.",
    gestureChanged: "Tu peux partager un atelier avec d'autres peintres — la palette s'éclaircit.",
    materialAnchor: "Chevalet, tubes de peinture, Montmartre",
    sceneText: "1886, Paris. Van Gogh s'installe rue Lepic. Il découvre Signac, Seurat, Bernard. La peinture change de lumière — le Sud viendra plus tard.",
    fact: "Vincent van Gogh s'installe à Paris en 1886 ; il y rencontre les avant-gardes et transforme sa palette avant son départ pour l'Arles.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Vincent_van_Gogh", authority: false }],
    tags: ["van-gogh", "peinture", "paris", "impressionnisme"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1887-bernard-gauguin-pont-aven",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "pont-aven-1887",
    momentLabel: "L'école de Pont-Aven",
    label: "Les peintres à Pont-Aven",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "pont_aven",
    editorialScore: 85,
    date: "1887-01-01",
    year: 1887,
    datePrecision: "year",
    placeName: "Pont-Aven, Bretagne",
    placeType: "city",
    placeQid: "Q178208",
    triggerLabel: "Gauguin et Bernard peignent en Bretagne",
    beforeState: "La Bretagne attire déjà les peintres paysagistes.",
    afterState: "Pont-Aven devient un laboratoire du synthétisme et de la couleur plate.",
    gestureChanged: "Tu peux voir des toiles où le paysage breton devient signe et symbolique.",
    materialAnchor: "Toile aux aplats, bigoudène, auberge",
    sceneText: "1887, Pont-Aven. Gauguin pose ses chevalets. Les toits et les costumes deviennent motifs. La Bretagne n'est plus seulement réaliste — elle est tableau.",
    fact: "À la fin des années 1880, Pont-Aven accueille Paul Gauguin, Émile Bernard et d'autres peintres — la colonie artistique préfigure le synthétisme.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/%C3%89cole_de_Pont-Aven", authority: false }],
    tags: ["gauguin", "bretagne", "peinture", "pont-aven"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1888-seurat-circus",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "seurat-pointillisme-1888",
    momentLabel: "Seurat et le pointillisme",
    label: "Georges Seurat et la division du ton",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "seurat_pointillisme",
    editorialScore: 88,
    date: "1888-01-01",
    year: 1888,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Seurat et le néo-impressionnisme",
    beforeState: "L'impressionnisme domine encore les avant-gardes.",
    afterState: "Seurat systématise la touche en points de couleur.",
    gestureChanged: "Tu peux voir un tableau comme un tissu de points — l'œil mélange les couleurs.",
    materialAnchor: "Toile pointillée, parapluie, Seine",
    sceneText: "1888, Paris. Seurat applique la science des couleurs au chevalet. Le pointillisme transforme la promenade en laboratoire optique.",
    fact: "Georges Seurat développe le divisionisme et le pointillisme au milieu des années 1880, influençant le néo-impressionnisme français.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Georges_Seurat", authority: false }],
    tags: ["seurat", "pointillisme", "neompressionnisme", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1890-mallarme-mardis",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "mallarme-mardis-1890",
    momentLabel: "Les Mardis de Mallarmé",
    label: "Les Mardis de Stéphane Mallarmé",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "mardis_mallarme",
    editorialScore: 87,
    date: "1890-01-01",
    year: 1890,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Réunions littéraires rue de Rome",
    beforeState: "Les salons littéraires existent depuis des décennies.",
    afterState: "Le salon de Mallarmé devient le foyer du symbolisme.",
    gestureChanged: "Tu peux entendre poètes et musiciens débattre jusqu'à minuit — la poésie pure trouve son cercle.",
    materialAnchor: "Tasse de thé, cigarette, feuille manuscrite",
    sceneText: "1890, Paris. Chaque mardi, la rue de Rome réunit le Tout-Paris des lettres. Mallarmé parle bas — la phrase devient événement.",
    fact: "Les Mardis de Stéphane Mallarmé, réunions hebdomadaires dans son appartement parisien, accueillent poètes, musiciens et écrivains de la fin du XIXe siècle.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/St%C3%A9phane_Mallarm%C3%A9", authority: false }],
    tags: ["mallarme", "symbolisme", "salon", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1891-gauguin-tahiti-projet",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "gauguin-1891",
    momentLabel: "Gauguin part pour la Polynésie",
    label: "Paul Gauguin vers Tahiti",
    category: "foundational_event",
    theme: "loisirs",
    gestureRoot: "gauguin_tahiti",
    editorialScore: 89,
    date: "1891-04-01",
    year: 1891,
    datePrecision: "month",
    placeName: "Marseille",
    placeType: "city",
    placeQid: "Q234453",
    triggerLabel: "Départ de Gauguin pour Tahiti",
    beforeState: "La peinture française cherche encore l'ailleurs dans l'atelier.",
    afterState: "Gauguin fait l'expérience du voyage comme renouvellement pictural.",
    gestureChanged: "Tu peux imaginer l'artiste quittant la France pour peindre la lumière et les corps autrement.",
    materialAnchor: "Billet de paquebot, malle, palette",
    sceneText: "1891, Marseille. Gauguin embarque. Il laisse la France et la famille — la couleur du Pacifique l'attend. La peinture moderne prendra un autre continent.",
    fact: "En 1891, Paul Gauguin quitte la France pour Tahiti, où il développe une peinture nouvelle autour de la figure polynésienne.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Paul_Gauguin", authority: false }],
    tags: ["gauguin", "tahiti", "peinture", "voyage"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1894-jarry-caesar-antichrist",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "jarry-1894",
    momentLabel: "Alfred Jarry et les premières farces",
    label: "Alfred Jarry dans la scène avant-gardiste",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "jarry_1894",
    editorialScore: 87,
    date: "1894-01-01",
    year: 1894,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Jarry et le Théâtre des Arts — avant Ubu",
    beforeState: "Le théâtre expérimental reste marginal.",
    afterState: "Jarry prépare une farce qui fera date.",
    gestureChanged: "Tu peux voir un lycéen provoquer le rire et le scandale avant la maturité.",
    materialAnchor: "Marionnette, revue littéraire, Mercure de France",
    sceneText: "1894, Paris. Jarry circule dans les revues. Il prépare les armes d'Ubu — la France littéraire ne sait pas encore ce qui l'attend.",
    fact: "À la fin des années 1890, Alfred Jarry participe dans Paris à la vie des lettres et du théâtre avant la création d'Ubu roi en 1896.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Alfred_Jarry", authority: false }],
    tags: ["jarry", "theatre", "avant-garde", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1896-sarcey-theatre",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "sarcey-chroniques-1896",
    momentLabel: "Francisque Sarcey chroniqueur du théâtre",
    label: "Francisque Sarcey et la critique de théâtre",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "sarcey",
    editorialScore: 80,
    date: "1896-01-01",
    year: 1896,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Chroniques théâtrales dans Le Temps",
    beforeState: "La critique de théâtre guide le public parisien.",
    afterState: "Sarcey incarne l'opinion du fauteuil d'orchestre.",
    gestureChanged: "Tu peux lire le lendemain si la pièce vaut le déplacement — avant la radio.",
    materialAnchor: "Journal Le Temps, jumelles de théâtre, fauteuil",
    sceneText: "1896, Paris. Sarcey signe ses chroniques. Chaque première attend son verdict — le public lit avant d'acheter.",
    fact: "Francisque Sarcey est l'une des figures majeures de la critique théâtrale française à la fin du XIXe siècle.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Francisque_Sarcey", authority: false }],
    tags: ["theatre", "critique", "paris", "presse"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1897-bernhardt-reine",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "sarah-bernhardt-1897",
    momentLabel: "Sarah Bernhardt au sommet",
    label: "Sarah Bernhardt, idole des tréteaux",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "bernhardt",
    editorialScore: 92,
    date: "1897-01-01",
    year: 1897,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Tournées et triomphes de la tragédienne",
    beforeState: "Le théâtre français a déjà ses stars.",
    afterState: "Bernhardt incarne la comédienne mondaine au point de légende.",
    gestureChanged: "Tu peux voir la même actrice jouer à Paris, Londres et New York — la star avant Hollywood.",
    materialAnchor: "Affiche lithographique, voile, coffre",
    sceneText: "1897, Paris. Sarah Bernhardt est la « Divine ». La ville s'arrête quand elle joue — la tragédie française a un visage.",
    fact: "Sarah Bernhardt est l'une des actrices les plus célèbres du monde à la fin du XIXe siècle ; ses tournées font de la scène française un modèle international.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Sarah_Bernhardt", authority: false }],
    tags: ["bernhardt", "theatre", "comedie", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1899-dreyfus-veillée",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "affaire-dreyfus-1899",
    momentLabel: "L'Affaire Dreyfus au tournant du siècle",
    label: "L'Affaire Dreyfus et la culture d'opinion",
    category: "foundational_event",
    theme: "administration",
    gestureRoot: "dreyfus_1899",
    editorialScore: 86,
    date: "1899-09-01",
    year: 1899,
    datePrecision: "month",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Débats et meetings pour la révision du procès",
    beforeState: "L'opinion publique est déjà polarisée.",
    afterState: "Les intellectuels prennent parti pour ou contre Dreyfus — la culture devient combat civique.",
    gestureChanged: "Tu peux lire des tribunes qui engagent l'honneur de la France et de la République.",
    materialAnchor: "Journal L'Aurore, « J'accuse… ! », foule",
    sceneText: "1899, Paris. L'Affaire occupe les cafés. Zola a déjà écrit ; la révision approche. La France se débat dans la presse et la rue.",
    fact: "À la fin des années 1890, l'Affaire Dreyfus structure la vie intellectuelle française et oppose dreyfusards et antidreyfusards.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Affaire_Dreyfus", authority: false }],
    tags: ["dreyfus", "affaire", "republique", "presse"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1901-sully-prudhomme-nobel",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "sully-prudhomme-nobel-1901",
    momentLabel: "Sully Prudhomme, premier prix Nobel de littérature",
    label: "Sully Prudhomme, premier Nobel de littérature",
    category: "foundational_event",
    theme: "loisirs",
    gestureRoot: "nobel_litterature",
    editorialScore: 88,
    date: "1901-12-10",
    year: 1901,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Première attribution du Nobel de littérature à un Français",
    beforeState: "La littérature mondiale n'a pas encore de prix Nobel.",
    afterState: "La France voit son poésie académique couronnée par Stockholm.",
    gestureChanged: "Tu peux lire dans les journaux qu'un Français reçoit le premier Nobel littéraire.",
    materialAnchor: "Une du journal, portrait de Sully Prudhomme, médaille",
    sceneText: "10 décembre 1901, Stockholm. Le tout premier prix Nobel de littérature revient à Sully Prudhomme. La France lit son nom dans une aube nouvelle de gloire littéraire.",
    fact: "En 1901, Sully Prudhomme est le premier lauréat du prix Nobel de littérature, reconnaissant son œuvre poétique et philosophique.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Sully_Prudhomme", authority: false }],
    tags: ["nobel", "litterature", "france", "poesie"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1902-pelleas-melisande",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "debussy-pelleas-1902",
    momentLabel: "Pelléas et Mélisande à l'Opéra-Comique",
    label: "Création de Pelléas et Mélisande",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "debussy_pelleas",
    editorialScore: 95,
    date: "1902-04-30",
    year: 1902,
    datePrecision: "day",
    placeName: "Opéra-Comique, Paris",
    placeType: "site",
    placeQid: "Q1547",
    triggerLabel: "Création de l'opéra de Claude Debussy",
    beforeState: "L'opéra français reste largement wagnérien ou verdiiste.",
    afterState: "Debussy invente une langue musicale symboliste pour la scène.",
    gestureChanged: "Tu peux entendre une musique qui murmure plutôt qu'elle ne crie — le drame devient brume.",
    materialAnchor: "Partition, décor forestier, rideau d'Opéra-Comique",
    sceneText: "30 avril 1902, Opéra-Comique. Pelléas et Mélisande naît. Le public découvre un opéra où l'orchestre tient le silence. La musique française change de siècle.",
    fact: "Le 30 avril 1902, Pelléas et Mélisande de Claude Debussy est créé à l'Opéra-Comique de Paris — œuvre fondatrice de l'opéra moderne français.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Pell%C3%A9as_et_M%C3%A9lisande_(op%C3%A9ra)", authority: false }],
    tags: ["debussy", "opera", "opera-comique", "musique"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1904-salons-automne-printemps",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "salon-automne-1904",
    momentLabel: "Le Salon d'automne",
    label: "Le Salon d'automne de Paris",
    category: "venue_opening",
    theme: "loisirs",
    gestureRoot: "salon_automne",
    editorialScore: 88,
    date: "1904-01-01",
    year: 1904,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Salon d'automne — avant-garde et Cézanne",
    beforeState: "Le Salon officiel filtre encore fortement les modernes.",
    afterState: "Le Salon d'automne accueille Cézanne et les jeunes artistes.",
    gestureChanged: "Tu peux voir la peinture moderne hors du palais officiel.",
    materialAnchor: "Catalogue du Salon d'automne, toile de Cézanne",
    sceneText: "1904, Paris. Le Salon d'automne expose une modernité que le Salon de mai refuse. Le public découvre Cézanne à grande échelle — la rétrospective marque les esprits.",
    fact: "Le Salon d'automne, créé en 1903, organise en 1904 une grande rétrospective de Paul Cézanne, événement fondateur pour la réception de la peinture moderne à Paris.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Salon_d%27automne", authority: false }],
    tags: ["salon-automne", "cezanne", "paris", "moderne"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1908-matisse-fauvisme",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "matisse-fauvisme-1908",
    momentLabel: "Matisse et le fauvisme",
    label: "Henri Matisse et la couleur fauve",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "matisse_fauve",
    editorialScore: 90,
    date: "1908-01-01",
    year: 1908,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Matisse au sommet du fauvisme",
    beforeState: "L'impressionnisme laisse place aux avant-gardes multiples.",
    afterState: "Matisse mène la couleur pure et le grand format décoratif.",
    gestureChanged: "Tu peux voir une femme au vert de face — la couleur n'imite plus la nature.",
    materialAnchor: "Toile fauve, atelier Quai Saint-Michel, tissus",
    sceneText: "1908, Paris. Matisse peint La Desserte — la couleur hurle. Le fauvisme n'est pas une mode — c'est une libération.",
    fact: "En 1908, Henri Matisse peint notamment La Desserte (Harmonie en rouge) ; le fauvisme est au centre des débats de la peinture parisienne.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Henri_Matisse", authority: false }],
    tags: ["matisse", "fauvisme", "peinture", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1909-ballets-russes",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "ballets-russes-1909",
    momentLabel: "Les Ballets russes à Paris",
    label: "Saison des Ballets russes à Paris",
    category: "public_premiere",
    theme: "loisirs",
    gestureRoot: "ballets_russes",
    editorialScore: 94,
    date: "1909-05-19",
    year: 1909,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Première saison parisienne des Ballets russes",
    beforeState: "La danse française reste souvent classique.",
    afterState: "Diaghilev mélange musique, décor et chorégraphie d'avant-garde.",
    gestureChanged: "Tu peux voir Nijinski sauter — le spectacle total arrive.",
    materialAnchor: "Programme de salle, costume oriental, rideau",
    sceneText: "1909, Paris. Le Châtelet applaudit les Ballets russes. Paris découvre Stravinsky, Bakst, Fokine — la scène moderne est née.",
    fact: "En 1909, Serge Diaghilev présente à Paris la première saison des Ballets russes, qui révolutionne la danse et les arts de la scène.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Ballets_russes", authority: false }],
    tags: ["ballets-russes", "diaghilev", "danse", "paris"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1911-ducasse-versailles",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "ducasse-versailles-1911",
    momentLabel: "La fête de Versailles et les arts du spectacle",
    label: "Grandes fêtes à Versailles",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "versailles_1911",
    editorialScore: 78,
    date: "1911-01-01",
    year: 1911,
    datePrecision: "year",
    placeName: "Versailles",
    placeType: "city",
    placeQid: "Q621",
    triggerLabel: "Spectacles et reconstitutions historiques au château",
    beforeState: "Versailles attire déjà les touristes.",
    afterState: "Les fêtes nocturnes mêlent musique et lumière.",
    gestureChanged: "Tu peux te promener dans les jardins illuminés — le patrimoine devient spectacle.",
    materialAnchor: "Bosquet, feu d'artifice, costume de cour",
    sceneText: "1911, Versailles. Le château organise des fêtes de nuit. La France se regarde en Louis XIV — avant la guerre qui changera tout.",
    fact: "Au début du XXe siècle, le château de Versailles développe des spectacles et visites nocturnes qui font du site un monument de la culture de masse.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Ch%C3%A2teau_de_Versailles", authority: false }],
    tags: ["versailles", "patrimoine", "spectacle", "fete"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1915-avant-garde-guerre",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "culture-guerre-1915",
    momentLabel: "Les lettres à l'heure de la guerre",
    label: "La littérature française en 1915",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "litterature_1915",
    editorialScore: 84,
    date: "1915-01-01",
    year: 1915,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Revue NRF et témoignages de la Grande Guerre",
    beforeState: "La vie littéraire était florissante avant 1914.",
    afterState: "Les écrivains au front ou à l'arrière inventent de nouveaux tons.",
    gestureChanged: "Tu peux lire des textes où la guerre est matière brute — plus de belles phrases vides.",
    materialAnchor: "Revue, feuille du front, tampon postal",
    sceneText: "1915, France. Les revues publient encore — mais la voix change. Barbusse prépare Le Feu — le réalisme de la tranchée arrive.",
    fact: "En 1915, la littérature française s'adapte à la Grande Guerre : revues, poèmes et récits témoignent de l'expérience du front et de l'arrière.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Litt%C3%A9rature_de_la_Premi%C3%A8re_Guerre_mondiale", authority: false }],
    tags: ["guerre", "litterature", "1915", "trench"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1917-apollinaire-blessure",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "apollinaire-1917",
    momentLabel: "Apollinaire blessé à la guerre",
    label: "Guillaume Apollinaire au front",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "apollinaire_guerre",
    editorialScore: 86,
    date: "1917-03-17",
    year: 1917,
    datePrecision: "day",
    placeName: "France",
    placeType: "country",
    placeQid: "Q142",
    triggerLabel: "Apollinaire blessé à la tête — Calligrammes",
    beforeState: "Apollinaire écrit depuis le front.",
    afterState: "Sa blessure marque la poésie moderne.",
    gestureChanged: "Tu peux lire des vers qui mêlent tranchées et typographie nouvelle.",
    materialAnchor: "Bandage, casque Adrian, manuscrit",
    sceneText: "17 mars 1917, front. Apollinaire est blessé à la tête. Il survivra — et Calligrammes portera la marque de la guerre dans la forme même du poème.",
    fact: "Le 17 mars 1917, Guillaume Apollinaire est blessé à la tête sur le front ; sa trajectoire de poète-soldat influence la poésie française de l'entre-deux-guerres.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Guillaume_Apollinaire", authority: false }],
    tags: ["apollinaire", "guerre", "poesie", "1917"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1920-cocteau-paris",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "cocteau-1920",
    momentLabel: "Jean Cocteau et les Six",
    label: "Jean Cocteau et les Six",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "cocteau_six",
    editorialScore: 88,
    date: "1920-01-01",
    year: 1920,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Cocteau théorise la musique française d'après-guerre",
    beforeState: "La guerre a laissé la scène artistique fragile.",
    afterState: "Le Groupe des Six incarne une musique française légère et moderne.",
    gestureChanged: "Tu peux entendre Poulenc et Milhaud au cabaret — Paris rit à nouveau.",
    materialAnchor: "Piano, masque, affiche de Parade",
    sceneText: "1920, Paris. Cocteau rassemble les compositeurs. Les Six veulent du neuf — pas de Wagner. Le music-hall devient salle de concert.",
    fact: "Au début des années 1920, Jean Cocteau sert de théoricien au Groupe des Six, composant avec la musique française moderne et Parade (1917) avec Satie.",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Les_Six", authority: false }],
    tags: ["cocteau", "six", "musique", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1922-journal-surrealisme",
    countryQid: "Q142",
    lang: "fr",
    momentKey: "litterature-1922",
    momentLabel: "Paris, laboratoire des avant-gardes",
    label: "La vie littéraire parisienne en 1922",
    category: "symbolic_moment",
    theme: "loisirs",
    gestureRoot: "avant-garde-1922",
    editorialScore: 85,
    date: "1922-01-01",
    year: 1922,
    datePrecision: "year",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Revue Littérature et pré-surréalisme",
    beforeState: "Dada agite encore les esprits.",
    afterState: "Breton et les siens préparent le Manifeste surréaliste.",
    gestureChanged: "Tu peux lire des pages où le rêve et l'automatisme deviennent programme.",
    materialAnchor: "Revue Littérature, café Certa, dés",
    sceneText: "1922, Paris. Littérature publie les textes qui mènent au surréalisme. Le mot n'est pas encore roi — mais le rêve l'est déjà.",
    fact: "En 1922, la revue Littérature, dirigée notamment par André Breton, diffuse les expériences qui mèneront au Manifeste du surréalisme (1924).",
    sources: [{ label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Litt%C3%A9rature_(revue)", authority: false }],
    tags: ["breton", "surrealisme", "revue", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  }
];
