import type { CulturalMomentEntry } from "../../../types";

export const FR_CULTURAL_BACKFILL_1925_1949: CulturalMomentEntry[] = [
  {
    id: "fr-1925-exposition-arts-decoratifs",
    countryQid: "Q142", lang: "fr",
    momentKey: "exposition-internationale-des-arts-decoratifs",
    momentLabel: "Exposition internationale des arts décoratifs de Paris",
    label: "l'Exposition des arts décoratifs de 1925",
    category: "foundational_event", theme: "loisirs", gestureRoot: "art_deco",
    editorialScore: 92,
    date: "1925-04-28", year: 1925, datePrecision: "day",
    placeName: "Esplanade des Invalides, Grand Palais et quais de Seine, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Ouverture de l'Exposition internationale des arts décoratifs et industriels modernes",
    beforeState: "Avant le 28 avril 1925, l'Art déco n'a pas encore son grand moment public capable d'imposer son vocabulaire au pays.",
    afterState: "Après l'ouverture de l'Exposition, Paris diffuse partout un nouveau goût français fait de lignes nettes, de luxe moderne et de pavillons manifestes.",
    gestureChanged: "Tu peux passer de pavillon en pavillon et voir le décor français changer d'époque sous tes yeux.",
    materialAnchor: "Pavillons, affiches, ferronneries et fontaines lumineuses",
    sceneText: "28 avril 1925, a Paris. Le public circule entre les Invalides, le Grand Palais et les quais, et comprend vite qu'il ne visite pas une foire de plus. Le decor, le mobilier, les affiches et l'allure meme des pavillons donnent un nom et un visage a l'Art deco francais.",
    fact: "Le 28 avril 1925 s'ouvre à Paris l'Exposition internationale des arts décoratifs et industriels modernes, événement fondateur de l'Art déco.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Exposition_internationale_des_arts_d%C3%A9coratifs_et_industriels_modernes", authority: false },
      { label: "Grand Palais", url: "https://www.grandpalais.fr/sites/default/files/2025-03/dossier_pedagogique_grandpalais_grandpalaisrmn_4_2016.pdf", authority: true }
    ],
    tags: ["art-deco", "paris", "design", "exposition"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1926-josephine-baker-paris",
    countryQid: "Q142", lang: "fr",
    momentKey: "josephine-baker-phenomene-parisien",
    momentLabel: "Joséphine Baker devient un phénomène parisien",
    label: "Joséphine Baker dans le Paris des Années folles",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "josephine_baker",
    editorialScore: 86,
    date: "1926", year: 1926, datePrecision: "year",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Joséphine Baker s'impose dans la vie culturelle parisienne",
    beforeState: "Avant 1926, le music-hall parisien n'a pas encore fait de Joséphine Baker l'une de ses images les plus fortes.",
    afterState: "En 1926, Joséphine Baker devient l'un des visages du Paris des Années folles et un symbole durable de la modernité scénique.",
    gestureChanged: "Tu peux reconnaître dans les journaux, les partitions et les scènes parisiennes une nouvelle icône noire et américaine devenue phénomène français.",
    materialAnchor: "Partition du Charleston, photographie de scène et revue illustrée",
    sceneText: "1926, dans Paris. Le nom de Joséphine Baker circule entre les theatres, les partitions et les journaux illustres. Sa silhouette, son charleston et son style deviennent un raccourci immediat pour dire les nuits parisiennes et l'audace des Annees folles.",
    fact: "En 1926, Joséphine Baker s'impose comme une vedette majeure de la scène parisienne et contribue à faire de Paris une capitale du jazz et du music-hall.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Jos%C3%A9phine_Baker", authority: false }
    ],
    tags: ["josephine-baker", "paris", "music-hall", "jazz"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1931-marius",
    countryQid: "Q142", lang: "fr",
    momentKey: "marius-marcel-pagnol",
    momentLabel: "Marius de Marcel Pagnol",
    label: "Marius impose la voix de Pagnol au cinéma",
    category: "work_release", theme: "loisirs", gestureRoot: "pagnol_marius",
    editorialScore: 88,
    date: "1931-10-09", year: 1931, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Sortie de Marius",
    beforeState: "Avant 1931, le cinéma français parlant cherche encore ses grandes oeuvres populaires capables d'assumer pleinement l'accent, la langue et le théâtre.",
    afterState: "Après Marius, la trilogie marseillaise de Pagnol installe durablement une voix française identifiable entre théâtre filmé et cinéma parlant.",
    gestureChanged: "Tu peux entendre au cinéma un parler marseillais et des dialogues de Pagnol devenir un phénomène national.",
    materialAnchor: "Affiche de film, accent marseillais et terrasse du Vieux-Port",
    sceneText: "9 octobre 1931. Avec Marius, l'accent de Marseille et les dialogues de Pagnol entrent de plain-pied dans le cinema populaire. Pour le public francais, le parlant ne copie plus seulement Hollywood: il trouve un timbre national reconnaissable entre tous.",
    fact: "Le 9 octobre 1931 sort Marius, film d'Alexander Korda adapté de Marcel Pagnol, grand jalon du cinéma parlant français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Marius_(film,_1931)", authority: false }
    ],
    tags: ["cinema", "pagnol", "marseille", "marius"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1933-zero-de-conduite",
    countryQid: "Q142", lang: "fr",
    momentKey: "zero-de-conduite-jean-vigo",
    momentLabel: "Zéro de conduite de Jean Vigo",
    label: "Zéro de conduite secoue le cinéma français",
    category: "work_release", theme: "loisirs", gestureRoot: "zero_de_conduite",
    editorialScore: 84,
    date: "1933", year: 1933, datePrecision: "year",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Sortie de Zéro de conduite",
    beforeState: "Avant 1933, peu de films français donnent à l'école, à l'insolence enfantine et à la révolte libertaire une forme aussi frontale.",
    afterState: "Après Zéro de conduite, Jean Vigo laisse un repère durable pour le cinéma d'insubordination scolaire et poétique.",
    gestureChanged: "Tu peux voir un film français qui transforme le collège en lieu de révolte et scandalise assez pour être censuré.",
    materialAnchor: "Cour de collège, oreillers en bataille et affiche Gaumont",
    sceneText: "1933, a Paris. Le film de Jean Vigo sort et derange aussitot. L'ecole, l'autorite et l'enfance rebelle prennent soudain au cinema une allure neuve, assez vive pour choquer et assez libre pour devenir culte.",
    fact: "En 1933, Zéro de conduite de Jean Vigo sort en France et devient, malgré la censure, une référence majeure du cinéma français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Z%C3%A9ro_de_conduite_%28film%29", authority: false },
      { label: "Wikipedia EN", url: "https://en.wikipedia.org/wiki/Zero_for_Conduct", authority: false }
    ],
    tags: ["cinema", "jean-vigo", "ecole", "censure"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1938-quai-des-brumes",
    countryQid: "Q142", lang: "fr",
    momentKey: "quai-des-brumes-marcel-carne",
    momentLabel: "Le Quai des brumes de Marcel Carné",
    label: "Le Quai des brumes devient l'image du réalisme poétique",
    category: "work_release", theme: "loisirs", gestureRoot: "quai_des_brumes",
    editorialScore: 88,
    date: "1938-05-18", year: 1938, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie du Quai des brumes",
    beforeState: "Avant 1938, le réalisme poétique français existe déjà, mais n'a pas encore trouvé son image mélancolique la plus célèbre.",
    afterState: "Après Le Quai des brumes, Jean Gabin, Prévert et Carné fixent une esthétique durable du cinéma français d'avant-guerre.",
    gestureChanged: "Tu peux citer un film français où brouillard, fatalité et répliques deviennent immédiatement des signes de reconnaissance populaire.",
    materialAnchor: "Affiche de film, port embrumé et silhouette de Gabin",
    sceneText: "18 mai 1938. Le Quai des brumes donne au cinema francais une image qui restera: le port, le brouillard, Gabin, la fatalite. Le realisme poetique cesse d'etre une formule critique et devient une memoire commune du grand ecran.",
    fact: "Le Quai des brumes, sorti en 1938, impose Marcel Carné et Jacques Prévert comme figures majeures du réalisme poétique français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Le_Quai_des_brumes_%28film%29", authority: false },
      { label: "Wikipedia ES", url: "https://es.wikipedia.org/wiki/El_muelle_de_las_brumas", authority: false }
    ],
    tags: ["cinema", "carne", "prevert", "gabin"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1939-regle-du-jeu",
    countryQid: "Q142", lang: "fr",
    momentKey: "la-regle-du-jeu-jean-renoir",
    momentLabel: "La Règle du jeu de Jean Renoir",
    label: "La Règle du jeu choque la France de 1939",
    category: "work_release", theme: "loisirs", gestureRoot: "regle_du_jeu",
    editorialScore: 90,
    date: "1939-07-07", year: 1939, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Première de La Règle du jeu",
    beforeState: "Avant juillet 1939, Jean Renoir n'a pas encore livré cette radiographie féroce d'une société française à la veille du désastre.",
    afterState: "Après sa première controversée, La Règle du jeu entre dans l'histoire comme l'un des grands films français sur l'aveuglement d'une époque.",
    gestureChanged: "Tu peux voir un film français qui retourne contre son propre monde mondain un miroir si dur qu'une partie du public le rejette d'abord.",
    materialAnchor: "Château, partie de chasse et affiche de première",
    sceneText: "7 juillet 1939, a Paris. La premiere de La Regle du jeu tombe dans une France deja tendue. Renoir montre une societe elegante, mobile, brillante, mais incapable de voir le desastre qui approche; le film choque avant de devenir canonique.",
    fact: "Le 7 juillet 1939 a lieu la première de La Règle du jeu, chef-d'oeuvre de Jean Renoir d'abord très mal reçu avant d'être considéré comme l'un des plus grands films français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/La_R%C3%A8gle_du_jeu", authority: false }
    ],
    tags: ["cinema", "renoir", "1939", "classique"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1927-jazz-singer-cinema-parlant",
    countryQid: "Q142", lang: "fr",
    momentKey: "premier-film-parlant-grand-public",
    momentLabel: "Le Chanteur de jazz — premier film parlant",
    label: "premier film parlant grand public",
    category: "public_premiere", theme: "loisirs", gestureRoot: "cinema_parlant",
    editorialScore: 90,
    date: "1927-10-06", year: 1927, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie du Chanteur de jazz",
    beforeState: "Avant le 6 octobre 1927, les films sont muets — les acteurs jouent, un pianiste accompagne en salle.",
    afterState: "Après le 6 octobre 1927, le cinéma parlant bouleverse l'industrie et l'expérience du spectateur.",
    gestureChanged: "Tu peux entendre la voix des acteurs dans une salle de cinéma pour la première fois.",
    materialAnchor: "Fauteuil de cinéma, bobine sonore et écran argenté",
    sceneText: "6 octobre 1927, dans les salles et revues de cinema francaises. La nouvelle venue d'Amerique circule vite: pour la premiere fois, un acteur parle vraiment a l'ecran. En France aussi, le cinema muet commence soudain a paraitre ancien.",
    fact: "Le 6 octobre 1927, la sortie du Chanteur de jazz marque l'avènement du cinéma parlant.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Le_Chanteur_de_jazz", authority: false }
    ],
    tags: ["cinema", "parlant", "jazz", "hollywood"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1928-mickey-mouse",
    countryQid: "Q142", lang: "fr",
    momentKey: "mickey-mouse-premier-dessin-anime-sonore",
    momentLabel: "Mickey Mouse — premier dessin animé sonore",
    label: "naissance de Mickey Mouse",
    category: "public_premiere", theme: "loisirs", gestureRoot: "mickey_mouse",
    editorialScore: 92,
    date: "1928-11-18", year: 1928, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie de Steamboat Willie",
    beforeState: "Avant novembre 1928, les dessins animés sont muets et les personnages anonymes.",
    afterState: "Après novembre 1928, Mickey Mouse devient le premier personnage de dessin animé sonore et le symbole mondial de l'entertainment.",
    gestureChanged: "Tu peux reconnaître Mickey Mouse, personnage qui accompagnera l'enfance de générations entières.",
    materialAnchor: "Écran de cinéma, sifflet de bateau et oreilles rondes",
    sceneText: "18 novembre 1928, dans les salles francaises. Un petit personnage noir aux oreilles rondes siffle a l'ecran et reste aussitot en tete. Mickey cesse d'etre un dessin parmi d'autres: il devient un repere durable de la culture populaire.",
    fact: "Le 18 novembre 1928, Steamboat Willie sort en salle : c'est la naissance officielle de Mickey Mouse, premier dessin animé synchronisé avec le son.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Mickey_Mouse", authority: false }
    ],
    tags: ["mickey", "disney", "animation", "cinema"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1936-jesse-owens-berlin",
    countryQid: "Q142", lang: "fr",
    momentKey: "jesse-owens-4-medailles-or-berlin",
    momentLabel: "Jesse Owens — 4 médailles d'or aux JO de Berlin",
    label: "Jesse Owens aux Jeux olympiques de Berlin",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "jesse_owens_berlin",
    editorialScore: 92,
    date: "1936-08-03", year: 1936, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Victoires de Jesse Owens aux JO de Berlin",
    beforeState: "Avant les JO de Berlin, les nazis proclament la supériorité aryenne dans leur propre pays.",
    afterState: "Après les victoires de Jesse Owens, un athlète noir américain a remporté 4 médailles d'or devant Hitler.",
    gestureChanged: "Tu peux te souvenir du moment où le sport a contredit la propagande nazie sur la scène mondiale.",
    materialAnchor: "Stade olympique, podium et drapeaux américains",
    sceneText: "Aout 1936, dans les cafes et journaux francais. Les resultats olympiques passent de table en table: Jesse Owens gagne encore. En France aussi, le sport devient la preuve visible qu'une propagande peut etre contredite devant tout le monde.",
    fact: "En août 1936, Jesse Owens remporte 4 médailles d'or aux Jeux olympiques de Berlin, défiant symboliquement l'idéologie nazie.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Jesse_Owens", authority: false }
    ],
    tags: ["olympique", "jesse-owens", "berlin", "sport"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1937-blanche-neige-disney",
    countryQid: "Q142", lang: "fr",
    momentKey: "blanche-neige-premier-long-metrage-anime",
    momentLabel: "Blanche-Neige — premier long métrage d'animation",
    label: "Blanche-Neige de Disney, premier long métrage animé",
    category: "public_premiere", theme: "loisirs", gestureRoot: "blanche_neige_disney",
    editorialScore: 90,
    date: "1937-12-21", year: 1937, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie de Blanche-Neige et les Sept Nains",
    beforeState: "Avant décembre 1937, l'animation se limite aux courts métrages.",
    afterState: "Après décembre 1937, le long métrage d'animation existe comme genre cinématographique à part entière.",
    gestureChanged: "Tu peux passer 1h20 assis dans une salle à regarder des personnages dessinés vivre une histoire complète.",
    materialAnchor: "Écran de cinéma, pomme rouge et robes colorées",
    sceneText: "21 decembre 1937, dans les journaux de cinema francais. On raconte qu'un dessin anime tient toute une soiree et fait pleurer une salle entiere. Pour le public francais, l'animation cesse d'etre un simple court metrage et change tout de suite d'echelle.",
    fact: "Le 21 décembre 1937, Blanche-Neige et les Sept Nains sort en salle, premier long métrage d'animation de l'histoire.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Blanche-Neige_et_les_Sept_Nains_(film,_1937)", authority: false }
    ],
    tags: ["disney", "animation", "blanche-neige", "cinema"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1940-le-dictateur-chaplin",
    countryQid: "Q142", lang: "fr",
    momentKey: "le-dictateur-chaplin-satire-hitler",
    momentLabel: "Le Dictateur — Chaplin se moque de Hitler",
    label: "Le Dictateur de Charlie Chaplin",
    category: "work_release", theme: "loisirs", gestureRoot: "chaplin_dictateur",
    editorialScore: 92,
    date: "1940-10-15", year: 1940, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie du Dictateur de Charlie Chaplin",
    beforeState: "Avant 1940, aucun film n'ose parodier frontalement Hitler et le régime nazi.",
    afterState: "Après 1940, Le Dictateur devient le symbole de la résistance culturelle à la tyrannie.",
    gestureChanged: "Tu peux voir un film qui rit de Hitler pendant que la guerre fait rage en Europe.",
    materialAnchor: "Brosse à dents sous le nez, globe terrestre gonflable et uniforme militaire parodique",
    sceneText: "15 octobre 1940, en France. Le titre circule d'abord comme une audace venue d'Amerique: Chaplin ose ridiculiser Hitler alors que l'Europe ploie deja sous la guerre. Le rire devient une forme de resistance culturelle avant meme la Liberation.",
    fact: "Le 15 octobre 1940, Le Dictateur de Charlie Chaplin sort en salle, première satire directe de Hitler dans l'histoire du cinéma.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Le_Dictateur", authority: false }
    ],
    tags: ["chaplin", "dictateur", "cinema", "resistance"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1944-liberation-paris",
    countryQid: "Q142", lang: "fr",
    momentKey: "liberation-de-paris",
    momentLabel: "Libération de Paris",
    label: "Libération de Paris",
    category: "symbolic_moment", theme: "administration", gestureRoot: "liberation_paris",
    editorialScore: 98,
    date: "1944-08-25", year: 1944, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Libération de Paris",
    beforeState: "Avant le 25 août 1944, Paris est occupée par l'armée allemande depuis juin 1940.",
    afterState: "Après le 25 août 1944, Paris est libre et de Gaulle descend les Champs-Élysées.",
    gestureChanged: "Tu peux sortir dans la rue à Paris sans craindre les soldats allemands pour la première fois en quatre ans.",
    materialAnchor: "Drapeau tricolore, balcon parisien et foule sur les Champs-Élysées",
    sceneText: "25 août 1944, Paris. Les cloches sonnent, les gens pleurent dans la rue. De Gaulle descend les Champs-Élysées dans un flot humain. Quatre ans d'occupation s'effacent en une journée.",
    fact: "Le 25 août 1944, Paris est libérée de l'occupation allemande. Charles de Gaulle descend les Champs-Élysées sous des millions de regards.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Lib%C3%A9ration_de_Paris", authority: false }
    ],
    tags: ["liberation", "paris", "guerre", "de-gaulle"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1947-christian-dior-new-look",
    countryQid: "Q142", lang: "fr",
    momentKey: "dior-new-look",
    momentLabel: "Christian Dior invente le New Look",
    label: "le New Look de Christian Dior",
    category: "foundational_event", theme: "loisirs", gestureRoot: "dior_new_look",
    editorialScore: 88,
    date: "1947-02-12", year: 1947, datePrecision: "day",
    placeName: "Maison Dior, avenue Montaigne, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Défilé Corolle de Christian Dior",
    beforeState: "Avant février 1947, la mode féminine reste marquée par les restrictions de guerre, avec des jupes courtes et des formes austères.",
    afterState: "Après février 1947, le New Look impose des tailles cintrées, des jupes longues et une féminité luxuriante.",
    gestureChanged: "Tu peux t'habiller avec des robes longues et cintrées qui réaffirment la mode parisienne après la guerre.",
    materialAnchor: "Jupe longue, taille cintrée et guêpière Dior",
    sceneText: "12 février 1947, avenue Montaigne. Les mannequins défilent dans des robes longues et cintrées. La presse crie au scandale et au génie. Paris reprend son titre de capitale mondiale de la mode.",
    fact: "Le 12 février 1947, Christian Dior présente sa première collection et invente le New Look, révolutionnant la mode mondiale.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/New_Look_(mode)", authority: false },
      { label: "Dior", url: "https://www.dior.com/fr_fr/mode/mode-femme/le-heritage-de-dior", authority: true }
    ],
    tags: ["dior", "mode", "new-look", "paris"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
];
