import type { CulturalMomentEntry } from "../../../types";

export const FR_CULTURAL_BACKFILL_1970_1989: CulturalMomentEntry[] = [
  {
    id: "fr-1970-coluche-cafe-de-la-gare",
    countryQid: "Q142", lang: "fr",
    momentKey: "voir-coluche-au-cafe-de-la-gare",
    momentLabel: "Voir Coluche au Café de la Gare à Paris",
    label: "Coluche et le Café de la Gare (1970)",
    category: "foundational_event", theme: "loisirs", gestureRoot: "coluche_cafe_gare",
    editorialScore: 84,
    date: "1970-01-01", year: 1970, datePrecision: "year",
    placeName: "Café de la Gare, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Coluche et ses complices créent le Café de la Gare",
    beforeState: "Avant 1970, la scène comique alternative à Paris n'a pas de lieu de référence pour les jeunes humoristes.",
    afterState: "Après la création du Café de la Gare, un nouveau courant de comédie populaire et politique se développe en France.",
    gestureChanged: "Tu peux aller dans une petite salle voir un spectacle de jeunes humoristes qui parlent de la vie ordinaire avec irrévérence.",
    materialAnchor: "Salle de spectacle, chaise en bois et affiche de spectacle",
    sceneText: "1970, Café de la Gare, Paris. Coluche, Romain Bouteille et leurs complices montent sur scène sans filet. Leur comédie parle de la vie réelle, sans ménager les puissants. Le public rit — et reconnaît quelque chose de vrai.",
    fact: "En 1970, Coluche, Romain Bouteille et leurs amis fondent le Café de la Gare, troupe de théâtre alternative qui renouvelle le comique français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Caf%C3%A9_de_la_Gare", authority: false }
    ],
    tags: ["coluche", "theatre", "comedie", "paris"],
    quality: { strictPlace: true, strictDate: false, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1971-marguerite-yourcenar",
    countryQid: "Q142", lang: "fr",
    momentKey: "lire-un-roman-de-marguerite-yourcenar",
    momentLabel: "Lire Marguerite Yourcenar — Mémoires d'Hadrien en poche",
    label: "Mémoires d'Hadrien de Yourcenar en poche (1971)",
    category: "work_release", theme: "loisirs", gestureRoot: "yourcenar_hadrien",
    editorialScore: 82,
    date: "1971-01-01", year: 1971, datePrecision: "year",
    placeName: "Librairies françaises", placeType: "country", placeQid: "Q142",
    triggerLabel: "Diffusion massive de Mémoires d'Hadrien en édition de poche",
    beforeState: "Avant les années 1970, Mémoires d'Hadrien reste un roman estimé mais peu diffusé en France.",
    afterState: "Dans les années 1970, son édition de poche permet à des milliers de lecteurs de découvrir ce roman historique exceptionnel.",
    gestureChanged: "Tu peux acheter pour quelques francs un roman qui ressuscite l'Antiquité romaine avec une précision et une élégance rares.",
    materialAnchor: "Poche Folio, roman ouvert et marque-page glissé",
    sceneText: "1971, librairie. La poche de Mémoires d'Hadrien est dans le bac. À quelques francs, on entre dans la tête d'un empereur romain — écrit par une femme qui deviendra la première académicienne. Un livre qui traverse les siècles.",
    fact: "Dans les années 1970, Mémoires d'Hadrien de Marguerite Yourcenar est diffusé en poche et entre dans le patrimoine littéraire français lu massivement.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/M%C3%A9moires_d%27Hadrien", authority: false }
    ],
    tags: ["litterature", "yourcenar", "roman", "livre"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1972-les-valseuses-blier",
    countryQid: "Q142", lang: "fr",
    momentKey: "aller-voir-les-valseuses-de-blier-au-cinema",
    momentLabel: "Aller voir Les Valseuses de Bertrand Blier au cinéma",
    label: "Les Valseuses de Bertrand Blier (1974)",
    category: "work_release", theme: "loisirs", gestureRoot: "valseuses_blier",
    editorialScore: 84,
    date: "1974-03-20", year: 1972, datePrecision: "year",
    placeName: "Cinémas français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie des Valseuses de Bertrand Blier",
    beforeState: "Avant 1974, les films français qui brisent ouvertement les tabous sexuels et sociaux restent marginaux.",
    afterState: "Les Valseuses impose un registre de comédie provocatrice et libertaire qui marque le cinéma français des années 1970.",
    gestureChanged: "Tu peux voir au cinéma un film qui rompt avec toutes les conventions morales et sociales, et en rire.",
    materialAnchor: "Affiche du film, billets de cinéma et critique de presse",
    sceneText: "1974, cinéma. Depardieu et Dewaere éclatent l'écran dans Les Valseuses. Le film provoque, choque et fait rire — en même temps. Une nouvelle génération de cinéma français, libre et insolente, prend d'assaut les salles.",
    fact: "Les Valseuses de Bertrand Blier (1974), avec Depardieu et Dewaere, s'impose comme un film culte libertaire du cinéma français des années 1970.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Les_Valseuses_(film)", authority: false }
    ],
    tags: ["cinema", "blier", "depardieu", "annees70"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1975-le-vieux-fusil",
    countryQid: "Q142", lang: "fr",
    momentKey: "voir-le-vieux-fusil-de-enrico-au-cinema",
    momentLabel: "Voir Le Vieux Fusil de Robert Enrico (César du meilleur film)",
    label: "Le Vieux Fusil de Robert Enrico (1975)",
    category: "work_release", theme: "loisirs", gestureRoot: "vieux_fusil_enrico",
    editorialScore: 82,
    date: "1975-11-05", year: 1975, datePrecision: "day",
    placeName: "Cinémas français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie du Vieux Fusil et premiers César du cinéma",
    beforeState: "Avant 1975, il n'existe pas de cérémonie française équivalente aux Oscars pour récompenser le cinéma national.",
    afterState: "Avec la création des César en 1976, le cinéma français dispose de son propre palmarès annuel de prestige.",
    gestureChanged: "Tu peux regarder la remise des César à la télévision et voir les acteurs et réalisateurs français célébrés sur scène.",
    materialAnchor: "Statuette César, tapis rouge et affiche du Vieux Fusil",
    sceneText: "1975-1976. Le Vieux Fusil, film de la mémoire et de la vengeance, remporte le premier César du meilleur film. Une nouvelle institution est née : chaque année, le cinéma français a désormais son palmarès officiel.",
    fact: "Le Vieux Fusil de Robert Enrico est couronné meilleur film lors de la première cérémonie des César, en 1976.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Le_Vieux_Fusil", authority: false },
      { label: "César", url: "https://www.academie-cinema.org/", authority: true }
    ],
    tags: ["cinema", "cesar", "vieux-fusil", "enrico"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1976-dalida-disco-itsy-bitsy",
    countryQid: "Q142", lang: "fr",
    momentKey: "danser-sur-dalida-et-la-disco-en-france",
    momentLabel: "Danser sur Dalida et la musique disco dans les clubs français",
    label: "La disco en France — Dalida et les clubs des années 1970",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "disco_france",
    editorialScore: 82,
    date: "1975-01-01", year: 1976, datePrecision: "year",
    placeName: "Discothèques françaises", placeType: "country", placeQid: "Q142",
    triggerLabel: "Explosion de la culture disco en France au milieu des années 1970",
    beforeState: "Avant le milieu des années 1970, la musique de danse française reste dominée par le yé-yé et la variété.",
    afterState: "À partir de 1975-1976, les discothèques explosent en France et la disco américaine se mêle à la variété nationale.",
    gestureChanged: "Tu peux aller dans une discothèque le samedi soir, danser sur des tubes et rentrer à l'aube — une nouvelle géographie nocturne.",
    materialAnchor: "Boule à facettes, sol lumineux et 45 tours de Dalida",
    sceneText: "1976, discothèque française. La boule à facettes tourne. Dalida et Village People alternent. Les corps bougent sous les lumières stroboscopiques. La France a sa culture nocturne — et elle ne danse plus la valse.",
    fact: "Au milieu des années 1970, la culture disco s'implante en France avec l'ouverture de nombreuses discothèques et des succès de Dalida ou de la musique américaine.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Disco", authority: false }
    ],
    tags: ["disco", "musique", "dalida", "nuit"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1980-marguerite-yourcenar-academie",
    countryQid: "Q142", lang: "fr",
    momentKey: "apprendre-que-marguerite-yourcenar-entre-a-lacademie-francaise",
    momentLabel: "Apprendre que Marguerite Yourcenar entre à l'Académie française",
    label: "Marguerite Yourcenar — première femme à l'Académie française (1980)",
    category: "foundational_event", theme: "administration", gestureRoot: "yourcenar_academie",
    editorialScore: 88,
    date: "1980-03-06", year: 1980, datePrecision: "day",
    placeName: "Académie française, Paris", placeType: "institution", placeQid: null,
    triggerLabel: "Élection de Marguerite Yourcenar à l'Académie française",
    beforeState: "Avant le 6 mars 1980, l'Académie française n'a jamais accueilli de femme depuis sa fondation en 1635.",
    afterState: "Après l'élection de Yourcenar, la vieille institution française ouvre pour la première fois ses portes à une femme.",
    gestureChanged: "Tu peux lire dans ton journal qu'une femme vient d'être élue à l'Académie française — une rupture de 345 ans.",
    materialAnchor: "Habit vert d'académicien, épée et journal titrant l'événement",
    sceneText: "6 mars 1980. Marguerite Yourcenar est élue à l'Académie française. Elle sera reçue sous la Coupole en 1981. Pour la première fois en 345 ans, une femme rejoindra les Immortels — l'institution la plus conservatrice de la République des lettres.",
    fact: "Le 6 mars 1980, Marguerite Yourcenar est élue à l'Académie française, devenant la première femme à rejoindre l'institution fondée en 1635.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Marguerite_Yourcenar", authority: false },
      { label: "Académie française", url: "https://www.academie-francaise.fr/les-immortels/marguerite-yourcenar", authority: true }
    ],
    tags: ["yourcenar", "academie", "femmes", "litterature"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1971-tintin-lune-bande-dessinee",
    countryQid: "Q142", lang: "fr",
    momentKey: "tintin-on-a-marche-sur-la-lune",
    momentLabel: "Tintin marche sur la Lune avant les hommes",
    label: "On a marché sur la Lune de Hergé",
    category: "work_release", theme: "loisirs", gestureRoot: "tintin_lune",
    editorialScore: 82,
    date: "1954-10-30", year: 1954, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie de On a marché sur la Lune en album",
    beforeState: "Avant 1954, personne n'a jamais représenté un alunissage dans une fiction grand public.",
    afterState: "Après 1954, Tintin a marché sur la Lune 15 ans avant Neil Armstrong — dans les cases de la BD.",
    gestureChanged: "Tu peux lire un récit d'exploration lunaire réaliste avant que l'humanité y arrive vraiment.",
    materialAnchor: "Album Tintin, scaphandre blanc et sol lunaire dessiné",
    sceneText: "1954, dans les librairies francaises. L'album a couverture rouge passe de main en main: Tintin marche deja sur la Lune. Bien avant Apollo 11, l'imaginaire scientifique entre dans les chambres d'enfants par la bande dessinee.",
    fact: "En 1954, Hergé publie On a marché sur la Lune, représentation prophétique de l'alunissage 15 ans avant qu'il ne se produise.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/On_a_march%C3%A9_sur_la_Lune", authority: false }
    ],
    tags: ["tintin", "herge", "lune", "bd"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1968-mai-68",
    countryQid: "Q142", lang: "fr",
    momentKey: "mai-68-revolution-culturelle",
    momentLabel: "Mai 68 — la révolution culturelle française",
    label: "Mai 68",
    category: "symbolic_moment", theme: "administration", gestureRoot: "mai_68",
    editorialScore: 94,
    date: "1968-05-03", year: 1968, datePrecision: "day",
    placeName: "Paris — Sorbonne", placeType: "site", placeQid: "Q22345",
    triggerLabel: "Début de Mai 68 à la Sorbonne",
    beforeState: "Avant mai 1968, la France vit sous le gaullisme conservateur et la jeunesse n'a pas de voix politique.",
    afterState: "Après mai 1968, la société française change profondément : mœurs, droits sociaux, rapports à l'autorité.",
    gestureChanged: "Tu peux te souvenir du mois où des millions de Français ont arrêté de travailler et où tout semblait possible.",
    materialAnchor: "Pavés, drapeaux rouges et affiches de l'atelier populaire",
    sceneText: "3 mai 1968, Sorbonne. Les CRS chargent les étudiants. La nuit des barricades va suivre. Dix millions de grévistes vont paralyser la France. Le gaullisme ne sera plus jamais le même.",
    fact: "Le 3 mai 1968, les événements de Mai 68 commencent à la Sorbonne, déclenchant une crise sociale et culturelle sans précédent en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Mai_68", authority: false }
    ],
    tags: ["mai68", "revolution", "paris", "culture"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1973-dernier-tango-paris",
    countryQid: "Q142", lang: "fr",
    momentKey: "voir-le-dernier-tango-a-paris-de-bertolucci",
    momentLabel: "Voir Le Dernier Tango à Paris de Bertolucci",
    label: "Le Dernier Tango à Paris (1973)",
    category: "work_release", theme: "loisirs", gestureRoot: "dernier_tango_paris",
    editorialScore: 84,
    date: "1973-01-26", year: 1973, datePrecision: "day",
    placeName: "Cinémas parisiens", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie en France du Dernier Tango à Paris de Bernardo Bertolucci",
    beforeState: "Avant 1973, le cinéma d'auteur ne peut pas montrer aussi explicitement la sexualité et la violence émotionnelle.",
    afterState: "Après la sortie controversée du film, la frontière entre cinéma d'art et pornographie est débattue dans la presse française.",
    gestureChanged: "Tu peux aller voir au cinéma d'art et essai un film qui choque, dérange et est censuré dans plusieurs pays.",
    materialAnchor: "Affiche interdite aux moins de 18 ans, pellicule et salle d'art et essai",
    sceneText: "26 janvier 1973, Paris. Le Dernier Tango à Paris déferle sur les écrans. Marlon Brando et Maria Schneider. Le film provoque, scandalise, fascine. Censuré partout, encensé par la critique — Paris en fait un événement mondial.",
    fact: "Le 26 janvier 1973, Le Dernier Tango à Paris de Bertolucci sort en France, déclenchant une polémique internationale sur les limites du cinéma d'auteur.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Le_Dernier_Tango_%C3%A0_Paris", authority: false }
    ],
    tags: ["cinema", "bertolucci", "paris", "controverse"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1974-giscard-election",
    countryQid: "Q142", lang: "fr",
    momentKey: "regarder-le-debat-giscard-mitterrand-a-la-television",
    momentLabel: "Regarder le débat télévisé Giscard-Mitterrand (1974)",
    label: "Le débat télévisé Giscard-Mitterrand (1974)",
    category: "foundational_event", theme: "administration", gestureRoot: "debat_tv_presidentiel",
    editorialScore: 86,
    date: "1974-05-10", year: 1974, datePrecision: "day",
    placeName: "Salons télévisés, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Premier débat télévisé de l'entre-deux-tours présidentiel",
    beforeState: "Avant 1974, les candidats à la présidentielle ne se confrontent pas en débat télévisé.",
    afterState: "Après 1974, le débat de l'entre-deux-tours devient un moment politique et télévisuel incontournable.",
    gestureChanged: "Tu peux regarder deux candidats à l'Élysée s'affronter en direct devant tes yeux — et former ton propre jugement.",
    materialAnchor: "Téléviseur en couleur, table de débat et logo de l'émission",
    sceneText: "10 mai 1974. La France regarde Giscard et Mitterrand face à face. La phrase de Mitterrand — «Vous n'avez pas le monopole du cœur» — entre dans l'histoire. Le débat présidentiel télévisé naît ici.",
    fact: "Le 10 mai 1974, Valéry Giscard d'Estaing et François Mitterrand s'affrontent dans le premier débat télévisé de l'entre-deux-tours présidentiel.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/D%C3%A9bat_de_l%27entre-deux-tours_de_l%27%C3%A9lection_pr%C3%A9sidentielle_fran%C3%A7aise_de_1974", authority: false }
    ],
    tags: ["debat-tv", "election", "giscard", "mitterrand"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1978-france-football-coupe-monde",
    countryQid: "Q142", lang: "fr",
    momentKey: "regarder-l-equipe-de-france-a-la-coupe-du-monde-78",
    momentLabel: "Regarder l'équipe de France à la Coupe du monde 1978",
    label: "La France à la Coupe du monde 1978",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "coupe_monde_1978",
    editorialScore: 80,
    date: "1978-06-01", year: 1978, datePrecision: "month",
    placeName: "Salons français devant la télévision", placeType: "country", placeQid: "Q142",
    triggerLabel: "Participation de l'équipe de France à la Coupe du monde en Argentine",
    beforeState: "Avant 1978, l'équipe de France de football n'a pas réussi à se qualifier régulièrement pour les grandes compétitions.",
    afterState: "En 1978, la France participe à la Coupe du monde en Argentine — Platini et une nouvelle génération de joueurs se révèlent.",
    gestureChanged: "Tu peux regarder à la télévision l'équipe de France en Coupe du monde et voir une génération de joueurs prendre forme.",
    materialAnchor: "Téléviseur, maillot bleu de l'équipe de France et journal sportif",
    sceneText: "1978, salon. La Coupe du monde d'Argentine passe à la télévision. La France de Platini est là. On ne gagne pas encore — mais quelque chose se construit. Le football français est en train de changer de visage.",
    fact: "En 1978, la France participe à la Coupe du monde en Argentine ; Michel Platini commence à se révéler, annonçant une grande génération.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Coupe_du_monde_de_football_1978", authority: false }
    ],
    tags: ["football", "france", "coupe-du-monde", "platini"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1981-mitterrand-culture-lang",
    countryQid: "Q142", lang: "fr",
    momentKey: "beneficier-du-budget-culture-jack-lang",
    momentLabel: "Bénéficier du budget culturel de Jack Lang (1 % du budget)",
    label: "La politique culturelle de Jack Lang (1982)",
    category: "foundational_event", theme: "loisirs", gestureRoot: "lang_culture",
    editorialScore: 86,
    date: "1982-01-01", year: 1981, datePrecision: "year",
    placeName: "Ministère de la Culture, France", placeType: "institution", placeQid: null,
    triggerLabel: "Jack Lang double le budget de la Culture et le porte à 1 % du budget de l'État",
    beforeState: "Avant 1981, le budget de la Culture représente 0,5 % du budget de l'État.",
    afterState: "Sous Jack Lang, le budget double : musées, spectacles vivants, bibliothèques reçoivent des moyens inédits.",
    gestureChanged: "Tu peux profiter de plus de spectacles, d'expositions, et de festivals subventionnés partout en France.",
    materialAnchor: "Billet de festival, programmation culturelle et logo Ministère Culture",
    sceneText: "1982, ministère de la Culture. Jack Lang annonce le doublement du budget. Partout en France, des festivals se créent, des musées rénovent, des compagnies de théâtre survivent grâce aux subventions. La culture est une politique d'État.",
    fact: "En 1982, Jack Lang obtient que le budget de la Culture soit porté à 1 % du budget de l'État — doublement inédit qui transforme la politique culturelle française.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Jack_Lang", authority: false },
      { label: "Ministère de la Culture", url: "https://www.culture.gouv.fr/", authority: true }
    ],
    tags: ["culture", "lang", "politique", "budget"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1983-bernard-pivot-apostrophes",
    countryQid: "Q142", lang: "fr",
    momentKey: "regarder-apostrophes-de-bernard-pivot-a-la-television",
    momentLabel: "Regarder Apostrophes de Bernard Pivot à la télévision",
    label: "Apostrophes de Bernard Pivot (années 1970-80)",
    category: "symbolic_moment", theme: "loisirs", gestureRoot: "apostrophes_pivot",
    editorialScore: 84,
    date: "1983-01-01", year: 1983, datePrecision: "year",
    placeName: "Salons télévisés, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Apostrophes de Bernard Pivot — émission littéraire télévisée de référence",
    beforeState: "Avant Apostrophes (1975), la littérature n'a pas de place régulière en prime time à la télévision française.",
    afterState: "Avec Apostrophes, un livre discuté à la télévision peut se vendre à 100 000 exemplaires le lendemain.",
    gestureChanged: "Tu peux regarder des écrivains débattre en direct le vendredi soir et décider d'acheter leur livre le lendemain.",
    materialAnchor: "Livre ouvert, plateau d'Apostrophes et regard de Pivot",
    sceneText: "1983, salon français. Apostrophes passe sur Antenne 2. Bernard Pivot tient son livre, questionne l'auteur. Le lendemain, les librairies font la queue. La télévision est devenue le plus grand prescripteur de lecture de France.",
    fact: "Apostrophes de Bernard Pivot (1975-1990) est la première émission littéraire de prime time à la télévision française — une séquence qu'on ne recrée plus.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Apostrophes_(t%C3%A9l%C3%A9vision)", authority: false }
    ],
    tags: ["litterature", "pivot", "television", "livres"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1988-rap-francais-emergence",
    countryQid: "Q142", lang: "fr",
    momentKey: "entendre-du-rap-francais-a-la-radio",
    momentLabel: "Entendre du rap français pour la première fois à la radio",
    label: "Le rap français — NTM, IAM, MC Solaar (fin des années 1980)",
    category: "foundational_event", theme: "loisirs", gestureRoot: "rap_francais",
    editorialScore: 86,
    date: "1988-01-01", year: 1988, datePrecision: "year",
    placeName: "Radios libres et banlieues françaises", placeType: "country", placeQid: "Q142",
    triggerLabel: "Émergence du rap français sur les radios libres",
    beforeState: "Avant 1988, le hip-hop est présent dans les banlieues françaises mais n'atteint pas encore les radios commerciales.",
    afterState: "À la fin des années 1980, les premiers rappeurs français (MC Solaar, NTM, IAM) s'imposent sur les radios libres.",
    gestureChanged: "Tu peux allumer Skyrock ou NRJ et entendre un rappeur qui parle de la France, de sa banlieue et de ta langue.",
    materialAnchor: "Ghetto blaster, cassette de rap et logo Skyrock",
    sceneText: "1988, radio. La voix parle vite, en français, avec des rimes sur une boucle de basse. C'est NTM ou MC Solaar — les mots viennent des banlieues de Paris et de Marseille. Le rap français est né, et il parle de la vraie France.",
    fact: "À la fin des années 1980, le rap français émerge sur les radios libres avec des artistes comme MC Solaar, IAM et NTM, posant les bases d'un genre qui dominera les charts deux décennies plus tard.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Hip-hop_fran%C3%A7ais", authority: false }
    ],
    tags: ["rap", "hip-hop", "banlieue", "musique"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1977-star-wars-france",
    countryQid: "Q142", lang: "fr",
    momentKey: "star-wars-sortie-france",
    momentLabel: "La Guerre des étoiles sort en France",
    label: "La Guerre des étoiles de George Lucas en France",
    category: "work_release", theme: "loisirs", gestureRoot: "star_wars_france",
    editorialScore: 90,
    date: "1977-10-19", year: 1977, datePrecision: "day",
    placeName: "Cinémas français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie de La Guerre des étoiles en France",
    beforeState: "Avant 1977, le cinéma de science-fiction ne mobilise pas les foules en France.",
    afterState: "Après 1977, La Guerre des étoiles révolutionne le cinéma de divertissement et crée la notion de blockbuster en France.",
    gestureChanged: "Tu peux faire la queue pendant des heures devant un cinéma pour un film comme tu ferais pour un concert.",
    materialAnchor: "Sabre laser, affiche étoilée et queue devant le cinéma",
    sceneText: "19 octobre 1977, cinémas français. Les files d'attente débordent sur le trottoir. Sur l'écran, des vaisseaux spatiaux traversent les étoiles avec un son jamais entendu. Le cinéma-spectacle vient de changer d'échelle.",
    fact: "Le 19 octobre 1977, La Guerre des étoiles sort en France, révolutionnant le cinéma de divertissement et les effets spéciaux.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/La_Guerre_des_%C3%A9toiles", authority: false }
    ],
    tags: ["star-wars", "cinema", "lucas", "blockbuster"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-1980-walkman-sony",
    countryQid: "Q142", lang: "fr",
    momentKey: "walkman-musique-portable",
    momentLabel: "Le Walkman Sony — la musique devient portable",
    label: "le Walkman Sony en France",
    category: "public_premiere", theme: "loisirs", gestureRoot: "walkman_sony",
    editorialScore: 88,
    date: "1979-07-01", year: 1979, datePrecision: "month",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Lancement du Walkman Sony",
    beforeState: "Avant 1979, écouter de la musique enregistrée nécessite d'être chez soi ou près d'une chaîne hi-fi.",
    afterState: "Après 1979, le Walkman permet d'écouter sa musique n'importe où, n'importe quand.",
    gestureChanged: "Tu peux marcher dans la rue avec des écouteurs et entendre ta propre bande-son pendant que le monde défile.",
    materialAnchor: "Walkman argenté, cassette et écouteurs orange",
    sceneText: "1979, dans le metro et les rues francaises. La cassette claque dans le boitier argente, les ecouteurs isolent du bruit urbain et la marche change aussitot de rythme. Pour la premiere fois, chacun traverse la ville avec sa propre bande-son.",
    fact: "En juillet 1979, Sony lance le Walkman, rendant la musique portable et changeant l'écoute musicale quotidienne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Walkman", authority: false },
      { label: "Sony", url: "https://www.sony.com/en/SonyInfo/CorporateInfo/History/SonyHistory/", authority: true }
    ],
    tags: ["walkman", "sony", "musique", "portable"],
    quality: { strictPlace: false, strictDate: false, dailyLife: false, sourceCount: 2 }
  },
  {
    id: "fr-1985-sida-et-capote",
    countryQid: "Q142", lang: "fr",
    momentKey: "sida-campagne-preservatif",
    momentLabel: "La campagne de prévention du sida change les comportements",
    label: "la campagne nationale de prévention du sida",
    category: "foundational_event", theme: "santé", gestureRoot: "sida_prevention",
    editorialScore: 86,
    date: "1987-04-01", year: 1987, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Première grande campagne nationale de prévention du sida",
    beforeState: "Avant 1987, la sexualité n'est pas un sujet de santé publique assumé dans les médias français.",
    afterState: "Après 1987, le préservatif entre dans le discours public et les comportements sexuels changent.",
    gestureChanged: "Tu peux entendre à la télévision et à la radio qu'il faut utiliser un préservatif — un tabou vient de tomber.",
    materialAnchor: "Préservatif, affiche de prévention et slogan gouvernemental",
    sceneText: "1987, France. Pour la première fois, une publicité gouvernementale dit le mot préservatif à la télévision. La honte recule. La prévention entre dans les conversations ordinaires.",
    fact: "En 1987, le gouvernement français lance la première grande campagne nationale de prévention contre le sida, brisant un tabou public.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/VIH/SIDA_en_France", authority: false }
    ],
    tags: ["sida", "sante", "prevention", "preservatif"],
    quality: { strictPlace: false, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
];
