import type { GestureRupture } from "../../../types";

export const FR_GESTURE_BACKFILL_1925_1949: GestureRupture[] = [
  {
    id: "fr-1928-assurances-sociales",
    countryQid: "Q142", lang: "fr",
    gestureKey: "ouvrir-des-droits-aux-assurances-sociales",
    gestureLabel: "ouvrir des droits aux assurances sociales",
    theme: "santé", gestureRoot: "assurances_sociales",
    editorialScore: 90,
    category: "health", direction: "impossible_to_possible",
    ruptureDate: "1928-04-05", ruptureYear: 1928, datePrecision: "day",
    placeName: "Caisse d'assurances sociales", placeType: "institution", placeQid: null,
    triggerLabel: "Loi sur les assurances sociales",
    triggerType: "law",
    beforeState: "Avant le 5 avril 1928, maladie, maternité ou invalidité sont couvertes par un patchwork de secours locaux, de mutuelles ou d'entraide patronale.",
    afterState: "Après le 5 avril 1928, le principe d'une assurance sociale obligatoire s'installe pour les salariés aux revenus modestes.",
    gestureChanged: "Tu peux t'immatriculer, cotiser et faire valoir des droits sociaux auprès d'une caisse au lieu de dépendre uniquement de l'assistance.",
    materialAnchor: "Carnet d'assuré, fiche de cotisation et guichet de caisse",
    sceneText: "5 avril 1928, au guichet d'une caisse. Les papiers ne servent plus seulement a prouver ton travail, mais aussi tes droits. Maladie, maternité, invalidité: la protection sociale cesse d'etre une faveur locale et commence a devenir une procedure nationale.",
    fact: "Le 5 avril 1928, la loi sur les assurances sociales crée en France un régime obligatoire couvrant notamment maladie, maternité, invalidité, vieillesse et décès pour les salariés sous plafond.",
    sources: [
      { label: "Sécurité sociale", url: "https://www.securite-sociale.fr/files/live/sites/SSFR/files/medias/DSS/2020/Loi%205%20avril%201928.pdf", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Assurance_maladie_en_France", authority: false }
    ],
    tags: ["sante", "protection-sociale", "caisse", "assurance"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1932-allocations-familiales-obligatoires",
    countryQid: "Q142", lang: "fr",
    gestureKey: "toucher-des-allocations-familiales-par-la-caisse",
    gestureLabel: "toucher des allocations familiales par la caisse",
    theme: "famille", gestureRoot: "allocations_familiales",
    editorialScore: 84,
    category: "family", direction: "impossible_to_possible",
    ruptureDate: "1932-03-11", ruptureYear: 1932, datePrecision: "day",
    placeName: "Caisse de compensation", placeType: "institution", placeQid: null,
    triggerLabel: "Loi rendant obligatoires les allocations familiales",
    triggerType: "law",
    beforeState: "Avant le 11 mars 1932, les aides pour enfants dépendent d'initiatives patronales ou de caisses encore inégales selon les lieux et les métiers.",
    afterState: "Après le 11 mars 1932, les employeurs privés doivent cotiser à une caisse de compensation qui verse des allocations aux salariés avec enfants.",
    gestureChanged: "Tu peux faire compter officiellement les charges de famille dans le budget du foyer via une caisse plutôt que seulement par arrangement d'entreprise.",
    materialAnchor: "Livret de famille, bulletin de paie et caisse de compensation",
    sceneText: "11 mars 1932, au bureau de paie. La ligne familiale cesse d'etre une faveur aleatoire. Pour un foyer ouvrier, l'enfant entre desormais dans les comptes par un circuit reconnu, avec cotisation patronale et versement organise.",
    fact: "La loi du 11 mars 1932 impose aux employeurs privés de s'affilier à une caisse de compensation versant des allocations familiales aux ouvriers et employés.",
    sources: [
      { label: "CAF", url: "https://www.caf.fr/sites/default/files/medias/501/PRESSE/100%20de%20la%20Caf/CP%20centenaire%20%285%29.pdf", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Caisse_d%27allocations_familiales_%28France%29", authority: false }
    ],
    tags: ["famille", "allocations", "caf", "enfants"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1938-capacite-femme-mariee",
    countryQid: "Q142", lang: "fr",
    gestureKey: "signer-un-acte-en-son-nom-en-tant-que-femme-mariee",
    gestureLabel: "signer un acte en son nom en tant que femme mariée",
    theme: "administration", gestureRoot: "capacite_femme_mariee",
    editorialScore: 92,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "1938-02-18", ruptureYear: 1938, datePrecision: "day",
    placeName: "Guichet administratif", placeType: "institution", placeQid: null,
    triggerLabel: "Loi modifiant la capacité de la femme mariée",
    triggerType: "law",
    beforeState: "Avant le 18 février 1938, une femme mariée reste juridiquement entravée par la puissance maritale et l'incapacité civile issue du code Napoléon.",
    afterState: "Après le 18 février 1938, la puissance maritale et l'incapacité juridique de la femme mariée sont abolies en droit français.",
    gestureChanged: "Tu peux signer en ton nom au guichet sans que l'acte commence juridiquement par ton mari.",
    materialAnchor: "Pièce d'identité, stylo et formulaire signé à son nom",
    sceneText: "18 fevrier 1938, devant un guichet. Le geste reste le meme, mais pas sa valeur: une femme mariee peut enfin engager sa signature autrement qu'en prolongement automatique de celle de son mari. L'administration change de visage jusque dans l'encre du formulaire.",
    fact: "La loi du 18 février 1938 supprime en France la puissance maritale et l'incapacité juridique de la femme mariée.",
    sources: [
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000000500831", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Puissance_maritale", authority: false }
    ],
    tags: ["femmes", "administration", "etat-civil", "droits"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1936-conges-payes",
    countryQid: "Q142", lang: "fr",
    gestureKey: "partir-en-vacances-avec-les-conges-payes",
    gestureLabel: "partir en vacances grâce aux congés payés",
    theme: "travail", gestureRoot: "partir_en_vacances",
    editorialScore: 96,
    category: "work", direction: "impossible_to_possible",
    ruptureDate: "1936-06-20", ruptureYear: 1936, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi instituant les congés payés",
    triggerType: "law",
    beforeState: "Avant le 20 juin 1936, les ouvriers ne disposent d'aucun droit légal à des vacances payées.",
    afterState: "Après le 20 juin 1936, tout salarié a droit à deux semaines de congés rémunérés par an.",
    gestureChanged: "Tu peux quitter le travail deux semaines l'été avec ta paye sans perdre ton emploi.",
    materialAnchor: "Valise, billet de train et carte d'été",
    sceneText: "20 juin 1936, en France. Pour la première fois, tu prépares ta valise sans peur de rentrer sans travail. Le train du 14 juillet part vers la mer, la montagne ou le village — payé par ton patron.",
    fact: "Le 20 juin 1936, la loi instituant les congés payés est promulguée en France : deux semaines de vacances rémunérées pour tous les salariés.",
    sources: [
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000681072", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Cong%C3%A9s_pay%C3%A9s_en_France", authority: false }
    ],
    tags: ["travail", "vacances", "conges", "sncf"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1936-semaine-40h",
    countryQid: "Q142", lang: "fr",
    gestureKey: "travailler-40-heures-par-semaine",
    gestureLabel: "travailler 40 heures par semaine",
    theme: "travail", gestureRoot: "travailler_40_heures",
    editorialScore: 88,
    category: "work", direction: "possible_to_impossible",
    ruptureDate: "1936-06-21", ruptureYear: 1936, datePrecision: "day",
    placeName: "Usine et bureau", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi sur la semaine de 40 heures",
    triggerType: "law",
    beforeState: "Avant juin 1936, la semaine légale de travail dépasse souvent 40 heures sans limite claire.",
    afterState: "Après juin 1936, la semaine de 40 heures est la référence légale en France.",
    gestureChanged: "Tu ne peux plus être contraint de travailler au-delà de 40 heures sans heures supplémentaires.",
    materialAnchor: "Feuille de pointage et pendule d'usine",
    sceneText: "21 juin 1936, à l'usine. La semaine se compte désormais autrement sur la feuille de pointage. Le temps de travail hebdomadaire plafonne légalement à 40 heures.",
    fact: "Le 21 juin 1936, la loi sur la semaine de 40 heures est promulguée en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Semaine_de_40_heures_en_France", authority: false }
    ],
    tags: ["travail", "horaires", "40h", "usine"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1944-vote-femmes",
    countryQid: "Q142", lang: "fr",
    gestureKey: "voter-pour-la-premiere-fois-en-tant-que-femme",
    gestureLabel: "voter pour la première fois en tant que femme",
    theme: "administration", gestureRoot: "voter_en_tant_que_femme",
    editorialScore: 98,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "1944-04-21", ruptureYear: 1944, datePrecision: "day",
    placeName: "Bureau de vote", placeType: "institution", placeQid: null,
    triggerLabel: "Ordonnance accordant le droit de vote aux femmes",
    triggerType: "law",
    beforeState: "Avant le 21 avril 1944, les femmes françaises ne peuvent pas voter ni se présenter aux élections.",
    afterState: "Après le 21 avril 1944, les femmes sont électrices et éligibles à égalité avec les hommes.",
    gestureChanged: "Tu peux entrer dans le bureau de vote et glisser ton bulletin dans l'urne.",
    materialAnchor: "Carte d'électrice, isoloir et urne",
    sceneText: "21 avril 1944, bureau de vote. Pour la première fois, une Française entre dans l'isoloir avec sa carte d'électrice. Le bulletin dans l'urne — un geste ordinaire pour les hommes depuis 1848, nouveau pour elle.",
    fact: "Le 21 avril 1944, l'ordonnance d'Alger accorde le droit de vote et d'éligibilité aux femmes françaises.",
    sources: [
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000699974", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Droit_de_vote_des_femmes_en_France", authority: false }
    ],
    tags: ["vote", "femmes", "droits", "elections"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1945-securite-sociale",
    countryQid: "Q142", lang: "fr",
    gestureKey: "se-faire-rembourser-ses-soins-par-la-secu",
    gestureLabel: "se faire rembourser ses soins médicaux",
    theme: "santé", gestureRoot: "se_faire_rembourser_par_la_secu",
    editorialScore: 96,
    category: "health", direction: "impossible_to_possible",
    ruptureDate: "1945-10-04", ruptureYear: 1945, datePrecision: "day",
    placeName: "Caisse de Sécurité sociale", placeType: "institution", placeQid: null,
    triggerLabel: "Ordonnance créant la Sécurité sociale",
    triggerType: "law",
    beforeState: "Avant octobre 1945, les soins médicaux ne sont pas remboursés de façon universelle et systématique.",
    afterState: "Après octobre 1945, la Sécurité sociale prend en charge une partie des frais médicaux de tous les salariés.",
    gestureChanged: "Tu peux déposer ta feuille de soins à la caisse et récupérer une partie de tes frais médicaux.",
    materialAnchor: "Feuille de soins, ordonnance et guichet de la Sécu",
    sceneText: "4 octobre 1945, caisse de Sécurité sociale. La feuille de soins ne finit plus dans un tiroir : elle donne droit à un remboursement. Pour la première fois, tomber malade ne ruine pas forcément.",
    fact: "Le 4 octobre 1945, l'ordonnance crée la Sécurité sociale française, assurant un remboursement des frais médicaux.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/S%C3%A9curit%C3%A9_sociale_en_France", authority: false },
      { label: "Sécu", url: "https://www.securite-sociale.fr/la-secu-cest-quoi/histoire", authority: true }
    ],
    tags: ["sante", "secu", "remboursement", "medecin"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1946-allocations-familiales",
    countryQid: "Q142", lang: "fr",
    gestureKey: "recevoir-des-allocations-familiales",
    gestureLabel: "recevoir des allocations familiales",
    theme: "famille", gestureRoot: "recevoir_allocations_familiales",
    editorialScore: 86,
    category: "family", direction: "impossible_to_possible",
    ruptureDate: "1946-08-22", ruptureYear: 1946, datePrecision: "day",
    placeName: "CAF", placeType: "institution", placeQid: null,
    triggerLabel: "Loi généralisant les allocations familiales",
    triggerType: "law",
    beforeState: "Avant 1946, les allocations familiales n'existent que pour certaines catégories de travailleurs.",
    afterState: "Après 1946, tout foyer avec enfants peut prétendre à des allocations familiales.",
    gestureChanged: "Tu peux toucher des allocations chaque mois pour chaque enfant à charge.",
    materialAnchor: "Livret de famille, formulaire CAF et virement mensuel",
    sceneText: "1946, guichet de la CAF. Le livret de famille ouvre un droit mensuel. Chaque enfant représente désormais un versement régulier qui allège le budget familial.",
    fact: "En 1946, la loi généralise les allocations familiales à l'ensemble des familles françaises.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Allocation_familiale", authority: false }
    ],
    tags: ["famille", "allocations", "caf", "enfants"],
    quality: { strictPlace: true, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1948-hlm",
    countryQid: "Q142", lang: "fr",
    gestureKey: "habiter-un-hlm",
    gestureLabel: "habiter dans un logement HLM",
    theme: "maison", gestureRoot: "habiter_un_hlm",
    editorialScore: 82,
    category: "housing", direction: "impossible_to_possible",
    ruptureDate: "1948-09-01", ruptureYear: 1948, datePrecision: "month",
    placeName: "HLM France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi sur les habitations à loyer modéré",
    triggerType: "law",
    beforeState: "Avant 1948, les logements à loyer modéré n'existent pas sous cette forme nationale organisée.",
    afterState: "Après 1948, des logements à loyer modéré sont construits et attribués aux ménages modestes.",
    gestureChanged: "Tu peux déposer un dossier pour obtenir un logement à loyer réduit financé par l'État.",
    materialAnchor: "Dossier HLM, clés et cage d'escalier collective",
    sceneText: "1948, immeuble HLM. La clé que tu reçois ouvre un appartement neuf avec eau courante et chauffage. Pour des millions de Français, c'est la première fois qu'ils habitent un logement décent.",
    fact: "En 1948, la loi organise les habitations à loyer modéré (HLM) en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Habitation_%C3%A0_loyer_mod%C3%A9r%C3%A9", authority: false }
    ],
    tags: ["logement", "hlm", "loyer", "habitat"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
];
