import type { GestureRupture } from "../../../types";

export const FR_GESTURE_BACKFILL_1970_1989: GestureRupture[] = [
  {
    id: "fr-1971-loi-neuwirth-pilule",
    countryQid: "Q142", lang: "fr",
    gestureKey: "obtenir-la-pilule-contraceptive-sans-autorisation-parentale",
    gestureLabel: "obtenir la pilule contraceptive sans autorisation parentale",
    theme: "santé", gestureRoot: "pilule_contraception",
    editorialScore: 88,
    category: "health", direction: "impossible_to_possible",
    ruptureDate: "1971-01-20", ruptureYear: 1971, datePrecision: "day",
    placeName: "Pharmacie, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Décret autorisant la délivrance de la pilule sans ordonnance aux mineures",
    triggerType: "decree",
    beforeState: "Avant 1971, les mineures ne peuvent obtenir la pilule qu'avec l'accord parental.",
    afterState: "À partir de 1971, le décret d'application de la loi Neuwirth permet aux mineures d'accéder à la contraception sans autorisation parentale.",
    gestureChanged: "Tu peux te rendre à la pharmacie demander la pilule sans passer par tes parents.",
    materialAnchor: "Ordonnance médicale, plaquette de pilule et comptoir de pharmacie",
    sceneText: "Janvier 1971, pharmacie. Le décret d'application de la loi Neuwirth est entré en vigueur. Une jeune femme tend son ordonnance sans avoir eu à demander la permission à ses parents. Ce qui relevait du secret médical ou de la honte devient un droit ordinaire.",
    fact: "En 1971, les décrets d'application de la loi Neuwirth (1967) permettent enfin la délivrance de contraceptifs aux mineures sans autorisation parentale.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Loi_Neuwirth", authority: false },
      { label: "Vie-publique.fr", url: "https://www.vie-publique.fr/fiches/23892-la-legalisation-de-la-contraception", authority: true }
    ],
    tags: ["contraception", "pilule", "neuwirth", "femmes"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1975-loi-veil-ivg",
    countryQid: "Q142", lang: "fr",
    gestureKey: "avoir-droit-a-une-ivg-dans-un-hopital-public",
    gestureLabel: "avoir droit à une IVG dans un hôpital public",
    theme: "santé", gestureRoot: "ivg_loi_veil",
    editorialScore: 94,
    category: "health", direction: "impossible_to_possible",
    ruptureDate: "1975-01-17", ruptureYear: 1975, datePrecision: "day",
    placeName: "Hôpital public, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi Veil légalisant l'interruption volontaire de grossesse",
    triggerType: "law",
    beforeState: "Avant le 17 janvier 1975, l'avortement est un crime passible de prison en France.",
    afterState: "Après le 17 janvier 1975, l'IVG est légale et remboursée dans les hôpitaux publics.",
    gestureChanged: "Tu peux demander une IVG à un médecin sans craindre d'être poursuivie.",
    materialAnchor: "Formulaire de consultation, hôpital et carte Vitale",
    sceneText: "17 janvier 1975. La loi Veil passe à l'Assemblée. Simone Veil a bravé les insultes à la tribune. Désormais, l'avortement n'est plus un crime — c'est un acte médical légal, remboursé, encadré. Une rupture irréversible dans l'histoire des droits des femmes.",
    fact: "Le 17 janvier 1975, la loi Veil légalise l'interruption volontaire de grossesse en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Loi_Veil", authority: false },
      { label: "Vie-publique.fr", url: "https://www.vie-publique.fr/fiches/23893-livg-en-france", authority: true }
    ],
    tags: ["ivg", "veil", "avortement", "femmes"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1976-roissy-rail-cdg",
    countryQid: "Q142", lang: "fr",
    gestureKey: "prendre-le-train-jusqu-a-laeroport-roissy",
    gestureLabel: "prendre le train jusqu'à l'aéroport de Roissy-Charles-de-Gaulle",
    theme: "transport", gestureRoot: "rer_roissy",
    editorialScore: 82,
    category: "transport", direction: "impossible_to_possible",
    ruptureDate: "1976-05-30", ruptureYear: 1976, datePrecision: "day",
    placeName: "Aéroport Charles-de-Gaulle, Roissy", placeType: "site", placeQid: "Q90600",
    triggerLabel: "Mise en service de la liaison ferroviaire Roissy-Rail (Paris-Nord — aéroport CDG)",
    triggerType: "public_rollout",
    beforeState: "Avant mai 1976, rejoindre l'aéroport de Roissy se fait surtout en voiture ou en bus depuis Paris.",
    afterState: "À partir du 30 mai 1976, la liaison « Roissy-Rail » relie directement la gare du Nord à l'aéroport en une vingtaine de minutes.",
    gestureChanged: "Tu peux rallier l'aéroport depuis la gare du Nord en train, sans dépendre uniquement de la voiture ou du bus.",
    materialAnchor: "Valise, quai de gare du Nord et panneau Roissy-Rail",
    sceneText: "Mai 1976, gare du Nord. Les premiers trains Z 6400 assurent la navette vers Roissy. L'aéroport vient d'être relié au réseau ferré : un trajet court, régulier, sans embouteillages sur l'autoroute du Nord.",
    fact: "Le 30 mai 1976, la SNCF met en service la liaison Roissy-Rail entre Paris-Nord et l'aéroport Charles-de-Gaulle.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Ligne_d%27Aulnay-sous-Bois_%C3%A0_Roissy_2-RER", authority: false }
    ],
    tags: ["transport", "roissy", "train", "aeroport"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1979-minitel-lancement",
    countryQid: "Q142", lang: "fr",
    gestureKey: "consulter-un-annuaire-sur-le-minitel",
    gestureLabel: "consulter un annuaire sur le Minitel",
    theme: "communication", gestureRoot: "minitel",
    editorialScore: 90,
    category: "media", direction: "impossible_to_possible",
    ruptureDate: "1980-07-15", ruptureYear: 1979, datePrecision: "year",
    placeName: "Domicile, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Lancement expérimental du Minitel à Saint-Malo",
    triggerType: "public_rollout",
    beforeState: "Avant 1980, pour chercher un numéro de téléphone, tu feuilleteras l'annuaire papier ou tu appelais les renseignements.",
    afterState: "Après le lancement du Minitel, tu peux interroger l'annuaire électronique depuis chez toi sur un terminal branché à la ligne.",
    gestureChanged: "Tu peux taper un nom sur le clavier et voir le numéro de téléphone s'afficher sur l'écran du Minitel.",
    materialAnchor: "Terminal Minitel, clavier et écran cathodique",
    sceneText: "1979-1980, Saint-Malo. Les premiers abonnés reçoivent le terminal. L'annuaire papier reste dans le tiroir : à sa place, un clavier et un écran. On tape un nom, on attend, et le numéro apparaît. La France vient d'inventer son internet avant l'heure.",
    fact: "En 1980, le Minitel est lancé expérimentalement à Saint-Malo pour remplacer l'annuaire papier — premier réseau informatique grand public français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Minitel", authority: false },
      { label: "INA", url: "https://www.ina.fr/ina-eclaire-actu/le-minitel-40-ans", authority: true }
    ],
    tags: ["minitel", "communication", "numerique", "annuaire"],
    quality: { strictPlace: true, strictDate: false, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1972-vote-18-ans",
    countryQid: "Q142", lang: "fr",
    gestureKey: "voter-pour-la-premiere-fois-a-18-ans",
    gestureLabel: "voter pour la première fois à 18 ans",
    theme: "administration", gestureRoot: "vote_18_ans",
    editorialScore: 88,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "1974-07-05", ruptureYear: 1972, datePrecision: "year",
    placeName: "Bureau de vote, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Abaissement de la majorité électorale à 18 ans",
    triggerType: "law",
    beforeState: "Avant juillet 1974, il faut avoir 21 ans pour voter en France.",
    afterState: "Après la loi de 1974, les 18-20 ans deviennent électeurs à part entière.",
    gestureChanged: "Tu peux glisser un bulletin dans l'urne à 18 ans — sans attendre 21 ans.",
    materialAnchor: "Carte d'électeur, isoloir et bulletin de vote",
    sceneText: "1974, bureau de vote. Pour la première fois, des jeunes de 18 ans présentent leur carte d'électeur. La loi abaisse la majorité — et avec elle, le droit de vote. Des millions de Français viennent d'entrer dans le corps électoral.",
    fact: "En 1974, la France abaisse l'âge de la majorité électorale de 21 à 18 ans, accordant le droit de vote à des millions de jeunes.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Droit_de_vote_en_France", authority: false }
    ],
    tags: ["vote", "jeunesse", "democratie", "18-ans"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1973-ticket-de-metro-magnétique",
    countryQid: "Q142", lang: "fr",
    gestureKey: "valider-son-ticket-de-metro-dans-le-composteur",
    gestureLabel: "valider son ticket de métro magnétique dans le composteur",
    theme: "transport", gestureRoot: "metro_ticket_magnetique",
    editorialScore: 80,
    category: "transport", direction: "impossible_to_possible",
    ruptureDate: "1973-01-01", ruptureYear: 1973, datePrecision: "year",
    placeName: "Métro parisien", placeType: "site", placeQid: "Q23718",
    triggerLabel: "Introduction du ticket magnétique dans le métro parisien",
    triggerType: "public_rollout",
    beforeState: "Avant 1973, les tickets de métro parisiens sont en carton avec perforation manuelle ou poinçonnage.",
    afterState: "À partir de 1973, les tickets magnétiques permettent un compostage automatique à l'entrée du métro.",
    gestureChanged: "Tu peux insérer ton ticket dans la fente de la borne, et le portillon s'ouvre automatiquement.",
    materialAnchor: "Ticket de métro magnétique, borne de compostage et portillon RATP",
    sceneText: "1973, entrée du métro parisien. Le ticket glisse dans la borne. Un déclic, le portillon s'ouvre. Le poinçonneur est remplacé par une machine. Un geste quotidien qui dure quarante ans vient de naître.",
    fact: "En 1973, la RATP introduit le ticket magnétique dans le métro parisien, automatisant l'accès aux quais.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Transport_en_commun_%C3%A0_Paris", authority: false }
    ],
    tags: ["metro", "transport", "paris", "ticket"],
    quality: { strictPlace: true, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1976-interdiction-colorants-alimentaires",
    countryQid: "Q142", lang: "fr",
    gestureKey: "acheter-des-produits-sans-dix-colorants-de-synthese-interdits",
    gestureLabel: "acheter des produits sans dix colorants de synthèse désormais interdits",
    theme: "santé", gestureRoot: "colorants_alimentaires_interdits",
    editorialScore: 84,
    category: "food", direction: "impossible_to_possible",
    ruptureDate: "1976-10-01", ruptureYear: 1976, datePrecision: "day",
    placeName: "Supermarché et commerce de détail, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Arrêté interministériel (juin 1976) : interdiction de dix colorants dans l'industrie agroalimentaire (effet au 1er octobre 1976)",
    triggerType: "decree",
    beforeState: "Avant l'automne 1976, certains colorants de synthèse (E 103, E 105, E 111, etc.) sont encore employés dans des produits courants.",
    afterState: "À partir du 1er octobre 1976, leur emploi en fabrication est interdit : les industriels doivent reformuler les recettes.",
    gestureChanged: "Tu peux lire une liste d'ingrédients où ces additifs ne figurent plus — le cahier des charges du rayon s'est resserré.",
    materialAnchor: "Étiquette nutritionnelle, liste des ingrédients et caddie de supermarché",
    sceneText: "Automne 1976, grande surface. Les fabricants ont retiré dix colorants de leurs formules. Ce n'est pas encore l'étiquetage nutritionnel complet, mais l'État encadre déjà ce qui entre dans le panier.",
    fact: "À partir du 1er octobre 1976, l'emploi de dix colorants alimentaires de synthèse est interdit dans la fabrication des denrées en France.",
    sources: [
      { label: "Larousse — Journal de l'année 1976 (consommation)", url: "https://www.larousse.fr/archives/journaux_annee/1976/341/consommation", authority: false },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Liste_des_additifs_alimentaires", authority: false }
    ],
    tags: ["consommation", "alimentation", "additifs", "sante"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1982-ivg-remboursement-secu",
    countryQid: "Q142", lang: "fr",
    gestureKey: "beneficier-du-remboursement-de-livg-par-la-secu",
    gestureLabel: "bénéficier du remboursement de l'IVG par la Sécurité sociale",
    theme: "santé", gestureRoot: "ivg_remboursement",
    editorialScore: 72,
    category: "health", direction: "impossible_to_possible",
    ruptureDate: "1982-12-31", ruptureYear: 1982, datePrecision: "year",
    placeName: "Hôpital public et CPAM, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Prise en charge de l'IVG par l'assurance maladie (lois de finances / mesures 1982)",
    triggerType: "law",
    beforeState: "Après la légalisation de l'IVG en 1975, l'acte n'est pas encore pris en charge comme les autres soins hospitaliers.",
    afterState: "À partir de 1982, l'IVG est remboursée sur la même base que les actes pris en charge par l'assurance maladie.",
    gestureChanged: "Tu peux subir une IVG dans un établissement conventionné avec un parcours de remboursement aligné sur les autres soins.",
    materialAnchor: "Feuille de soins, carte Vitale et tiers payant hospitalier",
    sceneText: "1982, hôpital public. La feuille de soins IVG rejoint le circuit classique de la Sécurité sociale. La loi Veil avait légalisé ; les textes budgétaires et sociaux de 1982 rendent la prise en charge effective pour des millions de femmes.",
    fact: "En 1982, l'IVG devient remboursable par l'assurance maladie en France, après des années où le coût restait entièrement à la charge des patientes.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Interruption_volontaire_de_grossesse_en_France", authority: false }
    ],
    tags: ["ivg", "remboursement", "secu", "femmes"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1980-tele-couleur-foyer",
    countryQid: "Q142", lang: "fr",
    gestureKey: "regarder-la-tele-couleur-a-la-maison",
    gestureLabel: "regarder la télévision couleur chez soi",
    theme: "loisirs", gestureRoot: "television_couleur_foyer",
    editorialScore: 84,
    category: "media", direction: "impossible_to_possible",
    ruptureDate: "1980-01-01", ruptureYear: 1980, datePrecision: "year",
    placeName: "Salon familial, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Généralisation de la télévision couleur dans les foyers français",
    triggerType: "public_rollout",
    beforeState: "Avant 1980, la majorité des foyers français regardent encore la télévision en noir et blanc.",
    afterState: "À partir du début des années 1980, la télévision couleur devient la norme dans la plupart des foyers.",
    gestureChanged: "Tu peux regarder les informations et les films avec les couleurs réelles — et non plus en camaïeu de gris.",
    materialAnchor: "Téléviseur couleur, programme TV et antenne de toit",
    sceneText: "1980, salon. Le vieux poste noir et blanc est parti. Le nouveau téléviseur couleur trône dans l'angle. Les journalistes ont maintenant des visages colorés, le ciel est bleu sur les images de reportage. La France regarde en couleur.",
    fact: "Au début des années 1980, la télévision couleur se généralise dans les foyers français — plus de 60 % des ménages en sont équipés.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9vision_en_couleur_en_France", authority: false }
    ],
    tags: ["television", "couleur", "medias", "foyer"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-1972-securite-sociale-generalisee",
    countryQid: "Q142", lang: "fr",
    gestureKey: "etre-couvert-par-la-secu-sans-etre-salarie",
    gestureLabel: "être couvert par la Sécurité sociale sans être salarié",
    theme: "santé", gestureRoot: "secu_generalisee",
    editorialScore: 86,
    category: "health", direction: "impossible_to_possible",
    ruptureDate: "1974-07-24", ruptureYear: 1974, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi généralisant la Sécurité sociale",
    triggerType: "law",
    beforeState: "Avant juillet 1974, la couverture maladie reste liée au statut de salarié ou d'ayant droit.",
    afterState: "Après juillet 1974, toute personne résidant en France peut être affiliée à la Sécurité sociale.",
    gestureChanged: "Tu peux ouvrir des droits à la Sécu même si tu n'es pas salarié ni rattaché à un conjoint qui l'est.",
    materialAnchor: "Carnet de santé, carte d'assuré et guichet CPAM",
    sceneText: "24 juillet 1974, guichet CPAM. La couverture n'est plus réservée aux seuls salariés. Artisans, étudiants, inactifs — tout résident peut désormais s'affilier. La carte d'assuré social sort de son cercle restreint.",
    fact: "Le 24 juillet 1974, la loi généralise la Sécurité sociale à l'ensemble de la population française résidente.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/S%C3%A9curit%C3%A9_sociale_en_France", authority: false },
      { label: "Sécu", url: "https://www.securite-sociale.fr/la-secu-cest-quoi/histoire", authority: true }
    ],
    tags: ["sante", "secu", "affiliation", "couverture"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1978-informatique-et-libertes",
    countryQid: "Q142", lang: "fr",
    gestureKey: "avoir-droit-a-ses-donnees-personnelles",
    gestureLabel: "avoir un droit de regard sur ses données personnelles",
    theme: "communication", gestureRoot: "droits_donnees_personnelles",
    editorialScore: 84,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "1978-01-06", ruptureYear: 1978, datePrecision: "day",
    placeName: "Administration et entreprises", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi Informatique et Libertés",
    triggerType: "law",
    beforeState: "Avant le 6 janvier 1978, les fichiers informatiques sur les individus n'ont pas de cadre légal protecteur.",
    afterState: "Après le 6 janvier 1978, toute personne peut s'informer, accéder et rectifier ses données dans les fichiers.",
    gestureChanged: "Tu peux demander à consulter et corriger les informations te concernant dans un fichier informatique.",
    materialAnchor: "Dossier administratif, terminal et formulaire CNIL",
    sceneText: "6 janvier 1978, France. Les ordinateurs s'installent partout dans les administrations. La loi fixe pour la première fois un droit : tu peux savoir ce qu'ils savent de toi, et demander qu'on corrige.",
    fact: "Le 6 janvier 1978, la loi Informatique et Libertés crée en France le droit d'accès aux fichiers informatiques personnels.",
    sources: [
      { label: "CNIL", url: "https://www.cnil.fr/fr/la-loi-informatique-et-libertes", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Loi_informatique_et_libert%C3%A9s", authority: false }
    ],
    tags: ["donnees", "informatique", "cnil", "droits"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1981-peine-de-mort-abolie",
    countryQid: "Q142", lang: "fr",
    gestureKey: "vivre-dans-un-pays-sans-peine-de-mort",
    gestureLabel: "vivre dans un pays sans peine de mort",
    theme: "administration", gestureRoot: "abolition_peine_de_mort",
    editorialScore: 94,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "1981-10-09", ruptureYear: 1981, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi abolissant la peine de mort",
    triggerType: "law",
    beforeState: "Avant le 9 octobre 1981, la peine de mort existe en droit français et des exécutions ont lieu.",
    afterState: "Après le 9 octobre 1981, la France abolit la peine capitale — la guillotine disparaît.",
    gestureChanged: "Tu vis dans un pays où aucun tribunal ne peut plus condamner à mort.",
    materialAnchor: "Code pénal, salle d'audience et plaidoirie de Badinter",
    sceneText: "9 octobre 1981, Assemblée nationale. Robert Badinter monte à la tribune. La loi passe. La guillotine entre dans l'histoire. La France rejoint les démocraties qui ont renoncé à tuer au nom de la justice.",
    fact: "Le 9 octobre 1981, la France abolit la peine de mort sous l'impulsion du garde des Sceaux Robert Badinter.",
    sources: [
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000700213", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Abolition_de_la_peine_de_mort_en_France", authority: false }
    ],
    tags: ["justice", "peine-de-mort", "badinter", "droits"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1985-bac-informatique",
    countryQid: "Q142", lang: "fr",
    gestureKey: "avoir-une-heure-d-informatique-au-lycee",
    gestureLabel: "avoir un cours d'informatique au lycée",
    theme: "école", gestureRoot: "informatique_lycee",
    editorialScore: 76,
    category: "school", direction: "impossible_to_possible",
    ruptureDate: "1985-09-01", ruptureYear: 1985, datePrecision: "month",
    placeName: "Lycée français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Plan Informatique Pour Tous",
    triggerType: "public_rollout",
    beforeState: "Avant 1985, l'ordinateur est absent des salles de classe françaises.",
    afterState: "Après 1985, des ordinateurs TO7 entrent dans les lycées et l'informatique devient une matière scolaire.",
    gestureChanged: "Tu peux toucher un ordinateur à l'école et taper ton premier programme.",
    materialAnchor: "Thomson TO7, clavier caoutchouc et écran vert",
    sceneText: "Septembre 1985, salle informatique du lycée. Les Thomson TO7 sont alignés en rangées. Le professeur dicte les premières lignes de Basic. C'est bizarre, lent, mais c'est un ordinateur — et il est là pour toi.",
    fact: "En 1985, le Plan Informatique Pour Tous installe 120 000 micro-ordinateurs dans les écoles françaises.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Plan_Informatique_pour_tous", authority: false },
      { label: "INA", url: "https://www.ina.fr/ina-eclaire-actu/plan-informatique-pour-tous-1985", authority: true }
    ],
    tags: ["ecole", "informatique", "to7", "lycee"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-1989-europe-1-libre",
    countryQid: "Q142", lang: "fr",
    gestureKey: "passer-le-bac-a-18-ans-en-terminale",
    gestureLabel: "passer le baccalauréat rénové",
    theme: "école", gestureRoot: "baccalaureat",
    editorialScore: 78,
    category: "school", direction: "impossible_to_possible",
    ruptureDate: "1989-06-01", ruptureYear: 1989, datePrecision: "month",
    placeName: "Centre d'examen", placeType: "country", placeQid: "Q142",
    triggerLabel: "Objectif 80 % d'une classe d'âge au niveau bac",
    triggerType: "public_rollout",
    beforeState: "Avant 1989, moins de 30 % d'une classe d'âge obtient le baccalauréat.",
    afterState: "Après 1989, la massification scolaire pousse vers 80 % de bacheliers par génération.",
    gestureChanged: "Le bac cesse d'être réservé à une élite et devient un horizon ordinaire pour la majorité des lycéens.",
    materialAnchor: "Feuille de composition, stylo bille et salle d'examen",
    sceneText: "1989, salle d'examen. La table numérotée, le sujet retourné, le stylo prêt. Passer le bac n'est plus un parcours d'exception — c'est une étape ordinaire du lycée français.",
    fact: "En 1989, la France se fixe l'objectif de mener 80 % d'une classe d'âge au niveau du baccalauréat.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Baccalaur%C3%A9at_en_France", authority: false }
    ],
    tags: ["bac", "lycee", "examen", "jeunesse"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
];
