import type { GestureRupture } from "../../../types";

export const FR_GESTURE_BACKFILL_2010_current: GestureRupture[] = [
  {
    id: "fr-2010-reforme-retraites",
    countryQid: "Q142", lang: "fr",
    gestureKey: "connaitre-son-age-de-depart-a-la-retraite",
    gestureLabel: "connaître son âge de départ à la retraite après la réforme",
    theme: "travail", gestureRoot: "retraite_age_legal",
    editorialScore: 84,
    category: "work", direction: "possible_to_impossible",
    ruptureDate: "2010-11-09", ruptureYear: 2010, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi portant réforme des retraites (âge légal à 62 ans)",
    triggerType: "law",
    beforeState: "Avant novembre 2010, le débat sur l'âge de départ à la retraite reste encore partiellement ancré dans les repères antérieurs.",
    afterState: "Après la loi de novembre 2010, l'âge légal de départ à la retraite est fixé à 62 ans et le paysage des projections individuelles change.",
    gestureChanged: "Tu peux lire sur tes relevés et dans la presse un nouvel âge cible pour partir, avec des règles de décote et surcote revues.",
    materialAnchor: "Relevé de carrière, simulateur Agirc-Arrco et calendrier de réforme",
    sceneText: "9 novembre 2010, en France. La reforme des retraites est promulguee. Dans les entreprises et les syndicats, on recalcule les parcours. L'age legal de depart se lit desormais autrement sur les fiches de paie et les projets de vie.",
    fact: "Le 9 novembre 2010, la loi portant réforme des retraites est promulguée en France, fixant notamment l'âge légal de départ à 62 ans.",
    sources: [
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/R%C3%A9forme_des_retraites_en_France_de_2010", authority: false }
    ],
    tags: ["retraite", "travail", "loi", "2010"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-2011-velib-autopartage",
    countryQid: "Q142", lang: "fr",
    gestureKey: "prendre-un-velo-en-libre-service",
    gestureLabel: "prendre un vélo en libre-service dans la rue",
    theme: "transport", gestureRoot: "velo_libre_service",
    editorialScore: 80,
    category: "transport", direction: "impossible_to_possible",
    ruptureDate: "2007-07-15", ruptureYear: 2007, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Lancement de Vélib'",
    triggerType: "service_start",
    beforeState: "Avant juillet 2007, se déplacer à vélo en ville suppose de posséder son propre vélo.",
    afterState: "Après juillet 2007, on peut prendre un vélo en station dans la rue, l'utiliser et le redéposer ailleurs.",
    gestureChanged: "Tu peux débloquer un vélo avec ta carte, pédaler jusqu'à destination et le redéposer dans n'importe quelle station.",
    materialAnchor: "Station Vélib', borne de déverrouillage et vélo gris",
    sceneText: "15 juillet 2007, Paris. La borne grésille, le vélo se débloque. Tu pédales jusqu'au bureau et le redéposes dans une autre station. La ville se parcourt différemment.",
    fact: "Le 15 juillet 2007, Vélib' est lancé à Paris avec 10 000 vélos et 750 stations, inventant le vélo en libre-service urbain.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/V%C3%A9lib%27", authority: false },
      { label: "Mairie de Paris", url: "https://www.paris.fr/velib", authority: true }
    ],
    tags: ["velo", "paris", "libre-service", "transport"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-2012-smartphone-quotidien",
    countryQid: "Q142", lang: "fr",
    gestureKey: "verifier-ses-notifications-le-matin",
    gestureLabel: "vérifier ses notifications en se levant",
    theme: "communication", gestureRoot: "verifier_notifications",
    editorialScore: 84,
    category: "media", direction: "impossible_to_possible",
    ruptureDate: "2012-01-01", ruptureYear: 2012, datePrecision: "year",
    placeName: "Chambre à coucher", placeType: "country", placeQid: "Q142",
    triggerLabel: "Bascule du smartphone comme premier écran du matin",
    triggerType: "public_rollout",
    beforeState: "Avant 2012, le premier geste du matin est d'allumer la radio ou d'ouvrir un journal.",
    afterState: "Après 2012, plus de la moitié des Français commencent leur journée en regardant leur téléphone.",
    gestureChanged: "Tu regardes tes messages, tes alertes et tes réseaux avant même de sortir du lit.",
    materialAnchor: "Smartphone posé sur la table de nuit, écran allumé",
    sceneText: "2012, dans les chambres francaises. Le reveil sonne sur le telephone pose a cote du lit. Avant meme de poser le pied par terre, la main attrape l'ecran et fait defiler la nuit. La journee commence desormais par un smartphone.",
    fact: "En 2012, le smartphone devient l'écran principal du quotidien pour une majorité de Français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9phone_intelligent", authority: false }
    ],
    tags: ["smartphone", "notifications", "matin", "mobile"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2014-paiement-sans-contact",
    countryQid: "Q142", lang: "fr",
    gestureKey: "payer-sans-contact-sous-20-euros",
    gestureLabel: "payer sans contact pour un petit achat",
    theme: "argent", gestureRoot: "payer_sans_contact",
    editorialScore: 86,
    category: "money", direction: "impossible_to_possible",
    ruptureDate: "2014-01-01", ruptureYear: 2014, datePrecision: "year",
    placeName: "Caisse de commerce", placeType: "institution", placeQid: null,
    triggerLabel: "Généralisation du paiement sans contact en France",
    triggerType: "public_rollout",
    beforeState: "Avant 2014, tout paiement par carte nécessite d'insérer la carte et de composer son code.",
    afterState: "Après 2014, les petits achats passent par un simple geste d'approche de la carte.",
    gestureChanged: "Tu approches la carte du terminal sans l'insérer ni composer ton code pour les petits montants.",
    materialAnchor: "Carte bancaire, pictogramme NFC et terminal de caisse",
    sceneText: "2014, dans les boulangeries et supérettes francaises. La carte effleure le terminal. Pas de code, pas de ticket a signer, juste un bip et c'est regle. Le geste du paiement quotidien se raccourcit d'une dizaine de secondes.",
    fact: "En 2014, le paiement sans contact se généralise pour les achats inférieurs à 20 euros en France.",
    sources: [
      { label: "Banque de France", url: "https://www.banque-france.fr", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Paiement_sans_contact", authority: false }
    ],
    tags: ["paiement", "sans-contact", "nfc", "carte"],
    quality: { strictPlace: true, strictDate: false, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-2017-scandale-metoo",
    countryQid: "Q142", lang: "fr",
    gestureKey: "parler-de-harcelement-avec-hashtag",
    gestureLabel: "dénoncer le harcèlement avec un hashtag",
    theme: "administration", gestureRoot: "parole_liberee_harcelement",
    editorialScore: 82,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "2017-10-15", ruptureYear: 2017, datePrecision: "day",
    placeName: "Réseaux sociaux", placeType: "country", placeQid: "Q142",
    triggerLabel: "Mouvement #MeToo en France — #BalanceTonPorc",
    triggerType: "public_rollout",
    beforeState: "Avant octobre 2017, les témoignages de harcèlement sexuel se font rarement dans l'espace public.",
    afterState: "Après octobre 2017, la parole se libère massivement sur les réseaux sociaux en France.",
    gestureChanged: "Tu peux publier ton témoignage sous hashtag et rejoindre une prise de parole collective visible.",
    materialAnchor: "Téléphone, réseau social et hashtag #BalanceTonPorc",
    sceneText: "15 octobre 2017, sur les reseaux sociaux francais. #BalanceTonPorc envahit les fils d'actualite. Des milliers de femmes publient leurs temoignages. La parole liberee devient un geste public, collectif et national.",
    fact: "Le 15 octobre 2017, le hashtag #MeToo et #BalanceTonPorc déclenchent en France une vague de témoignages sur le harcèlement sexuel.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Mouvement_#MeToo_en_France", authority: false }
    ],
    tags: ["metoo", "harcelement", "reseaux", "parole"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2020-masque-obligatoire",
    countryQid: "Q142", lang: "fr",
    gestureKey: "porter-un-masque-dans-les-lieux-publics",
    gestureLabel: "porter un masque dans les lieux publics",
    theme: "santé", gestureRoot: "porter_masque_covid",
    editorialScore: 90,
    category: "public_space", direction: "possible_to_impossible",
    ruptureDate: "2020-07-20", ruptureYear: 2020, datePrecision: "day",
    placeName: "Lieux publics fermés", placeType: "country", placeQid: "Q142",
    triggerLabel: "Obligation du port du masque dans les lieux publics",
    triggerType: "law",
    beforeState: "Avant le 20 juillet 2020, entrer dans un magasin ou les transports sans masque est normal.",
    afterState: "Après le 20 juillet 2020, le masque est obligatoire dans tous les lieux publics clos en France.",
    gestureChanged: "Tu ne peux plus entrer dans un lieu public fermé sans couvrir ton nez et ta bouche.",
    materialAnchor: "Masque chirurgical, entrée de magasin et distributeur de gel",
    sceneText: "20 juillet 2020, entrée du supermarché. La main cherche le masque dans la poche avant de pousser la porte. Le gel hydroalcoolique suit. Le visage à moitié couvert devient la norme du quotidien.",
    fact: "Le 20 juillet 2020, le port du masque devient obligatoire dans tous les lieux publics clos en France dans le contexte de la pandémie de Covid-19.",
    sources: [
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Pand%C3%A9mie_de_Covid-19_en_France", authority: false }
    ],
    tags: ["covid", "masque", "pandemie", "sante"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 2 }
  },
  {
    id: "fr-2023-ia-quotidien",
    countryQid: "Q142", lang: "fr",
    gestureKey: "poser-une-question-a-une-ia",
    gestureLabel: "poser une question à une intelligence artificielle",
    theme: "communication", gestureRoot: "utiliser_ia_chatbot",
    editorialScore: 84,
    category: "media", direction: "impossible_to_possible",
    ruptureDate: "2023-01-01", ruptureYear: 2023, datePrecision: "year",
    placeName: "Ordinateur ou téléphone", placeType: "country", placeQid: "Q142",
    triggerLabel: "Démocratisation des IA conversationnelles (ChatGPT)",
    triggerType: "public_rollout",
    beforeState: "Avant 2023, interroger une IA pour rédiger, traduire ou résoudre un problème n'est pas un geste ordinaire.",
    afterState: "Après 2023, des millions de Français posent des questions à une IA dans leur quotidien professionnel ou personnel.",
    gestureChanged: "Tu peux taper ta question en langage naturel et recevoir une réponse rédigée en quelques secondes.",
    materialAnchor: "Clavier, fenêtre de chat et réponse générée instantanément",
    sceneText: "2023, dans les bureaux et domiciles francais. Tu tapes ta question comme a un collegue. La reponse arrive en quelques secondes, redigee, organisee, parfois fausse. Le rapport a l'ecrit et au savoir change silencieusement.",
    fact: "En 2023, les IA conversationnelles comme ChatGPT entrent dans les usages quotidiens de millions de Français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/ChatGPT", authority: false }
    ],
    tags: ["ia", "chatgpt", "numerique", "quotidien"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2019-incendie-notre-dame",
    countryQid: "Q142", lang: "fr",
    gestureKey: "voir-la-cathedrale-en-feu-sur-son-telephone",
    gestureLabel: "voir Notre-Dame en feu sur son téléphone en direct",
    theme: "loisirs", gestureRoot: "notre_dame_incendie",
    editorialScore: 88,
    category: "public_space", direction: "possible_to_impossible",
    ruptureDate: "2019-04-15", ruptureYear: 2019, datePrecision: "day",
    placeName: "Cathédrale Notre-Dame de Paris", placeType: "site", placeQid: "Q2986748",
    triggerLabel: "Incendie de la cathédrale Notre-Dame de Paris",
    triggerType: "public_rollout",
    beforeState: "Avant le 15 avril 2019, la flèche de Notre-Dame domine le paysage parisien comme un repère immuable.",
    afterState: "Après l'incendie, des millions de Français découvrent en direct que même les monuments les plus familiers peuvent basculer en une soirée.",
    gestureChanged: "Tu peux suivre les flammes sur ton écran, partager l'émotion et comprendre que le patrimoine n'est plus seulement une certitude.",
    materialAnchor: "Téléphone, flux vidéo et flèche en feu",
    sceneText: "15 avril 2019, soirée parisienne. Les écrans montrent la flèche qui cède, la fumée qui envahit le ciel. La ville entière retient son souffle devant un monument qui brûle en direct.",
    fact: "Le 15 avril 2019, un incendie détruit en partie la cathédrale Notre-Dame de Paris et bouleverse l'attention portée au patrimoine national.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Incendie_de_Notre-Dame_de_Paris", authority: false }
    ],
    tags: ["notre-dame", "patrimoine", "paris", "2019"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2022-finale-coupe-du-monde",
    countryQid: "Q142", lang: "fr",
    gestureKey: "regarder-la-finale-du-mondial-en-famille",
    gestureLabel: "regarder la finale du Mondial de football en famille ou entre amis",
    theme: "loisirs", gestureRoot: "coupe_du_monde_foot",
    editorialScore: 84,
    category: "media", direction: "impossible_to_possible",
    ruptureDate: "2022-12-18", ruptureYear: 2022, datePrecision: "day",
    placeName: "Salon et bars français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Finale de la Coupe du monde 2022 (France–Argentine)",
    triggerType: "public_rollout",
    beforeState: "Avant décembre 2022, le dernier souvenir mondial de finale remonte à 2018.",
    afterState: "Après la finale 2022, des millions de téléspectateurs français vivent un match de légende jusqu'aux tirs au but.",
    gestureChanged: "Tu peux vivre un rendez-vous collectif devant l'écran, entre tension, espoir et déception partagée.",
    materialAnchor: "Téléviseur, coupe du monde et maillot bleu",
    sceneText: "18 decembre 2022, salons et bars francais. Le match s'enchaine jusqu'aux prolongations et aux tirs au but. Le pays entier vit la meme seconde, colle a l'ecran.",
    fact: "Le 18 décembre 2022, l'équipe de France dispute la finale de la Coupe du monde au Qatar face à l'Argentine.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Coupe_du_monde_de_football_2022", authority: false }
    ],
    tags: ["football", "mondial", "2022", "tele"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2024-ceremonie-ouverture-jo-paris",
    countryQid: "Q142", lang: "fr",
    gestureKey: "suivre-la-ceremonie-douverture-des-jo-a-la-tele",
    gestureLabel: "suivre la cérémonie d'ouverture des Jeux olympiques à Paris",
    theme: "loisirs", gestureRoot: "jeux_olympiques_paris",
    editorialScore: 90,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "2024-07-26", ruptureYear: 2024, datePrecision: "day",
    placeName: "Paris — Seine et Trocadéro", placeType: "city", placeQid: "Q90",
    triggerLabel: "Cérémonie d'ouverture des Jeux olympiques d'été de Paris 2024",
    triggerType: "public_rollout",
    beforeState: "Avant juillet 2024, les Jeux à Paris restent surtout une promesse d'affiches et de chantiers.",
    afterState: "Après la cérémonie sur la Seine, le pays bascule dans trois semaines d'épreuves vécues comme un rendez-vous national.",
    gestureChanged: "Tu peux suivre un défilé sur l'eau, reconnaître les monuments et partager le même direct que des millions de foyers.",
    materialAnchor: "Écran, flottille sur la Seine et anneaux olympiques",
    sceneText: "26 juillet 2024, Paris. La Seine devient scene, les monuments servent de decor, le pays se regarde en direct. Les Jeux a la maison prennent enfin leur forme spectaculaire.",
    fact: "Le 26 juillet 2024, la cérémonie d'ouverture des Jeux olympiques de Paris se déroule le long de la Seine.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/C%C3%A9r%C3%A9monie_d%27ouverture_des_Jeux_olympiques_d%27%C3%A9t%C3%A9_de_2024", authority: false }
    ],
    tags: ["jo", "paris", "2024", "ceremonie"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2025-reforme-budgetaire-europeenne",
    countryQid: "Q142", lang: "fr",
    gestureKey: "lire-les-debats-sur-le-budget-europeen",
    gestureLabel: "suivre les débats sur le budget et la discipline européenne au quotidien",
    theme: "argent", gestureRoot: "budget_europeen",
    editorialScore: 72,
    category: "public_space", direction: "possible_to_impossible",
    ruptureDate: "2025-01-01", ruptureYear: 2025, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Actualité budgétaire et européenne en 2025",
    triggerType: "law",
    beforeState: "Avant 2025, les arbitrages fiscaux et européens semblent encore lointains pour une partie du public.",
    afterState: "En 2025, les titres sur le budget et l'Europe deviennent un bruit de fond médiatique permanent.",
    gestureChanged: "Tu peux ouvrir le fil d'actualité et tomber chaque jour sur un nouveau chiffre ou une nouvelle négociation.",
    materialAnchor: "Smartphone, fil d'actualité et graphiques budgétaires",
    sceneText: "2025, dans les transports et les salons. Le budget de l'Etat et les regles europeennes reviennent dans les conversations. Les chiffres publics deviennent un fond sonore politique.",
    fact: "En 2025, les débats sur le budget de l'État et les règles budgétaires européennes occupent une place importante dans l'actualité politique française.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/2025_en_France", authority: false }
    ],
    tags: ["budget", "europe", "2025", "politique"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2026-tour-de-france-depart",
    countryQid: "Q142", lang: "fr",
    gestureKey: "suivre-le-grand-depart-du-tour",
    gestureLabel: "suivre le grand départ du Tour de France à la télé ou au bord de la route",
    theme: "loisirs", gestureRoot: "tour_de_france",
    editorialScore: 78,
    category: "transport", direction: "impossible_to_possible",
    ruptureDate: "2026-06-27", ruptureYear: 2026, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Grand départ du Tour de France 2026",
    triggerType: "public_rollout",
    beforeState: "Avant l'été 2026, le calendrier sportif national n'a pas encore basculé vers la grande boucle.",
    afterState: "Après le départ, le Tour redevient le rituel estival partagé entre routes, écrans et ravitaillements télévisés.",
    gestureChanged: "Tu peux suivre les échappées, les chutes et les sprints comme un rendez-vous quotidien pendant trois semaines.",
    materialAnchor: "Vélo, maillot jaune et caravane publicitaire",
    sceneText: "Juin 2026, depart du Tour. Les bordures de route se garnissent, les téles passent au rythme des etapes. Le cyclisme redevient le fond sonore des soirees d'ete.",
    fact: "Le Tour de France 2026 suit la tradition d'un grand départ en juin ou juillet, avec un parcours annoncé par l'organisation.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Tour_de_France", authority: false }
    ],
    tags: ["tour-de-france", "cyclisme", "2026", "sport"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2011-sondage-social-facebook",
    countryQid: "Q142", lang: "fr",
    gestureKey: "partager-une-opinion-sur-les-reseaux-sociaux",
    gestureLabel: "partager une opinion publiquement sur les réseaux sociaux",
    theme: "communication", gestureRoot: "reseaux_sociaux_opinion",
    editorialScore: 84,
    category: "media", direction: "impossible_to_possible",
    ruptureDate: "2011-01-01", ruptureYear: 2011, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Généralisation des réseaux sociaux en France — Facebook, Twitter, YouTube",
    triggerType: "public_rollout",
    beforeState: "Avant 2011, exprimer une opinion publiquement nécessite un journal, une lettre au courrier des lecteurs ou un blog.",
    afterState: "À partir de 2011, Facebook et Twitter sont utilisés par des millions de Français pour partager opinions, photos et liens.",
    gestureChanged: "Tu peux écrire en trente secondes un avis que des milliers de personnes liront — sans avoir besoin d'un journal.",
    materialAnchor: "Fil d'actualité Facebook, bouton «J'aime» et smartphone",
    sceneText: "2011, smartphone en main. Le statut est posté. Les «j'aime» arrivent. Les amis commentent, partagent, relaient. Facebook et Twitter font de chaque Français un éditeur potentiel. La frontière entre public et privé bascule.",
    fact: "En 2011, Facebook dépasse 20 millions d'utilisateurs en France et transforme les pratiques d'expression publique.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Facebook_en_France", authority: false }
    ],
    tags: ["reseaux-sociaux", "facebook", "numerique", "expression"],
    quality: { strictPlace: false, strictDate: false, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2015-attentats-charlie-hebdo-vivre",
    countryQid: "Q142", lang: "fr",
    gestureKey: "manifester-je-suis-charlie-apres-les-attentats",
    gestureLabel: "manifester «Je suis Charlie» après les attentats de janvier 2015",
    theme: "administration", gestureRoot: "charlie_hebdo_marche",
    editorialScore: 92,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "2015-01-11", ruptureYear: 2015, datePrecision: "day",
    placeName: "Place de la République, Paris et villes de France", placeType: "site", placeQid: null,
    triggerLabel: "Marche républicaine après les attentats de Charlie Hebdo",
    triggerType: "public_rollout",
    beforeState: "Avant le 7 janvier 2015, la liberté d'expression n'a pas fait l'objet d'une mobilisation citoyenne de cette ampleur en France depuis des décennies.",
    afterState: "Le 11 janvier 2015, près de 4 millions de Français défilent — la plus grande manifestation de l'histoire de France.",
    gestureChanged: "Tu peux marcher dans la rue en tenant un crayon ou une pancarte «Je suis Charlie» parmi des millions d'autres.",
    materialAnchor: "Crayon, pancarte «Je suis Charlie» et foule dans la rue",
    sceneText: "11 janvier 2015, Paris. Quatre millions de personnes dans les rues. Le crayon brandi en hommage aux dessinateurs assassinés. «Je suis Charlie» — un slogan, une marche, un moment où la France entière s'est levée.",
    fact: "Le 11 janvier 2015, près de 4 millions de Français défilent dans la plus grande marche de l'histoire de France, après les attentats de Charlie Hebdo.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Marche_r%C3%A9publicaine_du_11_janvier_2015", authority: false }
    ],
    tags: ["charlie-hebdo", "liberte-expression", "attentats", "manifestation"],
    quality: { strictPlace: true, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
  {
    id: "fr-2016-nuit-debout",
    countryQid: "Q142", lang: "fr",
    gestureKey: "participer-a-nuit-debout-place-de-la-republique",
    gestureLabel: "participer à Nuit Debout place de la République",
    theme: "administration", gestureRoot: "nuit_debout",
    editorialScore: 80,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "2016-03-31", ruptureYear: 2016, datePrecision: "day",
    placeName: "Place de la République, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Naissance du mouvement Nuit Debout place de la République",
    triggerType: "public_rollout",
    beforeState: "Avant mars 2016, la contestation contre la loi El Khomri s'exprime dans des manifestations syndicales classiques.",
    afterState: "À partir du 31 mars 2016, Nuit Debout invente un nouveau format de démocratie participative informelle sur la place publique.",
    gestureChanged: "Tu peux rejoindre chaque soir place de la République des centaines de personnes qui débattent à voix haute de politique, de société, d'avenir.",
    materialAnchor: "Mégaphone, thermos de café et pavés de la place de la République",
    sceneText: "31 mars 2016, place de la République. La manifestation s'est terminée mais personne ne rentre chez soi. On débat, on s'organise, on parle. Nuit Debout invente son format — et dure des semaines.",
    fact: "Le 31 mars 2016, Nuit Debout s'installe place de la République à Paris, inventant un nouveau format de contestation citoyenne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Nuit_debout", authority: false }
    ],
    tags: ["nuit-debout", "contestation", "paris", "politique"],
    quality: { strictPlace: true, strictDate: true, dailyLife: false, sourceCount: 1 }
  },
  {
    id: "fr-2018-gilets-jaunes",
    countryQid: "Q142", lang: "fr",
    gestureKey: "rejoindre-un-rond-point-gilets-jaunes",
    gestureLabel: "rejoindre un rond-point avec un gilet jaune",
    theme: "administration", gestureRoot: "gilets_jaunes",
    editorialScore: 88,
    category: "public_space", direction: "impossible_to_possible",
    ruptureDate: "2018-11-17", ruptureYear: 2018, datePrecision: "day",
    placeName: "Rond-points de France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Premier samedi de mobilisation des Gilets jaunes",
    triggerType: "public_rollout",
    beforeState: "Avant novembre 2018, la contestation sociale en France est organisée par des syndicats et s'exprime dans des défilés classiques.",
    afterState: "Après le 17 novembre 2018, les Gilets jaunes inventent un mode d'action décentralisé : bloquer les ronds-points.",
    gestureChanged: "Tu peux enfiler un gilet jaune et rejoindre un rond-point local — sans syndicat, sans organisation, juste toi et tes voisins.",
    materialAnchor: "Gilet jaune fluorescent, brasero et panneau de rond-point",
    sceneText: "17 novembre 2018, ronds-points de France. Des centaines de milliers de personnes en gilet jaune bloquent les accès. Ni syndicat ni parti — juste des gens ordinaires qui étouffent face à la hausse du carburant et des prix. Un nouveau type de révolte naît.",
    fact: "Le 17 novembre 2018, le mouvement des Gilets jaunes mobilise plus de 280 000 personnes sur les ronds-points de France — mouvement social inédit.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Mouvement_des_Gilets_jaunes", authority: false }
    ],
    tags: ["gilets-jaunes", "contestation", "rond-point", "social"],
    quality: { strictPlace: false, strictDate: true, dailyLife: true, sourceCount: 1 }
  },
];
