import type { InventionEntry } from "../../../types";

export const FR_INVENTION_BACKFILL_1826_1899: InventionEntry[] = [
  {
    id: "fr-1827-photographie-niepce",
    countryQid: "Q142", lang: "fr",
    itemKey: "fixer-une-image-sur-plaque-niepce",
    itemLabel: "fixer une image du monde réel sur une plaque sensible",
    theme: "communication", gestureRoot: "photographie",
    editorialScore: 97,
    objectType: "device", category: "device",
    releaseDate: "1827", releaseYear: 1827, datePrecision: "year",
    placeName: "Chalon-sur-Saône", placeType: "city", placeQid: "Q170595",
    triggerLabel: "Nicéphore Niépce réalise la première photographie permanente",
    beforeState: "Avant 1827, aucun procédé ne permet de fixer durablement l'image projetée par une chambre noire.",
    afterState: "Après 1827, l'idée de capturer le réel sur un support matériel cesse d'être un rêve et devient une technique en développement.",
    objectChanged: "Tu peux imaginer qu'un objet ou un paysage peut être fixé sur une surface, en dehors de tout dessin à la main.",
    materialAnchor: "Plaque d'étain enduite de bitume de Judée, chambre noire",
    sceneText: "1827, Chalon-sur-Saône. Niépce pose sa plaque enduite de bitume à la fenêtre et attend des heures. Quand il la retire, la cour intérieure est là, immobile et vraie, gravée dans la matière. Pour la première fois, la lumière a signé elle-même.",
    fact: "En 1827, Joseph Nicéphore Niépce réalise la première photographie permanente connue, 'La Cour du domaine du Gras', avec une exposition de plusieurs heures.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Nic%C3%A9phore_Ni%C3%A9pce", authority: false },
      { label: "Musée Nicéphore Niépce", url: "https://www.museeniepce.com/", authority: true }
    ],
    tags: ["photographie", "niepce", "image", "lumiere"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1829-braille",
    countryQid: "Q142", lang: "fr",
    itemKey: "lire-au-toucher-avec-lalphabet-braille",
    itemLabel: "lire des textes au toucher grâce à l'alphabet Braille",
    theme: "communication", gestureRoot: "braille",
    editorialScore: 94,
    objectType: "media", category: "media",
    releaseDate: "1829", releaseYear: 1829, datePrecision: "year",
    placeName: "Institution nationale des jeunes aveugles, Paris", placeType: "institution", placeQid: null,
    triggerLabel: "Louis Braille publie la première méthode de lecture et écriture pour aveugles",
    beforeState: "Avant 1829, les aveugles n'ont pas de système d'écriture tactile cohérent pour lire de façon autonome.",
    afterState: "Après 1829, un alphabet de points en relief permet pour la première fois aux aveugles de lire et écrire de façon indépendante.",
    objectChanged: "Tu peux toucher des points sur une page et en tirer des lettres, des mots, des phrases — sans voir.",
    materialAnchor: "Planchette à poindre, papier épais, points en relief",
    sceneText: "1829, Paris. Louis Braille, aveugle depuis l'enfance, dispose les six points sur la page. Ses doigts glissent sur la surface et déchiffrent ce que les yeux ne peuvent pas atteindre. Une langue nouvelle naît dans les mains.",
    fact: "En 1829, Louis Braille, élève puis professeur à l'Institution nationale des jeunes aveugles de Paris, publie la première version de son système d'écriture en points en relief.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Louis_Braille", authority: false },
      { label: "Institut National des Jeunes Aveugles", url: "https://www.inja.fr/", authority: true }
    ],
    tags: ["braille", "handicap", "lecture", "paris"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1832-chemin-de-fer-paris-saint-germain",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-le-train-entre-paris-et-la-banlieue",
    itemLabel: "prendre le train entre Paris et la banlieue",
    theme: "transport", gestureRoot: "chemin_de_fer",
    editorialScore: 93,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1837-08-26", releaseYear: 1837, datePrecision: "day",
    placeName: "Paris – Saint-Germain-en-Laye", placeType: "site", placeQid: null,
    triggerLabel: "Ouverture de la ligne Paris–Saint-Germain-en-Laye, première ligne de passagers",
    beforeState: "Avant août 1837, aucune ligne de chemin de fer de passagers régulière ne relie Paris à sa région.",
    afterState: "Après août 1837, le train devient un mode de déplacement de masse autour de Paris, inaugurant l'ère ferroviaire française.",
    objectChanged: "Tu peux monter dans un wagon tiré par une locomotive à vapeur et arriver à Saint-Germain en moins d'une heure.",
    materialAnchor: "Wagon de bois, locomotive à vapeur, billet de première ou deuxième classe",
    sceneText: "26 août 1837, Paris. Le quai vibre sous les pieds avant même que la machine n'arrive. La locomotive crache sa vapeur, les voyageurs s'installent, et la ville recule derrière les vitres à une vitesse que personne n'avait encore connue entre ces deux points.",
    fact: "Le 26 août 1837 ouvre la première ligne ferroviaire de passagers en Île-de-France, entre Paris (Saint-Lazare) et Saint-Germain-en-Laye.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Ligne_de_Paris-Saint-Lazare_%C3%A0_Saint-Germain-en-Laye", authority: false },
      { label: "Archives SNCF", url: "https://www.sncf.com/fr/groupe/histoire", authority: true }
    ],
    tags: ["train", "chemin-de-fer", "paris", "banlieue"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1839-daguerreotype",
    countryQid: "Q142", lang: "fr",
    itemKey: "faire-son-portrait-au-daguerreotype",
    itemLabel: "faire réaliser son portrait photographique au daguerréotype",
    theme: "communication", gestureRoot: "daguerreotype",
    editorialScore: 95,
    objectType: "device", category: "media",
    releaseDate: "1839-08-19", releaseYear: 1839, datePrecision: "day",
    placeName: "Académie des sciences, Paris", placeType: "institution", placeQid: "Q161304",
    triggerLabel: "L'État français rachète le brevet du daguerréotype et le rend libre",
    beforeState: "Avant le 19 août 1839, aucune technique photographique n'est accessible au public ni diffusable librement.",
    afterState: "Après le 19 août 1839, le daguerréotype se répand rapidement dans les ateliers parisiens : tout le monde peut faire faire son portrait.",
    objectChanged: "Tu peux poser devant un appareil et obtenir ton image exacte sur une plaque d'argent — sans peintre.",
    materialAnchor: "Plaque argentée, chambre noire, produits chimiques de fixation",
    sceneText: "19 août 1839, Paris. Daguerre présente son procédé à l'Académie des sciences. Le lendemain, les boutiques d'optique sont prises d'assaut. La foule veut voir, toucher, posséder ce miroir qui ne ment pas et ne s'efface pas.",
    fact: "Le 19 août 1839, lors d'une séance conjointe à l'Académie des sciences, le daguerréotype est rendu public par l'État français, déclenchant un enthousiasme mondial immédiat.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Daguerr%C3%A9otype", authority: false },
      { label: "BnF", url: "https://expositions.bnf.fr/photo/arret/01-3.htm", authority: true }
    ],
    tags: ["daguerreotype", "photographie", "paris", "daguerre"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1844-telegraph-electrique-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "envoyer-un-message-par-telegraphe-electrique",
    itemLabel: "envoyer un message instantané par télégraphe électrique",
    theme: "communication", gestureRoot: "telegraphe",
    editorialScore: 88,
    objectType: "infrastructure", category: "network",
    releaseDate: "1845", releaseYear: 1845, datePrecision: "year",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Déploiement du réseau télégraphique électrique en France",
    beforeState: "Avant 1845, les messages longue distance en France transitent par le télégraphe optique de Chappe, lent et dépendant de la visibilité.",
    afterState: "Après 1845, le télégraphe électrique permet d'envoyer des messages à travers la France en quelques minutes.",
    objectChanged: "Tu peux rédiger un message court et le faire transmettre à l'autre bout du pays presque instantanément.",
    materialAnchor: "Fil de cuivre, clé morse, ruban de papier perforé",
    sceneText: "Paris, 1845. Le bureau de poste accepte désormais les dépêches électriques. Le message part sur le fil de cuivre, traverse la campagne à la vitesse de l'éclair, et arrive à destination en quelques minutes. La distance vient de changer de nature.",
    fact: "Dans les années 1845-1850, la France déploie un réseau télégraphique électrique, remplaçant progressivement le télégraphe optique de Chappe inauguré sous la Révolution.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9graphe_%C3%A9lectrique", authority: false },
      { label: "Musée des Arts et Métiers", url: "https://www.arts-et-metiers.net/", authority: true }
    ],
    tags: ["telegraphe", "communication", "paris", "reseau"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1848-presse-a-un-sou",
    countryQid: "Q142", lang: "fr",
    itemKey: "acheter-un-journal-bon-marche",
    itemLabel: "acheter un journal accessible à un sou dans la rue",
    theme: "communication", gestureRoot: "presse_populaire",
    editorialScore: 85,
    objectType: "media", category: "media",
    releaseDate: "1836", releaseYear: 1836, datePrecision: "year",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Émile de Girardin fonde La Presse, premier grand journal populaire financé par la publicité",
    beforeState: "Avant 1836, la presse française est chère, réservée aux classes aisées, distribuée par abonnement annuel coûteux.",
    afterState: "Après 1836, un journal bon marché financé par la publicité peut être vendu au numéro dans la rue pour quelques sous.",
    objectChanged: "Tu peux acheter un journal dans la rue pour un prix modique et y lire les nouvelles du jour, des feuilletons et des annonces.",
    materialAnchor: "Journal plié, vendeur de rue, monnaie de quelques sous",
    sceneText: "Paris, 1836. Le crieur agite le journal dans la rue. Le prix sur la manchette ne dépasse plus ce qu'un ouvrier peut sortir de sa poche. La presse cesse d'être un privilège et commence à devenir une habitude populaire.",
    fact: "En 1836, Émile de Girardin lance La Presse à un prix réduit grâce à la publicité, inventant le modèle de la presse populaire moderne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/%C3%89mile_de_Girardin", authority: false },
      { label: "BnF Gallica", url: "https://gallica.bnf.fr/ark:/12148/cb32779904s/date", authority: true }
    ],
    tags: ["presse", "journal", "paris", "publicite"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1851-cable-sous-marin-dover-calais",
    countryQid: "Q142", lang: "fr",
    itemKey: "communiquer-par-cable-sous-marin-france-angleterre",
    itemLabel: "communiquer instantanément entre la France et l'Angleterre par câble sous-marin",
    theme: "communication", gestureRoot: "cable_sous_marin",
    editorialScore: 86,
    objectType: "infrastructure", category: "network",
    releaseDate: "1851-11-13", releaseYear: 1851, datePrecision: "day",
    placeName: "Calais – Douvres", placeType: "site", placeQid: null,
    triggerLabel: "Pose du premier câble télégraphique sous-marin permanent entre Calais et Douvres",
    beforeState: "Avant novembre 1851, toute communication entre la France et l'Angleterre doit passer par des bateaux ou des signaux optiques.",
    afterState: "Après novembre 1851, Paris et Londres peuvent s'échanger des messages télégraphiques en quelques minutes.",
    objectChanged: "Tu peux envoyer une dépêche à Londres depuis Paris et recevoir une réponse le même jour.",
    materialAnchor: "Câble blindé, gutta-percha, station télégraphique côtière",
    sceneText: "13 novembre 1851, Calais. Le câble glisse dans la Manche depuis le navire câblier. Le lendemain, Paris et Londres parlent pour la première fois sans avoir à attendre qu'un bateau traverse le détroit. La mer devient un corridor électrique.",
    fact: "Le 13 novembre 1851, le premier câble télégraphique sous-marin permanent entre Calais et Douvres est mis en service, unissant électriquement la France au Royaume-Uni.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/C%C3%A2ble_sous-marin", authority: false },
      { label: "Musée des télécommunications", url: "https://www.retronews.fr/", authority: false }
    ],
    tags: ["cable", "telegraphe", "calais", "angleterre"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1855-acier-bessemer",
    countryQid: "Q142", lang: "fr",
    itemKey: "fabriquer-de-lacier-en-masse-par-convertisseur",
    itemLabel: "fabriquer de l'acier en grande quantité grâce au procédé Bessemer",
    theme: "travail", gestureRoot: "acier_bessemer",
    editorialScore: 84,
    objectType: "infrastructure", category: "device",
    releaseDate: "1856", releaseYear: 1856, datePrecision: "year",
    placeName: "Usines sidérurgiques françaises", placeType: "site", placeQid: null,
    triggerLabel: "Adoption du convertisseur Bessemer dans les aciéries françaises",
    beforeState: "Avant 1856, la production d'acier est lente, coûteuse et limitée à de petites quantités.",
    afterState: "Après 1856, le procédé Bessemer permet de produire de grandes quantités d'acier en quelques minutes, révolutionnant la construction.",
    objectChanged: "Tu peux voir des rails, des ponts et des structures métalliques se multiplier grâce à un acier bon marché et disponible en masse.",
    materialAnchor: "Convertisseur en poire, lingots d'acier, rail de chemin de fer",
    sceneText: "1856, dans une usine sidérurgique. Le convertisseur en poire se renverse et crache des flammes. En quinze minutes, la fonte devient acier. Ce qui prenait des jours et des journées entières d'attention tient maintenant dans un geste mécanique.",
    fact: "À partir de 1856, le procédé Bessemer est adopté dans les aciéries françaises et européennes, permettant la production industrielle d'acier bon marché essentiel aux chemins de fer et à l'architecture métallique.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Proc%C3%A9d%C3%A9_Bessemer", authority: false },
      { label: "Encyclopædia Universalis", url: "https://www.universalis.fr/encyclopedie/bessemer/", authority: true }
    ],
    tags: ["acier", "bessemer", "industrie", "siderurgie"],
    quality: { strictPlace: false, strictDate: false, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1863-metro-chemin-de-fer-urbain",
    countryQid: "Q142", lang: "fr",
    itemKey: "se-deplacer-en-train-dans-paris",
    itemLabel: "se déplacer rapidement en train à l'intérieur de Paris",
    theme: "transport", gestureRoot: "metro_paris",
    editorialScore: 87,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1900-07-19", releaseYear: 1900, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Ouverture de la première ligne du métro parisien",
    beforeState: "Avant 1900, se déplacer vite dans Paris dépend des omnibus à chevaux ou du chemin de fer de ceinture.",
    afterState: "Après le 19 juillet 1900, le métro souterrain offre aux Parisiens un moyen de transport rapide, bon marché et indépendant du trafic de surface.",
    objectChanged: "Tu peux descendre sous terre, monter dans une rame et traverser Paris en quelques minutes sans dépendre des embouteillages.",
    materialAnchor: "Ticket de métro, bouche de station, rame sur rail",
    sceneText: "19 juillet 1900, Paris. La bouche de métro s'ouvre dans le trottoir comme une invitation. En bas, l'air est différent, l'éclairage artificiel, le bruit sourd et régulier. La ville a maintenant un sous-sol qui court plus vite que ses rues.",
    fact: "Le 19 juillet 1900, la première ligne du métropolitain parisien est inaugurée entre Vincennes et Maillot, à l'occasion de l'Exposition universelle.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/M%C3%A9tro_de_Paris", authority: false },
      { label: "RATP patrimoine", url: "https://www.ratp.fr/groupe-ratp/ratp-et-vous/histoire", authority: true }
    ],
    tags: ["metro", "paris", "transport", "souterrain"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1869-canal-de-suez",
    countryQid: "Q142", lang: "fr",
    itemKey: "traverser-la-mediterranee-vers-lasie-sans-contourner-lafrique",
    itemLabel: "naviguer de la Méditerranée vers l'Asie sans contourner l'Afrique",
    theme: "transport", gestureRoot: "canal_suez",
    editorialScore: 89,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1869-11-17", releaseYear: 1869, datePrecision: "day",
    placeName: "Canal de Suez", placeType: "site", placeQid: "Q171053",
    triggerLabel: "Inauguration du canal de Suez, grand projet français de Ferdinand de Lesseps",
    beforeState: "Avant novembre 1869, tout navire allant d'Europe vers l'Asie devait contourner l'Afrique, un détour de plusieurs semaines.",
    afterState: "Après novembre 1869, la route maritime entre la Méditerranée et l'océan Indien est raccourcie de plusieurs milliers de kilomètres.",
    objectChanged: "Tu peux embarquer à Marseille et atteindre l'Inde ou la Chine bien plus vite qu'auparavant.",
    materialAnchor: "Navire à vapeur, canal à double sens, Lesseps en capitaine de cérémonie",
    sceneText: "17 novembre 1869, canal de Suez. Le convoi inaugural entre dans la tranchée creusée dans le sable égyptien. À bord des navires, des souverains et des ambassadeurs regardent défiler les deux rives d'un continent tranché. L'entreprise française vient de relier deux mers.",
    fact: "Le 17 novembre 1869, le canal de Suez est inauguré sous l'égide de Ferdinand de Lesseps, réduisant considérablement la route maritime entre l'Europe et l'Asie.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Canal_de_Suez", authority: false },
      { label: "Suez Canal Authority", url: "https://www.suezcanal.gov.eg/", authority: true }
    ],
    tags: ["suez", "canal", "lesseps", "navigation"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1874-impressionnisme-premiere-expo",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-une-peinture-impressionniste-a-paris",
    itemLabel: "voir une peinture impressionniste à Paris",
    theme: "loisirs", gestureRoot: "impressionnisme",
    editorialScore: 91,
    objectType: "media", category: "media",
    releaseDate: "1874-04-15", releaseYear: 1874, datePrecision: "day",
    placeName: "Atelier Nadar, boulevard des Capucines, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Première exposition des peintres impressionnistes chez Nadar",
    beforeState: "Avant avril 1874, les peintres refusés au Salon officiel n'ont pas d'espace public pour montrer leur travail différent.",
    afterState: "Après avril 1874, l'impressionnisme a un nom et un lieu d'exposition indépendant du Salon, ouvrant une nouvelle ère picturale.",
    objectChanged: "Tu peux voir des tableaux qui ne cherchent pas la perfection académique mais captent la lumière, le mouvement et l'instant.",
    materialAnchor: "Tableau à larges coups de pinceau, lumière naturelle, galerie libre",
    sceneText: "15 avril 1874, boulevard des Capucines, Paris. Dans l'atelier de Nadar, les toiles accrochées ne ressemblent à rien de ce que le Salon reconnaîtrait. Les coups de pinceau sont visibles, la lumière vibre, les sujets sont ordinaires. Le public ricane, puis revient.",
    fact: "Le 15 avril 1874, Monet, Renoir, Degas, Pissarro et leurs associés exposent pour la première fois ensemble chez le photographe Nadar, donnant naissance au mouvement impressionniste.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Impressionnisme", authority: false },
      { label: "Musée d'Orsay", url: "https://www.musee-orsay.fr/fr/oeuvres/impression-soleil-levant-78645", authority: true }
    ],
    tags: ["impressionnisme", "paris", "peinture", "monet"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1877-telephone-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "telephoner-pour-la-premiere-fois",
    itemLabel: "parler à voix à distance via le téléphone",
    theme: "communication", gestureRoot: "telephone",
    editorialScore: 93,
    objectType: "device", category: "network",
    releaseDate: "1879", releaseYear: 1879, datePrecision: "year",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Premières installations téléphoniques commerciales en France",
    beforeState: "Avant 1879, la communication à distance en France se fait uniquement par télégraphe ou courrier.",
    afterState: "Après 1879, les premiers abonnés au téléphone à Paris peuvent se parler en temps réel à travers la ville.",
    objectChanged: "Tu peux décrocher un appareil, demander une communication, et entendre la voix de quelqu'un à l'autre bout de la ligne.",
    materialAnchor: "Écouteur, magnéto à manivelle, fil de cuivre, central téléphonique",
    sceneText: "1879, Paris. L'appareil accroché au mur ressemble encore à une curiosité scientifique. Mais quand on décroche et qu'une voix humaine sort du boitier, pas du tout mécanique, pas enregistrée — celle de quelqu'un à l'autre bout de la ville — quelque chose change dans l'idée même de la distance.",
    fact: "À partir de 1879, les premières lignes téléphoniques commerciales sont installées à Paris, faisant de la France l'un des premiers pays à adopter le téléphone à grande échelle.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Histoire_du_t%C3%A9l%C3%A9phone_en_France", authority: false },
      { label: "Musée des Arts et Métiers", url: "https://www.arts-et-metiers.net/", authority: true }
    ],
    tags: ["telephone", "paris", "communication", "reseau"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1881-electricite-lumiere-paris",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-les-rues-de-paris-eclairees-a-lelectricite",
    itemLabel: "voir les rues de Paris éclairées à l'électricité",
    theme: "communication", gestureRoot: "electricite_publique",
    editorialScore: 92,
    objectType: "infrastructure", category: "network",
    releaseDate: "1878-08-01", releaseYear: 1878, datePrecision: "month",
    placeName: "Avenue de l'Opéra, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Premier éclairage public électrique permanent à Paris",
    beforeState: "Avant 1878, l'éclairage public de Paris repose sur le gaz, qui donne une lumière jaune et vacillante.",
    afterState: "Après 1878, des arcs électriques projettent une lumière blanche et vive dans les rues, transformant la nuit urbaine.",
    objectChanged: "Tu peux te promener la nuit dans certaines rues parisiennes sous un éclairage électrique continu et puissant.",
    materialAnchor: "Lampe à arc électrique, colonne d'éclairage, centrale électrique",
    sceneText: "Paris, 1878. L'avenue de l'Opéra s'illumine d'une lumière blanche qu'on n'avait jamais vue dans une rue. Les becs de gaz jaunes semblent soudain appartenir à une autre époque. La ville commence à changer de couleur la nuit.",
    fact: "En 1878, lors de l'Exposition universelle, Paris inaugure le premier éclairage public permanent à l'électricité sur l'avenue de l'Opéra, avec des lampes à arc Yablochkov.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/%C3%89clairage_%C3%A0_arc_%C3%A9lectrique", authority: false },
      { label: "EDF archives", url: "https://www.edf.fr/groupe-edf/esprit-de-service/archives", authority: false }
    ],
    tags: ["electricite", "paris", "eclairage", "nuit"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1885-vaccin-pasteur-rage",
    countryQid: "Q142", lang: "fr",
    itemKey: "etre-vaccine-contre-la-rage-par-pasteur",
    itemLabel: "être vacciné contre une maladie mortelle grâce au vaccin de Pasteur",
    theme: "santé", gestureRoot: "vaccin_pasteur",
    editorialScore: 98,
    objectType: "service", category: "service",
    releaseDate: "1885-07-06", releaseYear: 1885, datePrecision: "day",
    placeName: "Laboratoire de Pasteur, Paris", placeType: "institution", placeQid: null,
    triggerLabel: "Louis Pasteur vaccine avec succès le premier humain contre la rage",
    beforeState: "Avant le 6 juillet 1885, une morsure de chien enragé signifiait une mort certaine et atroce.",
    afterState: "Après le 6 juillet 1885, une série d'injections peut prévenir la mort par rage après une morsure.",
    objectChanged: "Tu peux recevoir une série de piqûres après une morsure infectée et survivre à une maladie jusque-là fatale.",
    materialAnchor: "Seringue de verre, fiole de vaccin, carnet de vaccination",
    sceneText: "6 juillet 1885, laboratoire de Pasteur, Paris. Joseph Meister, neuf ans, a été mordu par un chien enragé. Pasteur hésite, puis injecte. Deux semaines de traitement, et l'enfant reste en vie. Pour la première fois, la science a répondu à la rage.",
    fact: "Le 6 juillet 1885, Louis Pasteur administre pour la première fois un vaccin antirabique à un être humain, le jeune Joseph Meister, sauvant sa vie et ouvrant l'ère de la vaccinologie moderne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Louis_Pasteur", authority: false },
      { label: "Institut Pasteur", url: "https://www.pasteur.fr/fr/institut-pasteur/histoire-de-linstitut-pasteur", authority: true }
    ],
    tags: ["pasteur", "vaccin", "rage", "paris"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1889-tour-eiffel",
    countryQid: "Q142", lang: "fr",
    itemKey: "monter-sur-la-tour-eiffel",
    itemLabel: "monter sur la tour Eiffel, symbole de la modernité industrielle",
    theme: "loisirs", gestureRoot: "tour_eiffel",
    editorialScore: 97,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1889-03-31", releaseYear: 1889, datePrecision: "day",
    placeName: "Champ-de-Mars, Paris", placeType: "site", placeQid: "Q243",
    triggerLabel: "Inauguration de la tour Eiffel pour l'Exposition universelle",
    beforeState: "Avant mars 1889, aucune structure métallique aussi haute n'existe au monde, et beaucoup la jugent laide.",
    afterState: "Après mars 1889, la tour Eiffel devient le symbole mondial de Paris et de l'ingénierie française.",
    objectChanged: "Tu peux monter dans des ascenseurs mécaniques jusqu'au sommet d'une tour de fer et voir Paris à des centaines de mètres sous tes pieds.",
    materialAnchor: "Poutrelle de fer, ascenseur hydraulique, billet d'exposition",
    sceneText: "31 mars 1889, Champ-de-Mars. La tour est là, à 300 mètres, là où ses détracteurs annonçaient une honte. L'ascenseur monte par saccades. En haut, Paris est entier, compact, soumis. La ville ne ressemblera plus jamais à elle-même vue d'en bas.",
    fact: "Le 31 mars 1889, Gustave Eiffel inaugure sa tour, alors la plus haute structure du monde, conçue pour l'Exposition universelle du centenaire de la Révolution française.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Tour_Eiffel", authority: false },
      { label: "Tour Eiffel officiel", url: "https://www.toureiffel.paris/fr/la-tour-eiffel/son-histoire", authority: true }
    ],
    tags: ["tour-eiffel", "paris", "exposition", "eiffel"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1895-cinema-lumieres",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-une-projection-cinematographique",
    itemLabel: "voir une projection de cinéma dans une salle",
    theme: "loisirs", gestureRoot: "cinema_lumieres",
    editorialScore: 99,
    objectType: "media", category: "media",
    releaseDate: "1895-12-28", releaseYear: 1895, datePrecision: "day",
    placeName: "Salon Indien du Grand Café, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Première projection publique et payante du cinématographe Lumière",
    beforeState: "Avant le 28 décembre 1895, aucune image en mouvement n'est projetée sur écran devant un public payant.",
    afterState: "Après le 28 décembre 1895, le cinéma existe comme divertissement public, et Paris devient la capitale mondiale du septième art naissant.",
    objectChanged: "Tu peux t'asseoir dans une salle obscure et regarder des images en mouvement projetées sur un écran blanc.",
    materialAnchor: "Cinématographe, écran blanc, salle obscure, billets d'entrée",
    sceneText: "28 décembre 1895, boulevard des Capucines, Paris. Le sous-sol du Grand Café s'obscurcit. Sur l'écran, un train entre en gare. Des spectateurs reculent. Ils savent que c'est une image mais quelque chose dans leur corps ne le croit pas encore.",
    fact: "Le 28 décembre 1895, Auguste et Louis Lumière organisent la première projection cinématographique publique et payante au Salon Indien du Grand Café, à Paris.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Auguste_et_Louis_Lumi%C3%A8re", authority: false },
      { label: "Institut Lumière", url: "https://www.institut-lumiere.org/", authority: true }
    ],
    tags: ["cinema", "lumieres", "paris", "projection"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1898-decouverte-radium-curie",
    countryQid: "Q142", lang: "fr",
    itemKey: "apprendre-la-decouverte-du-radium-par-les-curie",
    itemLabel: "apprendre la découverte du radium par Marie et Pierre Curie",
    theme: "santé", gestureRoot: "radium_curie",
    editorialScore: 96,
    objectType: "device", category: "device",
    releaseDate: "1898-12-26", releaseYear: 1898, datePrecision: "day",
    placeName: "École de physique et chimie, Paris", placeType: "institution", placeQid: null,
    triggerLabel: "Marie et Pierre Curie annoncent la découverte du radium",
    beforeState: "Avant décembre 1898, la radioactivité est un phénomène récent mais les éléments qui la produisent restent inconnus.",
    afterState: "Après décembre 1898, le radium ouvre la voie à la physique nucléaire, à la médecine par rayonnement et à une nouvelle conception de la matière.",
    objectChanged: "Tu peux lire dans les journaux qu'une substance invisible émet un rayonnement persistant, découvert par une scientifique et son mari dans un hangar parisien.",
    materialAnchor: "Tube de pechblende, compteur de radioactivité, carnet de laboratoire",
    sceneText: "26 décembre 1898, Paris. Marie et Pierre Curie annoncent dans un rapport à l'Académie des sciences la découverte d'un nouvel élément : le radium. Dans le hangar de la rue Lhomond, la pechblende luisait légèrement dans le noir. La matière venait de révéler un secret qu'on n'avait pas même cherché.",
    fact: "Le 26 décembre 1898, Marie et Pierre Curie annoncent à l'Académie des sciences la découverte du radium, élément hautement radioactif isolé de la pechblende.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Marie_Curie", authority: false },
      { label: "Institut Curie", url: "https://curie.fr/fr/histoire-de-linstitut/marie-curie", authority: true }
    ],
    tags: ["curie", "radium", "radioactivite", "paris"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
];
