import type { InventionEntry } from "../../../types";

export const FR_INVENTION_BACKFILL_1900_1924: InventionEntry[] = [
  {
    id: "fr-1900-metro-paris",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-le-metropolitain-souterrain-a-paris",
    itemLabel: "prendre le métropolitain souterrain à Paris",
    theme: "transport", gestureRoot: "metro_paris",
    editorialScore: 95,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1900-07-19", releaseYear: 1900, datePrecision: "day",
    placeName: "Station Vincennes – Maillot, Paris", placeType: "site", placeQid: "Q44282",
    triggerLabel: "Inauguration de la première ligne du métro parisien",
    beforeState: "Avant juillet 1900, traverser Paris rapidement dépend des omnibus à chevaux et du chemin de fer de ceinture, lents et saturés.",
    afterState: "Après le 19 juillet 1900, les Parisiens peuvent descendre sous terre et traverser la ville en quelques minutes grâce au métropolitain.",
    objectChanged: "Tu peux acheter un ticket, descendre sous terre et traverser Paris sans dépendre du trafic ni des chevaux.",
    materialAnchor: "Ticket de carton, bouche de station en fer forgé Art nouveau, rame sur rails",
    sceneText: "19 juillet 1900, Paris. La bouche de station style Hector Guimard s'ouvre dans le trottoir comme une fleur de fonte. En bas, l'air est différent — frais, légèrement soufré. La rame entre en gare dans un grondement sourd. La ville a un sous-sol qui court plus vite que ses rues.",
    fact: "Le 19 juillet 1900, la première ligne du métro parisien est inaugurée entre Vincennes et Maillot, à l'occasion de l'Exposition universelle de Paris.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/M%C3%A9tro_de_Paris", authority: false },
      { label: "RATP histoire", url: "https://www.ratp.fr/groupe-ratp/ratp-et-vous/histoire", authority: true }
    ],
    tags: ["metro", "paris", "transport", "souterrain"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1903-tour-de-france-velo",
    countryQid: "Q142", lang: "fr",
    itemKey: "suivre-le-tour-de-france-cycliste",
    itemLabel: "suivre le Tour de France cycliste dans les journaux",
    theme: "loisirs", gestureRoot: "tour_de_france",
    editorialScore: 88,
    objectType: "media", category: "media",
    releaseDate: "1903-07-01", releaseYear: 1903, datePrecision: "day",
    placeName: "France entière, départ Paris", placeType: "country", placeQid: "Q142",
    triggerLabel: "Première édition du Tour de France cycliste organisée par L'Auto",
    beforeState: "Avant juillet 1903, aucune course cycliste nationale ne mobilise le public français autour d'un récit sportif en feuilleton.",
    afterState: "Après juillet 1903, le Tour de France devient un événement national annuel, suivi étape par étape dans les journaux.",
    objectChanged: "Tu peux acheter L'Auto chaque matin et suivre l'avancement de la course dans un récit haletant qui dure trois semaines.",
    materialAnchor: "Journal L'Auto, vélo de course, carte des étapes affichée",
    sceneText: "1er juillet 1903. Les 60 coureurs partent de Montgeron. Personne ne sait encore que cette course inventée pour vendre des journaux deviendra un rendez-vous national. Dans les cafés, la carte épinglée sur le mur suivra chaque étape comme une bataille.",
    fact: "Le 1er juillet 1903, la première édition du Tour de France cycliste est lancée par le journal L'Auto pour doper ses ventes, avec 60 coureurs sur 6 étapes.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Tour_de_France", authority: false },
      { label: "Tour de France officiel", url: "https://www.letour.fr/fr/histoire", authority: true }
    ],
    tags: ["tour-de-france", "cyclisme", "sport", "journal"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1905-separation-eglise-etat",
    countryQid: "Q142", lang: "fr",
    itemKey: "vivre-dans-un-etat-laique-separe-de-leglise",
    itemLabel: "vivre dans un État officiellement séparé de l'Église",
    theme: "administration", gestureRoot: "laicite",
    editorialScore: 96,
    objectType: "service", category: "service",
    releaseDate: "1905-12-09", releaseYear: 1905, datePrecision: "day",
    placeName: "Assemblée nationale, Paris", placeType: "institution", placeQid: "Q182519",
    triggerLabel: "Loi de séparation des Églises et de l'État",
    beforeState: "Avant décembre 1905, le Concordat de 1801 lie l'État français aux Églises : les prêtres sont rémunérés par l'État, les processions régulées par la loi.",
    afterState: "Après décembre 1905, l'État ne reconnaît plus aucun culte officiel, ne salarie plus les ministres des cultes, et la religion devient une affaire privée.",
    objectChanged: "Tu peux vivre dans une France où l'État gère l'école, le mariage civil et les funérailles sans référence obligatoire à la religion.",
    materialAnchor: "Loi imprimée, registre d'état civil laïque, école sans crucifix",
    sceneText: "9 décembre 1905, Paris. La loi est votée dans un silence tendu. Demain, l'État n'est plus catholique — ni rien d'autre. Les inventaires des biens d'Église déclenchent des bagarres dans les paroisses. La France vient de tracer une frontière nouvelle entre la foi et la puissance publique.",
    fact: "La loi du 9 décembre 1905 consacre la séparation des Églises et de l'État, fondant le principe de laïcité qui structure encore aujourd'hui la République française.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Loi_du_9_d%C3%A9cembre_1905_concernant_la_s%C3%A9paration_des_%C3%89glises_et_de_l%27%C3%89tat", authority: false },
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr/loda/id/LEGITEXT000006070169", authority: true }
    ],
    tags: ["laicite", "eglise", "etat", "republique"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1906-clemenceau-ministere-travail",
    countryQid: "Q142", lang: "fr",
    itemKey: "beneficier-dun-ministere-du-travail",
    itemLabel: "bénéficier d'un ministère dédié au travail et aux droits ouvriers",
    theme: "travail", gestureRoot: "ministere_travail",
    editorialScore: 84,
    objectType: "service", category: "service",
    releaseDate: "1906-10-25", releaseYear: 1906, datePrecision: "day",
    placeName: "Paris", placeType: "city", placeQid: "Q90",
    triggerLabel: "Création du ministère du Travail",
    beforeState: "Avant 1906, les questions ouvrières relèvent du Commerce ou de l'Intérieur, sans administration dédiée.",
    afterState: "Après octobre 1906, un ministère du Travail distinct coordonne inspection du travail, conciliation des conflits et législation sociale.",
    objectChanged: "Tu peux t'adresser à une administration dédiée pour les conflits du travail, les accidents et les conventions collectives.",
    materialAnchor: "Bureau d'inspection du travail, formulaire de déclaration d'accident, carnet ouvrier",
    sceneText: "1906, Paris. Un ministère du Travail — ça semble banal dit comme ça. Mais pour l'ouvrier qui se blesse et ne sait où se plaindre, pour le syndicat qui cherche un interlocuteur officiel, c'est la première fois qu'une porte est là, avec une enseigne qui dit que son problème existe.",
    fact: "Le 25 octobre 1906, le gouvernement Clemenceau crée le ministère du Travail, première institution d'État entièrement dédiée aux questions ouvrières et sociales.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Minist%C3%A8re_du_Travail_%28France%29", authority: false },
      { label: "Ministère du Travail", url: "https://travail-emploi.gouv.fr/le-ministere/presentation/histoire-du-ministere", authority: true }
    ],
    tags: ["travail", "ministere", "clemenceau", "droit-ouvrier"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1910-aviation-bleriot",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-un-avion-voler-au-dessus-de-la-france",
    itemLabel: "voir un aéroplane traverser le ciel au-dessus de la France",
    theme: "transport", gestureRoot: "aviation",
    editorialScore: 93,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1909-07-25", releaseYear: 1909, datePrecision: "day",
    placeName: "Côte anglaise, Calais", placeType: "site", placeQid: null,
    triggerLabel: "Blériot traverse la Manche en aéroplane pour la première fois",
    beforeState: "Avant juillet 1909, l'avion est une curiosité de meeting, incapable de franchir un obstacle géographique majeur.",
    afterState: "Après juillet 1909, l'aéroplane prouve qu'il peut traverser des détroits et franchir des frontières — l'aviation entre dans l'histoire de la guerre et des transports.",
    objectChanged: "Tu peux lever les yeux et voir un moteur à hélice traverser le ciel — ce n'est plus un ballon captif, c'est un engin dirigé par un pilote.",
    materialAnchor: "Monoplan de bois et toile, lunettes de pilote, foule massée au bord de la falaise",
    sceneText: "25 juillet 1909. Blériot décolle de France dans son monoplan de toile. 37 minutes plus tard, il se pose en Angleterre. La Manche est franchie. Quelque chose dans la géographie du monde vient de bouger — les frontières naturelles ne protègent plus rien.",
    fact: "Le 25 juillet 1909, Louis Blériot réalise la première traversée aérienne de la Manche en 37 minutes, démontrant que l'aviation pouvait franchir des obstacles géographiques majeurs.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Louis_Bl%C3%A9riot", authority: false },
      { label: "Musée de l'Air et de l'Espace", url: "https://www.museeairespace.fr/", authority: true }
    ],
    tags: ["aviation", "bleriot", "manche", "avion"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1914-union-sacree-guerre",
    countryQid: "Q142", lang: "fr",
    itemKey: "etre-mobilise-pour-la-grande-guerre",
    itemLabel: "être mobilisé pour la Grande Guerre et partir au front",
    theme: "administration", gestureRoot: "mobilisation_1914",
    editorialScore: 99,
    objectType: "service", category: "service",
    releaseDate: "1914-08-01", releaseYear: 1914, datePrecision: "day",
    placeName: "Gares de France", placeType: "site", placeQid: null,
    triggerLabel: "Décret de mobilisation générale — entrée en guerre de la France",
    beforeState: "Avant le 1er août 1914, la France est en paix depuis 1871, les réservistes sont dans les campagnes et les ateliers.",
    afterState: "Après le 1er août 1914, trois millions d'hommes sont mobilisés en deux semaines. La France entre dans la guerre la plus meurtrière de son histoire.",
    objectChanged: "Tu peux recevoir un ordre de mobilisation sur papier rose et devoir rejoindre ton régiment dans les quarante-huit heures.",
    materialAnchor: "Livret militaire, ordre de mobilisation rose, quai de gare bondé",
    sceneText: "1er août 1914. Les affiches d'ordre de mobilisation générale sont collées sur les murs des mairies. Les hommes lisent, certains pâlissent, d'autres partent chercher leur livret militaire. Les gares se remplissent. Personne ne dit combien de temps.",
    fact: "Le 1er août 1914, la France décrète la mobilisation générale. En deux semaines, 3,8 millions d'hommes rejoignent leur unité, déclenchant la participation française à la Première Guerre mondiale.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Mobilisation_fran%C3%A7aise_en_1914", authority: false },
      { label: "Archives nationales", url: "https://www.archives-nationales.culture.gouv.fr/", authority: true }
    ],
    tags: ["guerre", "mobilisation", "1914", "front"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1916-impot-sur-le-revenu",
    countryQid: "Q142", lang: "fr",
    itemKey: "payer-limpot-sur-le-revenu",
    itemLabel: "payer l'impôt sur le revenu en France",
    theme: "administration", gestureRoot: "impot_revenu",
    editorialScore: 88,
    objectType: "service", category: "service",
    releaseDate: "1914-07-15", releaseYear: 1914, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Loi Caillaux instaurant l'impôt général sur le revenu",
    beforeState: "Avant juillet 1914, la France n'a pas d'impôt direct unifié sur les revenus — seules des contributions indirectes existent.",
    afterState: "Après 1914, tout contribuable déclarant ses revenus est soumis à un impôt progressif, base du financement de l'État moderne.",
    objectChanged: "Tu peux remplir une déclaration de revenus et payer un impôt calculé sur ce que tu gagnes réellement.",
    materialAnchor: "Formulaire de déclaration, barème progressif, timbre fiscal",
    sceneText: "1914, France. La loi est votée dans un contexte tendu — la guerre arrive. L'impôt sur le revenu qu'on débattait depuis vingt ans est là. Pour la première fois, l'État regarde dans les revenus de chacun et y trouve une contribution progressive.",
    fact: "La loi du 15 juillet 1914 instaure l'impôt général sur le revenu en France, entrant en application effective à partir de 1916 pour financer l'effort de guerre.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Impôt_sur_le_revenu_(France)", authority: false },
      { label: "Ministère des Finances", url: "https://www.economie.gouv.fr/dgfip/histoire-de-la-dgfip", authority: true }
    ],
    tags: ["impot", "revenu", "fiscalite", "etat"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1918-armistice",
    countryQid: "Q142", lang: "fr",
    itemKey: "entendre-les-cloches-de-larmistice-du-11-novembre",
    itemLabel: "entendre les cloches et les canons annoncer la fin de la guerre",
    theme: "administration", gestureRoot: "armistice_1918",
    editorialScore: 99,
    objectType: "service", category: "service",
    releaseDate: "1918-11-11", releaseYear: 1918, datePrecision: "day",
    placeName: "France entière, forêt de Compiègne", placeType: "site", placeQid: null,
    triggerLabel: "Armistice du 11 novembre 1918 — fin de la Première Guerre mondiale",
    beforeState: "Avant le 11 novembre 1918, la France est en guerre depuis plus de quatre ans, avec 1,4 million de morts.",
    afterState: "Après le 11 novembre 1918 à 11h, les combats s'arrêtent sur tous les fronts. La France vit le plus grand soulagement collectif de son histoire moderne.",
    objectChanged: "Tu peux entendre le silence des canons pour la première fois depuis 1914, et pleurer dans la rue sans que personne trouve ça étrange.",
    materialAnchor: "Cloches des mairies, journal avec la manchette ARMISTICE, foule dans les rues",
    sceneText: "11 novembre 1918, 11 heures. Les cloches sonnent partout en France en même temps. Dans les tranchées, les soldats ne bougent pas tout de suite. Ils attendent que le silence soit vrai. Puis, lentement, quelqu'un pose son fusil. Et c'est fini.",
    fact: "Le 11 novembre 1918 à 11h, l'armistice mettant fin à la Première Guerre mondiale est signé dans la forêt de Compiègne. La France a perdu 1,4 million de soldats.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Armistice_de_1918", authority: false },
      { label: "Mémoire des Hommes", url: "https://www.memoiredeshommes.sga.defense.gouv.fr/", authority: true }
    ],
    tags: ["armistice", "guerre", "1918", "paix"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1920-radio-tour-eiffel-premices",
    countryQid: "Q142", lang: "fr",
    itemKey: "capter-les-premieres-emissions-radio-experimentales",
    itemLabel: "capter les premières émissions radio expérimentales françaises",
    theme: "communication", gestureRoot: "radio_experimentale",
    editorialScore: 82,
    objectType: "media", category: "media",
    releaseDate: "1921", releaseYear: 1921, datePrecision: "year",
    placeName: "Tour Eiffel, Paris", placeType: "site", placeQid: "Q243",
    triggerLabel: "Premières émissions radio régulières françaises depuis la Tour Eiffel",
    beforeState: "Avant 1921, les émissions radio en France sont purement militaires ou expérimentales, sans audience publique.",
    afterState: "À partir de 1921, des amateurs équipés d'un poste à galène peuvent capter des émissions depuis la Tour Eiffel — la radio entre dans les foyers.",
    objectChanged: "Tu peux construire ou acheter un poste à galène, brancher une antenne et capter des sons depuis la Tour Eiffel.",
    materialAnchor: "Poste à galène, antenne extérieure, écouteurs individuels",
    sceneText: "1921, Paris. L'amateur de T.S.F. pose son galène, ajuste le cristal, met ses écouteurs. Dans le grésillement, une voix — une vraie voix humaine, émise depuis la Tour Eiffel. Pour lui, c'est encore un exploit. Dans dix ans, ce sera quotidien.",
    fact: "À partir de 1921, la Tour Eiffel diffuse des émissions radio régulières accessibles aux amateurs de T.S.F., préfigurant la radiodiffusion publique française.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Radiodiffusion_en_France", authority: false },
      { label: "INA", url: "https://www.ina.fr/ina-eclaire-actu/histoire-de-la-radio", authority: true }
    ],
    tags: ["radio", "tour-eiffel", "tsf", "paris"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1922-voiture-citroën-populaire",
    countryQid: "Q142", lang: "fr",
    itemKey: "acheter-une-voiture-citroën-accessible",
    itemLabel: "acheter une voiture accessible à la classe moyenne française",
    theme: "transport", gestureRoot: "voiture_populaire",
    editorialScore: 87,
    objectType: "device", category: "transport",
    releaseDate: "1919-05-28", releaseYear: 1919, datePrecision: "day",
    placeName: "Usine Citroën, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Lancement de la Citroën Type A, première voiture européenne en grande série",
    beforeState: "Avant 1919, l'automobile est un luxe réservé à une élite aisée — produite à la main, coûteuse, fragile.",
    afterState: "Après 1919, la production en grande série à la chaîne rend une voiture accessible à des Français moins fortunés.",
    objectChanged: "Tu peux envisager d'acquérir une automobile sans être riche, produite en série comme un objet du quotidien.",
    materialAnchor: "Carrosserie noire, manivelle de démarrage, carnet de commande chez le concessionnaire",
    sceneText: "1919, Paris. Dans l'usine Citroën du quai de Javel, la chaîne de montage tourne comme chez Ford. La Type A sort à 100 voitures par jour. Pour la première fois, une voiture française est pensée pour être fabriquée en masse et vendue à ceux qui ne sont pas riches.",
    fact: "En 1919, André Citroën lance la Citroën Type A, première voiture européenne produite en grande série à la chaîne, rendant l'automobile accessible à une clientèle plus large.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Citro%C3%ABn_Type_A", authority: false },
      { label: "Citroën Origine", url: "https://www.citroen.fr/univers-citroen/heritage.html", authority: true }
    ],
    tags: ["citroën", "voiture", "serie", "paris"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1924-jo-paris-olympiques",
    countryQid: "Q142", lang: "fr",
    itemKey: "assister-aux-jeux-olympiques-de-paris",
    itemLabel: "assister aux Jeux olympiques de Paris 1924",
    theme: "loisirs", gestureRoot: "jo_paris_1924",
    editorialScore: 90,
    objectType: "service", category: "service",
    releaseDate: "1924-07-05", releaseYear: 1924, datePrecision: "day",
    placeName: "Stade olympique de Colombes, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Ouverture des Jeux olympiques de Paris 1924",
    beforeState: "Avant 1924, aucune compétition sportive internationale de cette ampleur n'a lieu en France depuis les JO de Paris 1900.",
    afterState: "Après les JO de 1924, Paris s'affirme comme ville sportive internationale, avec le premier village olympique et une couverture médiatique mondiale.",
    objectChanged: "Tu peux assister à des épreuves olympiques, lire les résultats dans les journaux chaque matin et voir courir les champions du monde.",
    materialAnchor: "Billet d'entrée, programme officiel, drapeau olympique",
    sceneText: "5 juillet 1924, Colombes. Le stade est plein, les drapeaux de 44 nations flottent. Pour la deuxième fois en vingt-quatre ans, Paris est la capitale du sport mondial. Dans les tribunes, on voit courir Paavo Nurmi — deux fois champion dans la même journée.",
    fact: "Les Jeux olympiques de Paris 1924 rassemblent 3 089 athlètes de 44 nations et introduisent pour la première fois un village olympique, marquant une étape dans l'histoire du sport international.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Jeux_olympiques_d%27%C3%A9t%C3%A9_de_1924", authority: false },
      { label: "Comité Olympique Français", url: "https://www.paris2024.org/fr/histoire-des-jo-a-paris/", authority: true }
    ],
    tags: ["jo", "paris", "olympique", "sport"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
];
