import type { InventionEntry } from "../../../types";

export const FR_INVENTION_BACKFILL_1925_1949: InventionEntry[] = [
  {
    id: "fr-1925-radio-tour-eiffel",
    countryQid: "Q142", lang: "fr",
    itemKey: "ecouter-la-radio-depuis-la-tour-eiffel",
    itemLabel: "écouter la radio depuis les premières émissions françaises",
    theme: "communication", gestureRoot: "radio_tour_eiffel",
    editorialScore: 82,
    objectType: "media", category: "media",
    releaseDate: "1925-11-24", releaseYear: 1925, datePrecision: "day",
    placeName: "Tour Eiffel, Paris", placeType: "site", placeQid: "Q243",
    triggerLabel: "Premières émissions régulières de Radio Tour Eiffel",
    beforeState: "Avant fin 1925, la radio reste surtout expérimentale et sans rendez-vous fixe pour le grand public.",
    afterState: "À partir de novembre 1925, les émissions depuis la Tour Eiffel donnent à la radio française un visage et un lieu d'antenne visible.",
    objectChanged: "Tu peux brancher un poste à lampes et capter des programmes annoncés depuis un émetteur parisien identifié.",
    materialAnchor: "Poste à lampes, antenne et Tour Eiffel comme repère d'ondes",
    sceneText:
      "Novembre 1925, Paris. Le poste grésille dans le salon et la voix sort d'un émetteur accroché à la Tour Eiffel. La radio cesse d'être seulement un bruit d'atelier : elle devient un rendez-vous domestique.",
    fact: "À partir du 24 novembre 1925, Radio Tour Eiffel diffuse des programmes réguliers depuis la Tour Eiffel, marquant l'essor de la radiodiffusion en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Radio_Tour_Eiffel", authority: false },
      { label: "INA", url: "https://www.ina.fr/ina-eclaire-actu/histoire-de-la-radio", authority: true }
    ],
    tags: ["radio", "tour-eiffel", "paris", "ondes"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1931-demonstration-television",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-une-image-transmise-par-television-en-france",
    itemLabel: "voir une image transmise par télévision en France",
    theme: "communication", gestureRoot: "television_francaise",
    editorialScore: 84,
    objectType: "media", category: "media",
    releaseDate: "1931-04-14", releaseYear: 1931, datePrecision: "day",
    placeName: "École supérieure d'électricité, Malakoff", placeType: "site", placeQid: null,
    triggerLabel: "Première démonstration publique de télévision en France",
    beforeState: "Avant avril 1931, l'image animée se voit au cinéma ou ne se voit pas du tout : elle ne traverse pas encore une pièce ou une rue par ondes.",
    afterState: "Après avril 1931, la télévision apparaît en France comme une possibilité technique concrète et non plus comme une simple spéculation.",
    objectChanged: "Tu peux voir apparaître sur un récepteur l'image d'une personne filmée dans un autre bâtiment.",
    materialAnchor: "Écran minuscule, tube cathodique et banc d'essai",
    sceneText: "14 avril 1931, a Malakoff. L'image arrive de Montrouge jusqu'a un poste experimental. Pour la premiere fois en France, la television n'est plus une hypothese d'ingenieur: elle se laisse voir, meme sur un petit ecran tremblant.",
    fact: "Le 14 avril 1931, René Barthélemy réalise entre Montrouge et Malakoff la première démonstration publique de télévision en France.",
    sources: [
      { label: "Histoire par l'image", url: "https://histoire-image.org/albums/siecle-transformations-scientifiques-technologiques", authority: true },
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false }
    ],
    tags: ["television", "rene-barthelemy", "image", "media"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1932-paris-television",
    countryQid: "Q142", lang: "fr",
    itemKey: "capter-le-programme-experimental-paris-television",
    itemLabel: "capter le programme expérimental Paris Télévision",
    theme: "communication", gestureRoot: "paris_television",
    editorialScore: 78,
    objectType: "media", category: "media",
    releaseDate: "1932-12", releaseYear: 1932, datePrecision: "month",
    placeName: "103 rue de Grenelle, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Lancement du programme expérimental Paris Télévision",
    beforeState: "Avant fin 1932, les essais français de télévision restent ponctuels et sans rendez-vous régulier.",
    afterState: "À partir de décembre 1932, un programme expérimental d'une heure par semaine donne à la télévision française un premier rythme de diffusion.",
    objectChanged: "Tu peux tenter de capter un rendez-vous télévisé régulier, même encore expérimental et réservé à très peu de postes.",
    materialAnchor: "Récepteur expérimental, cadran et horaire de diffusion",
    sceneText: "Décembre 1932, rue de Grenelle. La television francaise commence a avoir une cadence, pas seulement des essais isoles. Une heure par semaine suffit deja a transformer l'invention en media en devenir.",
    fact: "À partir de décembre 1932, René Barthélemy met au point en France le programme expérimental Paris Télévision, diffusé environ une heure par semaine en 60 lignes.",
    sources: [
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false }
    ],
    tags: ["television", "paris-television", "grenelle", "media"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1933-air-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-lavion-avec-air-france",
    itemLabel: "prendre l'avion avec Air France",
    theme: "transport", gestureRoot: "air_france",
    editorialScore: 88,
    objectType: "service", category: "transport",
    releaseDate: "1933-10-07", releaseYear: 1933, datePrecision: "day",
    placeName: "Aéroport du Bourget, Le Bourget", placeType: "site", placeQid: null,
    triggerLabel: "Inauguration d'Air France",
    beforeState: "Avant octobre 1933, le transport aérien français reste morcelé entre plusieurs compagnies et réseaux hérités des pionniers.",
    afterState: "Après octobre 1933, Air France devient la compagnie nationale qui unifie l'offre aérienne française sous un même nom.",
    objectChanged: "Tu peux acheter un billet portant Air France plutôt que naviguer entre plusieurs compagnies aux noms et réseaux dispersés.",
    materialAnchor: "Billet imprimé, affiche Air France et piste du Bourget",
    sceneText: "7 octobre 1933, au Bourget. Le nom Air France s'impose d'un coup sur les billets, les affiches et le reseau. Pour le voyageur francais, l'aviation commerciale commence enfin a ressembler a un service national identifiable.",
    fact: "Le 7 octobre 1933, Air France est officiellement inaugurée au Bourget comme nouvelle compagnie nationale issue du regroupement des grands transporteurs français.",
    sources: [
      { label: "Air France", url: "https://corporate.airfrance.com/fr/le-decollage-1933-1945", authority: true },
      { label: "Air France 90 ans", url: "https://corporate.airfrance.com/fr/actualites/air-france-celebre-90-ans-delegance-travers-le-monde-entier", authority: true }
    ],
    tags: ["transport", "aviation", "air-france", "voyage"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1935-radiovision-ptt",
    countryQid: "Q142", lang: "fr",
    itemKey: "regarder-la-premiere-chaine-reguliere-francaise",
    itemLabel: "regarder la première chaîne régulière française",
    theme: "communication", gestureRoot: "radiovision_ptt",
    editorialScore: 90,
    objectType: "media", category: "media",
    releaseDate: "1935-04-26", releaseYear: 1935, datePrecision: "day",
    placeName: "103 rue de Grenelle, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Première émission officielle de Radio-PTT Vision",
    beforeState: "Avant le 26 avril 1935, la télévision française n'existe qu'en essais et démonstrations sans vraie chaîne régulière.",
    afterState: "Après le 26 avril 1935, la France dispose d'une première chaîne de télévision régulière, encore confidentielle mais identifiée.",
    objectChanged: "Tu peux suivre une émission télévisée française programmée depuis un studio dédié plutôt qu'une simple démonstration technique.",
    materialAnchor: "Studio de Grenelle, caméra et récepteur 60 lignes",
    sceneText: "26 avril 1935, rue de Grenelle. La television francaise entre dans le rythme d'une emission officielle. Ce n'est plus seulement un appareil qui fonctionne: c'est un programme, un horaire, une premiere forme de chaine.",
    fact: "Le 26 avril 1935, Radio-PTT Vision diffuse sa première émission officielle au 103 rue de Grenelle à Paris, acte de naissance de la première chaîne régulière française.",
    sources: [
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false },
      { label: "Radio-PTT Vision", url: "https://fr.wikipedia.org/wiki/Radio-PTT_Vision", authority: false }
    ],
    tags: ["television", "radio-ptt-vision", "grenelle", "media"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1936-air-france-dakar",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-lair-france-jusqua-dakar",
    itemLabel: "prendre Air France jusqu'à Dakar",
    theme: "transport", gestureRoot: "liaison_aerienne",
    editorialScore: 80,
    objectType: "service", category: "transport",
    releaseDate: "1936-05", releaseYear: 1936, datePrecision: "month",
    placeName: "Paris et Dakar", placeType: "country", placeQid: "Q142",
    triggerLabel: "Ouverture du service passagers Air France vers Dakar",
    beforeState: "Avant 1936, l'étape de Dakar sert surtout au courrier et les voyageurs ne disposent pas encore d'un service passagers régulier sur cette route.",
    afterState: "À partir de mai 1936, Dakar entre dans le réseau passagers d'Air France au départ de Paris.",
    objectChanged: "Tu peux acheter une place passager vers Dakar sur une liaison régulière là où la ligne servait surtout à la poste aérienne.",
    materialAnchor: "Billet Air France, couchette de train et avion Dewoitine",
    sceneText: "Mai 1936. La route vers Dakar ne sert plus seulement a faire passer du courrier: elle devient une ligne passagers signee Air France. Le voyage reste long, mais il change deja de statut pour le public francais.",
    fact: "En mai 1936, Air France ouvre un service passagers hebdomadaire de Paris vers Dakar, jusque-là essentiellement limité au courrier sur cette route.",
    sources: [
      { label: "Air France", url: "https://corporate.airfrance.com/en/news/1936-air-france-launches-passenger-flights-dakar", authority: true }
    ],
    tags: ["transport", "aviation", "dakar", "air-france"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1937-radiodiffusion-nationale-television",
    countryQid: "Q142", lang: "fr",
    itemKey: "capter-la-television-francaise-en-455-lignes",
    itemLabel: "capter la télévision française en 455 lignes",
    theme: "communication", gestureRoot: "television_455_lignes",
    editorialScore: 86,
    objectType: "media", category: "media",
    releaseDate: "1937-07-14", releaseYear: 1937, datePrecision: "day",
    placeName: "Tour Eiffel, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Début de Radiodiffusion nationale Télévision",
    beforeState: "Avant l'été 1937, la télévision française reste limitée à des définitions plus basses et à des essais encore fragiles.",
    afterState: "À partir du 14 juillet 1937, la télévision française bascule vers un émetteur 455 lignes à la tour Eiffel et des émissions plus régulières.",
    objectChanged: "Tu peux capter une image télévisée plus fine et plus stable depuis l'émetteur de la tour Eiffel.",
    materialAnchor: "Tour Eiffel, poste de télévision et image 455 lignes",
    sceneText: "14 juillet 1937, a Paris. La television francaise gagne en finesse, en puissance et en regularite depuis la tour Eiffel. Le media reste rare, mais son infrastructure prend enfin une forme durable et reconnaissable.",
    fact: "Le 14 juillet 1937, Radio-PTT Vision devient Radiodiffusion nationale Télévision et commence ses essais réguliers en 455 lignes depuis la tour Eiffel.",
    sources: [
      { label: "Radiodiffusion nationale Télévision", url: "https://fr.wikipedia.org/wiki/Radiodiffusion_nationale_T%C3%A9l%C3%A9vision", authority: false },
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false }
    ],
    tags: ["television", "tour-eiffel", "455-lignes", "media"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1928-penicilline",
    countryQid: "Q142", lang: "fr",
    itemKey: "traiter-une-infection-avec-la-penicilline",
    itemLabel: "traiter une infection bactérienne avec la pénicilline",
    theme: "santé", gestureRoot: "penicilline",
    editorialScore: 96,
    objectType: "service", category: "service",
    releaseDate: "1928-09-28", releaseYear: 1928, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Découverte de la pénicilline par Alexander Fleming",
    beforeState: "Avant 1928, les infections bactériennes comme la septicémie sont souvent mortelles sans traitement efficace.",
    afterState: "Après 1928, la pénicilline ouvre la voie aux antibiotiques et change radicalement la médecine.",
    objectChanged: "Tu peux recevoir une injection d'antibiotique qui tue les bactéries là où rien n'existait avant.",
    materialAnchor: "Seringue, ampoule de pénicilline et ordonnance médicale",
    sceneText: "28 septembre 1928. En France, la nouvelle semble encore lointaine, mais l'idee est deja decisive: une substance peut enfin vaincre l'infection bacterienne. Dans les hopitaux francais, c'est l'horizon meme de la medecine qui commence a changer.",
    fact: "Le 28 septembre 1928, Alexander Fleming découvre la pénicilline, premier antibiotique de l'histoire.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/P%C3%A9nicilline", authority: false },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/medicine/1945/fleming/biographical/", authority: true }
    ],
    tags: ["sante", "antibiotique", "medecine", "infection"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1938-stylo-bille",
    countryQid: "Q142", lang: "fr",
    itemKey: "ecrire-avec-un-stylo-bille",
    itemLabel: "écrire avec un stylo à bille",
    theme: "communication", gestureRoot: "stylo_bille",
    editorialScore: 88,
    objectType: "device", category: "device",
    releaseDate: "1938-10-30", releaseYear: 1938, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Brevet du stylo à bille par László Bíró",
    beforeState: "Avant 1938, écrire en déplacement nécessite un stylo-plume avec cartouche d'encre qui tache et sèche.",
    afterState: "Après 1938, le stylo bille offre une écriture fiable, sans tache, qui ne nécessite pas de remplissage.",
    objectChanged: "Tu peux écrire sur n'importe quelle surface sans t'inquiéter des taches d'encre ou du séchage.",
    materialAnchor: "Stylo bille, papier et capuchon cliquable",
    sceneText: "1938. En France comme ailleurs, l'idee frappe par sa simplicite: une petite bille remplace la plume et l'encrier. Le geste d'ecrire se prepare a devenir plus propre, plus mobile et beaucoup moins fragile.",
    fact: "Le 30 octobre 1938, László Bíró dépose le brevet du stylo à bille, qui révolutionnera l'écriture quotidienne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Stylo_%C3%A0_bille", authority: false }
    ],
    tags: ["ecriture", "stylo", "biro", "papeterie"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1947-transistor",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-un-appareil-a-transistors",
    itemLabel: "utiliser un appareil électronique compact à transistors",
    theme: "communication", gestureRoot: "transistor",
    editorialScore: 90,
    objectType: "device", category: "device",
    releaseDate: "1947-12-16", releaseYear: 1947, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Invention du transistor par Bardeen, Brattain et Shockley",
    beforeState: "Avant 1947, les appareils électroniques fonctionnent avec des lampes à vide, lourdes, fragiles et chaleureuses.",
    afterState: "Après 1947, le transistor permet de miniaturiser tous les appareils électroniques.",
    objectChanged: "Tu peux porter un transistor radio dans ta poche au lieu de porter un poste lourd et encombrant.",
    materialAnchor: "Transistor radio, pile et oreillette",
    sceneText: "1947. En France, on ne le tient pas encore dans chaque poche, mais la promesse est deja claire: une electronique sans lampes, plus froide et plus petite. Les radios et les objets du quotidien vont retrecir jusque dans les foyers francais.",
    fact: "Le 16 décembre 1947, le transistor est inventé aux Bell Labs, ouvrant la voie à toute l'électronique moderne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Transistor", authority: false },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/physics/1956/summary/", authority: true }
    ],
    tags: ["electronique", "radio", "transistor", "miniaturisation"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1949-deux-chevaux",
    countryQid: "Q142", lang: "fr",
    itemKey: "conduire-une-2cv",
    itemLabel: "conduire une 2CV Citroën",
    theme: "transport", gestureRoot: "deux_chevaux",
    editorialScore: 92,
    objectType: "device", category: "transport",
    releaseDate: "1948-10-07", releaseYear: 1948, datePrecision: "day",
    placeName: "Salon de l'automobile, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Présentation de la 2CV Citroën au Salon de l'auto",
    beforeState: "Avant 1948, l'automobile reste hors de portée de la majorité des Français.",
    afterState: "Après 1948, la 2CV démocratise l'automobile avec un prix accessible à la classe ouvrière.",
    objectChanged: "Tu peux acheter une voiture neuve avec un salaire d'ouvrier et prendre la route avec ta famille.",
    materialAnchor: "2CV grise, capote rabattable et volant plat",
    sceneText: "7 octobre 1948, Salon de l'automobile. La petite voiture grise à la capote rabattable fait sensation. Elle ne coûte presque rien, consomme peu et tient sur les chemins de terre. La France ouvrière va enfin rouler.",
    fact: "Le 7 octobre 1948, la 2CV Citroën est présentée au Salon de l'automobile de Paris, démocratisant la voiture pour les Français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Citro%C3%ABn_2CV", authority: false },
      { label: "Citroën", url: "https://www.citroen.fr/monde-citroen/heritage.html", authority: true }
    ],
    tags: ["voiture", "2cv", "citroen", "automobile"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
];
