import type { InventionEntry } from "../../../types";

export const FR_INVENTION_BACKFILL_1925_1949: InventionEntry[] = [
  {
    id: "fr-1925-radio-tour-eiffel",
    countryQid: "Q142", lang: "fr",
    itemKey: "ecouter-la-radio-depuis-la-tour-eiffel",
    itemLabel: "écouter la radio depuis les premières émissions françaises",
    theme: "communication", gestureRoot: "radio_tour_eiffel",
    editorialScore: 82,
    objectType: "media", category: "media",
    releaseDate: "1925-11-24", releaseYear: 1925, datePrecision: "day",
    placeName: "Tour Eiffel, Paris", placeType: "site", placeQid: "Q243",
    triggerLabel: "Premières émissions régulières de Radio Tour Eiffel",
    beforeState: "Avant fin 1925, la radio reste surtout expérimentale et sans rendez-vous fixe pour le grand public.",
    afterState: "À partir de novembre 1925, les émissions depuis la Tour Eiffel donnent à la radio française un visage et un lieu d'antenne visible.",
    objectChanged: "Tu peux brancher un poste à lampes et capter des programmes annoncés depuis un émetteur parisien identifié.",
    materialAnchor: "Poste à lampes, antenne et Tour Eiffel comme repère d'ondes",
    sceneText:
      "Novembre 1925, Paris. Le poste grésille dans le salon et la voix sort d'un émetteur accroché à la Tour Eiffel. La radio cesse d'être seulement un bruit d'atelier : elle devient un rendez-vous domestique.",
    fact: "À partir du 24 novembre 1925, Radio Tour Eiffel diffuse des programmes réguliers depuis la Tour Eiffel, marquant l'essor de la radiodiffusion en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Radio_Tour_Eiffel", authority: false },
      { label: "INA", url: "https://www.ina.fr/ina-eclaire-actu/histoire-de-la-radio", authority: true }
    ],
    tags: ["radio", "tour-eiffel", "paris", "ondes"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1926-afnor",
    countryQid: "Q142",
    lang: "fr",
    itemKey: "sappuyer-sur-des-normes-francaises-afnor",
    itemLabel: "s'appuyer sur des normes françaises communes (AFNOR)",
    theme: "administration",
    gestureRoot: "normes_afnor",
    editorialScore: 84,
    objectType: "service",
    category: "service",
    releaseDate: "1926-06-22",
    releaseYear: 1926,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Création de l'Association française de normalisation (AFNOR)",
    beforeState:
      "Avant 1926, les cahiers des charges industriels et les formats techniques divergent encore fortement d'un fournisseur à l'autre.",
    afterState:
      "Après juin 1926, la normalisation française dispose d'un cadre associatif pour rapprocher normes, essais et usages.",
    objectChanged:
      "Tu peux t'appuyer sur des références communes pour les matériaux, les essais et les échanges entre industriels.",
    materialAnchor: "Cahier des charges, éprouvette et cachet de conformité",
    sceneText:
      "22 juin 1926, à Paris. L'AFNOR naît pour rapprocher les règles techniques : moins de pièces incompatibles, plus de repères partagés entre ateliers. La normalisation cesse d'être seulement une habitude locale.",
    fact: "Le 22 juin 1926 est créée l'Association française de normalisation (AFNOR), organisme chargé d'élaborer et de promouvoir les normes françaises.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Association_fran%C3%A7aise_de_normalisation", authority: false },
      { label: "AFNOR", url: "https://www.afnor.org/", authority: true }
    ],
    tags: ["normes", "afnor", "industrie", "qualite"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1927-spirit-of-st-louis-bourget",
    countryQid: "Q142",
    lang: "fr",
    itemKey: "voir-laviation-atlantique-au-bourget",
    itemLabel: "voir l'aviation transatlantique accueillie au Bourget",
    theme: "transport",
    gestureRoot: "aviation_bourget",
    editorialScore: 82,
    objectType: "infrastructure",
    category: "transport",
    releaseDate: "1927-05-21",
    releaseYear: 1927,
    datePrecision: "day",
    placeName: "Aéroport du Bourget, Le Bourget",
    placeType: "site",
    placeQid: null,
    triggerLabel: "Atterrissage du Spirit of St. Louis après la traversée de l'Atlantique",
    beforeState:
      "Avant mai 1927, la traversée de l'Atlantique Nord en avion reste une prouesse rare et incertaine pour le grand public.",
    afterState:
      "Après le 21 mai 1927, l'atterrissage au Bourget rend l'aviation long courrier tangible pour des milliers de spectateurs.",
    objectChanged:
      "Tu peux voir un avion qui vient de relier New York à Paris sans escale, comme preuve que l'océan se traverse désormais par les airs.",
    materialAnchor: "Piste du Bourget, foule et appareil à moteur à l'arrêt",
    sceneText:
      "21 mai 1927, au Bourget. Le Spirit of St. Louis se pose devant la foule : l'Atlantique vient d'être franchi en solo par les airs. À Paris, l'aviation cesse d'être un bruit de moteurs lointain pour devenir un spectacle national.",
    fact: "Le 21 mai 1927, Charles Lindbergh atterrit au Bourget après la première traversée de l'Atlantique Nord sans escale en solitaire.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Spirit_of_Saint-Louis", authority: false },
      { label: "1927 en France", url: "https://fr.wikipedia.org/wiki/1927_en_France", authority: false }
    ],
    tags: ["aviation", "bourget", "atlantique", "record"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1931-demonstration-television",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-une-image-transmise-par-television-en-france",
    itemLabel: "voir une image transmise par télévision en France",
    theme: "communication", gestureRoot: "television_francaise",
    editorialScore: 84,
    objectType: "media", category: "media",
    releaseDate: "1931-04-14", releaseYear: 1931, datePrecision: "day",
    placeName: "École supérieure d'électricité, Malakoff", placeType: "site", placeQid: null,
    triggerLabel: "Première démonstration publique de télévision en France",
    beforeState: "Avant avril 1931, l'image animée se voit au cinéma ou ne se voit pas du tout : elle ne traverse pas encore une pièce ou une rue par ondes.",
    afterState: "Après avril 1931, la télévision apparaît en France comme une possibilité technique concrète et non plus comme une simple spéculation.",
    objectChanged: "Tu peux voir apparaître sur un récepteur l'image d'une personne filmée dans un autre bâtiment.",
    materialAnchor: "Écran minuscule, tube cathodique et banc d'essai",
    sceneText: "14 avril 1931, a Malakoff. L'image arrive de Montrouge jusqu'a un poste experimental. Pour la premiere fois en France, la television n'est plus une hypothese d'ingenieur: elle se laisse voir, meme sur un petit ecran tremblant.",
    fact: "Le 14 avril 1931, René Barthélemy réalise entre Montrouge et Malakoff la première démonstration publique de télévision en France.",
    sources: [
      { label: "Histoire par l'image", url: "https://histoire-image.org/albums/siecle-transformations-scientifiques-technologiques", authority: true },
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false }
    ],
    tags: ["television", "rene-barthelemy", "image", "media"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1932-paris-television",
    countryQid: "Q142", lang: "fr",
    itemKey: "capter-le-programme-experimental-paris-television",
    itemLabel: "capter le programme expérimental Paris Télévision",
    theme: "communication", gestureRoot: "paris_television",
    editorialScore: 78,
    objectType: "media", category: "media",
    releaseDate: "1932-12", releaseYear: 1932, datePrecision: "month",
    placeName: "103 rue de Grenelle, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Lancement du programme expérimental Paris Télévision",
    beforeState: "Avant fin 1932, les essais français de télévision restent ponctuels et sans rendez-vous régulier.",
    afterState: "À partir de décembre 1932, un programme expérimental d'une heure par semaine donne à la télévision française un premier rythme de diffusion.",
    objectChanged: "Tu peux tenter de capter un rendez-vous télévisé régulier, même encore expérimental et réservé à très peu de postes.",
    materialAnchor: "Récepteur expérimental, cadran et horaire de diffusion",
    sceneText: "Décembre 1932, rue de Grenelle. La television francaise commence a avoir une cadence, pas seulement des essais isoles. Une heure par semaine suffit deja a transformer l'invention en media en devenir.",
    fact: "À partir de décembre 1932, René Barthélemy met au point en France le programme expérimental Paris Télévision, diffusé environ une heure par semaine en 60 lignes.",
    sources: [
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false }
    ],
    tags: ["television", "paris-television", "grenelle", "media"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1933-air-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-lavion-avec-air-france",
    itemLabel: "prendre l'avion avec Air France",
    theme: "transport", gestureRoot: "air_france",
    editorialScore: 88,
    objectType: "service", category: "transport",
    releaseDate: "1933-10-07", releaseYear: 1933, datePrecision: "day",
    placeName: "Aéroport du Bourget, Le Bourget", placeType: "site", placeQid: null,
    triggerLabel: "Inauguration d'Air France",
    beforeState: "Avant octobre 1933, le transport aérien français reste morcelé entre plusieurs compagnies et réseaux hérités des pionniers.",
    afterState: "Après octobre 1933, Air France devient la compagnie nationale qui unifie l'offre aérienne française sous un même nom.",
    objectChanged: "Tu peux acheter un billet portant Air France plutôt que naviguer entre plusieurs compagnies aux noms et réseaux dispersés.",
    materialAnchor: "Billet imprimé, affiche Air France et piste du Bourget",
    sceneText: "7 octobre 1933, au Bourget. Le nom Air France s'impose d'un coup sur les billets, les affiches et le reseau. Pour le voyageur francais, l'aviation commerciale commence enfin a ressembler a un service national identifiable.",
    fact: "Le 7 octobre 1933, Air France est officiellement inaugurée au Bourget comme nouvelle compagnie nationale issue du regroupement des grands transporteurs français.",
    sources: [
      { label: "Air France", url: "https://corporate.airfrance.com/fr/le-decollage-1933-1945", authority: true },
      { label: "Air France 90 ans", url: "https://corporate.airfrance.com/fr/actualites/air-france-celebre-90-ans-delegance-travers-le-monde-entier", authority: true }
    ],
    tags: ["transport", "aviation", "air-france", "voyage"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1935-radiovision-ptt",
    countryQid: "Q142", lang: "fr",
    itemKey: "regarder-la-premiere-chaine-reguliere-francaise",
    itemLabel: "regarder la première chaîne régulière française",
    theme: "communication", gestureRoot: "radiovision_ptt",
    editorialScore: 90,
    objectType: "media", category: "media",
    releaseDate: "1935-04-26", releaseYear: 1935, datePrecision: "day",
    placeName: "103 rue de Grenelle, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Première émission officielle de Radio-PTT Vision",
    beforeState: "Avant le 26 avril 1935, la télévision française n'existe qu'en essais et démonstrations sans vraie chaîne régulière.",
    afterState: "Après le 26 avril 1935, la France dispose d'une première chaîne de télévision régulière, encore confidentielle mais identifiée.",
    objectChanged: "Tu peux suivre une émission télévisée française programmée depuis un studio dédié plutôt qu'une simple démonstration technique.",
    materialAnchor: "Studio de Grenelle, caméra et récepteur 60 lignes",
    sceneText: "26 avril 1935, rue de Grenelle. La television francaise entre dans le rythme d'une emission officielle. Ce n'est plus seulement un appareil qui fonctionne: c'est un programme, un horaire, une premiere forme de chaine.",
    fact: "Le 26 avril 1935, Radio-PTT Vision diffuse sa première émission officielle au 103 rue de Grenelle à Paris, acte de naissance de la première chaîne régulière française.",
    sources: [
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false },
      { label: "Radio-PTT Vision", url: "https://fr.wikipedia.org/wiki/Radio-PTT_Vision", authority: false }
    ],
    tags: ["television", "radio-ptt-vision", "grenelle", "media"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1936-air-france-dakar",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-lair-france-jusqua-dakar",
    itemLabel: "prendre Air France jusqu'à Dakar",
    theme: "transport", gestureRoot: "liaison_aerienne",
    editorialScore: 80,
    objectType: "service", category: "transport",
    releaseDate: "1936-05", releaseYear: 1936, datePrecision: "month",
    placeName: "Paris et Dakar", placeType: "country", placeQid: "Q142",
    triggerLabel: "Ouverture du service passagers Air France vers Dakar",
    beforeState: "Avant 1936, l'étape de Dakar sert surtout au courrier et les voyageurs ne disposent pas encore d'un service passagers régulier sur cette route.",
    afterState: "À partir de mai 1936, Dakar entre dans le réseau passagers d'Air France au départ de Paris.",
    objectChanged: "Tu peux acheter une place passager vers Dakar sur une liaison régulière là où la ligne servait surtout à la poste aérienne.",
    materialAnchor: "Billet Air France, couchette de train et avion Dewoitine",
    sceneText: "Mai 1936. La route vers Dakar ne sert plus seulement a faire passer du courrier: elle devient une ligne passagers signee Air France. Le voyage reste long, mais il change deja de statut pour le public francais.",
    fact: "En mai 1936, Air France ouvre un service passagers hebdomadaire de Paris vers Dakar, jusque-là essentiellement limité au courrier sur cette route.",
    sources: [
      { label: "Air France", url: "https://corporate.airfrance.com/en/news/1936-air-france-launches-passenger-flights-dakar", authority: true }
    ],
    tags: ["transport", "aviation", "dakar", "air-france"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1937-radiodiffusion-nationale-television",
    countryQid: "Q142", lang: "fr",
    itemKey: "capter-la-television-francaise-en-455-lignes",
    itemLabel: "capter la télévision française en 455 lignes",
    theme: "communication", gestureRoot: "television_455_lignes",
    editorialScore: 86,
    objectType: "media", category: "media",
    releaseDate: "1937-07-14", releaseYear: 1937, datePrecision: "day",
    placeName: "Tour Eiffel, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Début de Radiodiffusion nationale Télévision",
    beforeState: "Avant l'été 1937, la télévision française reste limitée à des définitions plus basses et à des essais encore fragiles.",
    afterState: "À partir du 14 juillet 1937, la télévision française bascule vers un émetteur 455 lignes à la tour Eiffel et des émissions plus régulières.",
    objectChanged: "Tu peux capter une image télévisée plus fine et plus stable depuis l'émetteur de la tour Eiffel.",
    materialAnchor: "Tour Eiffel, poste de télévision et image 455 lignes",
    sceneText: "14 juillet 1937, a Paris. La television francaise gagne en finesse, en puissance et en regularite depuis la tour Eiffel. Le media reste rare, mais son infrastructure prend enfin une forme durable et reconnaissable.",
    fact: "Le 14 juillet 1937, Radio-PTT Vision devient Radiodiffusion nationale Télévision et commence ses essais réguliers en 455 lignes depuis la tour Eiffel.",
    sources: [
      { label: "Radiodiffusion nationale Télévision", url: "https://fr.wikipedia.org/wiki/Radiodiffusion_nationale_T%C3%A9l%C3%A9vision", authority: false },
      { label: "Chronologie de la télévision française", url: "https://fr.wikipedia.org/wiki/Chronologie_de_la_t%C3%A9l%C3%A9vision_fran%C3%A7aise", authority: false }
    ],
    tags: ["television", "tour-eiffel", "455-lignes", "media"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1928-penicilline",
    countryQid: "Q142", lang: "fr",
    itemKey: "traiter-une-infection-avec-la-penicilline",
    itemLabel: "traiter une infection bactérienne avec la pénicilline",
    theme: "santé", gestureRoot: "penicilline",
    editorialScore: 96,
    objectType: "service", category: "service",
    releaseDate: "1928-09-28", releaseYear: 1928, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Découverte de la pénicilline par Alexander Fleming",
    beforeState: "Avant 1928, les infections bactériennes comme la septicémie sont souvent mortelles sans traitement efficace.",
    afterState: "Après 1928, la pénicilline ouvre la voie aux antibiotiques et change radicalement la médecine.",
    objectChanged: "Tu peux recevoir une injection d'antibiotique qui tue les bactéries là où rien n'existait avant.",
    materialAnchor: "Seringue, ampoule de pénicilline et ordonnance médicale",
    sceneText: "28 septembre 1928. En France, la nouvelle semble encore lointaine, mais l'idee est deja decisive: une substance peut enfin vaincre l'infection bacterienne. Dans les hopitaux francais, c'est l'horizon meme de la medecine qui commence a changer.",
    fact: "Le 28 septembre 1928, Alexander Fleming découvre la pénicilline, premier antibiotique de l'histoire.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/P%C3%A9nicilline", authority: false },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/medicine/1945/fleming/biographical/", authority: true }
    ],
    tags: ["sante", "antibiotique", "medecine", "infection"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1938-stylo-bille",
    countryQid: "Q142", lang: "fr",
    itemKey: "ecrire-avec-un-stylo-bille",
    itemLabel: "écrire avec un stylo à bille",
    theme: "communication", gestureRoot: "stylo_bille",
    editorialScore: 88,
    objectType: "device", category: "device",
    releaseDate: "1938-10-30", releaseYear: 1938, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Brevet du stylo à bille par László Bíró",
    beforeState: "Avant 1938, écrire en déplacement nécessite un stylo-plume avec cartouche d'encre qui tache et sèche.",
    afterState: "Après 1938, le stylo bille offre une écriture fiable, sans tache, qui ne nécessite pas de remplissage.",
    objectChanged: "Tu peux écrire sur n'importe quelle surface sans t'inquiéter des taches d'encre ou du séchage.",
    materialAnchor: "Stylo bille, papier et capuchon cliquable",
    sceneText: "1938. En France comme ailleurs, l'idee frappe par sa simplicite: une petite bille remplace la plume et l'encrier. Le geste d'ecrire se prepare a devenir plus propre, plus mobile et beaucoup moins fragile.",
    fact: "Le 30 octobre 1938, László Bíró dépose le brevet du stylo à bille, qui révolutionnera l'écriture quotidienne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Stylo_%C3%A0_bille", authority: false }
    ],
    tags: ["ecriture", "stylo", "biro", "papeterie"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1939-cnrs",
    countryQid: "Q142",
    lang: "fr",
    itemKey: "structurer-la-recherche-avec-le-cnrs",
    itemLabel: "structurer la recherche française avec le CNRS",
    theme: "travail",
    gestureRoot: "cnrs_recherche",
    editorialScore: 90,
    objectType: "service",
    category: "service",
    releaseDate: "1939-10-19",
    releaseYear: 1939,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Création du Centre national de la recherche scientifique (CNRS)",
    beforeState:
      "Avant octobre 1939, les laboratoires et financements de recherche restent morcelés entre plusieurs organismes et caisses.",
    afterState:
      "Après le décret du 19 octobre 1939, le CNRS coordonne la recherche scientifique française à l'échelle nationale.",
    objectChanged:
      "Tu peux rattacher un projet de laboratoire à un organisme public unique qui mutualise moyens et priorités.",
    materialAnchor: "Décret au Journal officiel, laboratoire et budget de recherche",
    sceneText:
      "19 octobre 1939, à Paris. Le décret crée le CNRS au pire moment géopolitique, mais l'ambition est claire : donner à la science française un cadre national pour coordonner laboratoires et financements. La recherche cesse d'être seulement une somme d'initiatives isolées.",
    fact: "Le 19 octobre 1939, un décret crée le Centre national de la recherche scientifique (CNRS) pour coordonner la recherche en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Centre_national_de_la_recherche_scientifique", authority: false },
      { label: "CNRS", url: "https://www.cnrs.fr/fr/le-cnrs/histoire", authority: true }
    ],
    tags: ["recherche", "cnrs", "science", "laboratoire"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1940-eau-lourde-joliot",
    countryQid: "Q142",
    lang: "fr",
    itemKey: "poursuivre-la-recherche-nucleaire-avec-de-leau-lourde",
    itemLabel: "poursuivre la recherche nucléaire avec du stock d'eau lourde",
    theme: "travail",
    gestureRoot: "eau_lourde_nucleaire",
    editorialScore: 86,
    objectType: "service",
    category: "service",
    releaseDate: "1940-03-09",
    releaseYear: 1940,
    datePrecision: "day",
    placeName: "Collège de France, Paris",
    placeType: "institution",
    placeQid: null,
    triggerLabel: "Acquisition du stock norvégien d'eau lourde pour la chaîne nucléaire française",
    beforeState:
      "Avant mars 1940, l'équipe de Frédéric Joliot-Curie manque de matière première pour prolonger les expériences sur la réaction en chaîne.",
    afterState:
      "Après l'achat du stock norvégien, la France dispose d'eau lourde stratégique pour poursuivre la recherche nucléaire au Collège de France.",
    objectChanged:
      "Tu peux continuer des montages expérimentaux qui exigent un modérateur rare, au lieu de rester bloqué faute de matière.",
    materialAnchor: "Flacons scellés, compteur Geiger et carnet de manipulations",
    sceneText:
      "9 mars 1940, à Paris. Le stock d'eau lourde acheté en Norvège arrive dans les labos du Collège de France : une matière rare qui permet de poursuivre les essais sur la réaction en chaîne. La recherche nucléaire française tient un levier technique décisif.",
    fact: "En mars 1940, le gouvernement français rachète à la Norsk Hydro le stock d'eau lourde nécessaire aux travaux de Joliot-Curie sur la réaction en chaîne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Joliot-Curie", authority: false },
      { label: "1939 en France", url: "https://fr.wikipedia.org/wiki/1939_en_France", authority: false }
    ],
    tags: ["physique", "nucleaire", "college-de-france", "recherche"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1944-le-monde",
    countryQid: "Q142",
    lang: "fr",
    itemKey: "lire-le-journal-le-monde-des-son-premier-numero",
    itemLabel: "lire le journal Le Monde dès son premier numéro",
    theme: "communication",
    gestureRoot: "presse_nationale",
    editorialScore: 88,
    objectType: "media",
    category: "media",
    releaseDate: "1944-12-18",
    releaseYear: 1944,
    datePrecision: "day",
    placeName: "Paris",
    placeType: "city",
    placeQid: "Q90",
    triggerLabel: "Parution du premier numéro du Monde",
    beforeState:
      "Avant fin 1944, la presse quotidienne nationale française reste fragmentée et marquée par l'Occupation ; un grand journal indépendant de référence ne s'impose pas encore.",
    afterState:
      "À partir du 18 décembre 1944, Le Monde offre une grande feuille quotidienne conçue comme un journal de référence, indépendant des partis.",
    objectChanged:
      "Tu peux acheter un quotidien national qui se présente dès l'origine comme un titre de fond, avec une maquette et une ambition éditoriale nouvelles.",
    materialAnchor: "Une une du Monde, kiosque parisien et encres du lendemain de la Libération",
    sceneText:
      "18 décembre 1944, Paris. Le premier numéro du Monde sort en kiosque : une grande page, une ambition de journal de référence, une ligne éditoriale affichée dès le départ. La presse nationale se redonne un titre qui compte pour le pays tout entier.",
    fact: "Le 18 décembre 1944 paraît le premier numéro du journal Le Monde, fondé par Hubert Beuve-Méry.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Le_Monde", authority: false },
      { label: "Le Monde", url: "https://www.lemonde.fr/", authority: true }
    ],
    tags: ["presse", "le-monde", "paris", "media", "1944"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1947-transistor",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-un-appareil-a-transistors",
    itemLabel: "utiliser un appareil électronique compact à transistors",
    theme: "communication", gestureRoot: "transistor",
    editorialScore: 90,
    objectType: "device", category: "device",
    releaseDate: "1947-12-16", releaseYear: 1947, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Invention du transistor par Bardeen, Brattain et Shockley",
    beforeState: "Avant 1947, les appareils électroniques fonctionnent avec des lampes à vide, lourdes, fragiles et chaleureuses.",
    afterState: "Après 1947, le transistor permet de miniaturiser tous les appareils électroniques.",
    objectChanged: "Tu peux porter un transistor radio dans ta poche au lieu de porter un poste lourd et encombrant.",
    materialAnchor: "Transistor radio, pile et oreillette",
    sceneText: "1947. En France, on ne le tient pas encore dans chaque poche, mais la promesse est deja claire: une electronique sans lampes, plus froide et plus petite. Les radios et les objets du quotidien vont retrecir jusque dans les foyers francais.",
    fact: "Le 16 décembre 1947, le transistor est inventé aux États-Unis par une équipe de Bell Telephone Laboratories, ouvrant la voie à toute l'électronique moderne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Transistor", authority: false },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/physics/1956/summary/", authority: true }
    ],
    tags: ["electronique", "radio", "transistor", "miniaturisation"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1949-reacteur-zoe",
    countryQid: "Q142",
    lang: "fr",
    itemKey: "suivre-la-recherche-nucleaire-civile-a-saclay",
    itemLabel: "suivre la recherche nucléaire civile autour du réacteur Zoé",
    theme: "travail",
    gestureRoot: "reacteur_zoe",
    editorialScore: 88,
    objectType: "infrastructure",
    category: "network",
    releaseDate: "1949-01-01",
    releaseYear: 1949,
    datePrecision: "year",
    placeName: "Fort de Châtillon, Saclay",
    placeType: "site",
    placeQid: null,
    triggerLabel: "Exploitation du réacteur nucléaire Zoé au Fort de Châtillon",
    beforeState:
      "Avant 1949, la France n'a pas encore stabilisé un premier réacteur nucléaire civil au service de la recherche fondamentale.",
    afterState:
      "En 1949, Zoé prolonge au quotidien la première criticité obtenue fin 1948 et ancre Saclay dans la recherche nucléaire.",
    objectChanged:
      "Tu peux mesurer des chaînages neutroniques sur un banc national plutôt que seulement sur des montages préparatoires isolés.",
    materialAnchor: "Bâtiment du réacteur, instrumentation et registre de criticité",
    sceneText:
      "1949, au Fort de Châtillon. Zoé tourne pour la science : le premier réacteur nucléaire français à criticité obtenue en 1948 devient un outil de recherche régulier. Les équipes mesurent, calibrent et préparent ce que sera la filière nucléaire nationale.",
    fact: "Le réacteur nucléaire Zoé, mis en criticité en décembre 1948 au Fort de Châtillon, est le premier réacteur nucléaire français ; son exploitation se poursuit en 1949 comme pilier de la recherche au CEA.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Zo%C3%A9_(r%C3%A9acteur)", authority: false },
      { label: "CEA", url: "https://www.cea.fr/", authority: true }
    ],
    tags: ["nucleaire", "cea", "saclay", "reacteur"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1949-deux-chevaux",
    countryQid: "Q142", lang: "fr",
    itemKey: "conduire-une-2cv",
    itemLabel: "conduire une 2CV Citroën",
    theme: "transport", gestureRoot: "deux_chevaux",
    editorialScore: 92,
    objectType: "device", category: "transport",
    releaseDate: "1948-10-07", releaseYear: 1948, datePrecision: "day",
    placeName: "Salon de l'automobile, Paris", placeType: "site", placeQid: null,
    triggerLabel: "Présentation de la 2CV Citroën au Salon de l'auto",
    beforeState: "Avant 1948, l'automobile reste hors de portée de la majorité des Français.",
    afterState: "Après 1948, la 2CV démocratise l'automobile avec un prix accessible à la classe ouvrière.",
    objectChanged: "Tu peux acheter une voiture neuve avec un salaire d'ouvrier et prendre la route avec ta famille.",
    materialAnchor: "2CV grise, capote rabattable et volant plat",
    sceneText: "7 octobre 1948, Salon de l'automobile. La petite voiture grise à la capote rabattable fait sensation. Elle ne coûte presque rien, consomme peu et tient sur les chemins de terre. La France ouvrière va enfin rouler.",
    fact: "Le 7 octobre 1948, la 2CV Citroën est présentée au Salon de l'automobile de Paris, démocratisant la voiture pour les Français.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Citro%C3%ABn_2CV", authority: false },
      { label: "Citroën", url: "https://www.citroen.fr/monde-citroen/heritage.html", authority: true }
    ],
    tags: ["voiture", "2cv", "citroen", "automobile"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1929-plan-young-franc",
    countryQid: "Q142", lang: "fr",
    itemKey: "accepter-les-conditions-du-plan-young",
    itemLabel: "accepter les conditions du Plan Young sur les réparations",
    theme: "travail", gestureRoot: "plan_young",
    editorialScore: 78,
    objectType: "service", category: "service",
    releaseDate: "1929-06-07", releaseYear: 1929, datePrecision: "day",
    placeName: "Paris", placeType: "institution", placeQid: "Q142",
    triggerLabel: "Signature du Plan Young à Paris sur les réparations allemandes",
    beforeState: "Avant juin 1929, le plan Dawes régit les réparations allemandes — un montant encore élevé et des échéances incertaines.",
    afterState: "Après le Plan Young, la somme des réparations est réduite et étalée sur 59 ans, allégeant la pression économique.",
    objectChanged: "Les économies européennes peuvent planifier plus sereinement leurs finances avec un calendrier de réparations révisé.",
    materialAnchor: "Documents signés, colonne de chiffres et manchettes de presse",
    sceneText: "7 juin 1929, Paris. Le Plan Young remplace le Plan Dawes. Les réparations allemandes sont réduites et étalées sur soixante ans. Pour la France, c'est une négociation diplomatico-financière qui allégerait l'instabilité européenne.",
    fact: "Le 7 juin 1929, le Plan Young est signé à Paris, révisant à la baisse les réparations de guerre imposées à l'Allemagne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Plan_Young", authority: false }
    ],
    tags: ["economie", "reparations", "plan-young", "diplomatie"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1930-ligne-maginot-construction",
    countryQid: "Q142", lang: "fr",
    itemKey: "financer-la-construction-de-la-ligne-maginot",
    itemLabel: "financer et construire la ligne Maginot",
    theme: "administration", gestureRoot: "ligne_maginot",
    editorialScore: 82,
    objectType: "infrastructure", category: "device",
    releaseDate: "1930-01-14", releaseYear: 1930, datePrecision: "day",
    placeName: "Frontière franco-allemande, Alsace-Lorraine", placeType: "site", placeQid: null,
    triggerLabel: "Vote du crédit de 3 milliards pour la ligne Maginot",
    beforeState: "Avant 1930, la frontière franco-allemande n'est défendue que par des fortifications vieillissantes.",
    afterState: "Après le vote du 14 janvier 1930, la France engage la construction de la plus grande ligne de fortification moderne d'Europe.",
    objectChanged: "La France dispose d'une ligne de défense souterraine et bétonée longue de centaines de kilomètres sur sa frontière est.",
    materialAnchor: "Ouvrage fortifié, couloir souterrain et casemate bétonnée",
    sceneText: "Janvier 1930. La loi vote 3 milliards de francs. Les chantiers s'ouvrent le long de la frontière franco-allemande. Des milliers d'ouvriers creusent, bétonnent, installent des coupoles. La France construit ce qu'elle croit être un rempart définitif.",
    fact: "Le 14 janvier 1930, la loi allouant les crédits pour la ligne Maginot est votée, lançant la construction de la plus grande fortification de l'Europe d'entre-deux-guerres.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Ligne_Maginot", authority: false }
    ],
    tags: ["maginot", "fortification", "defense", "frontiere"],
    quality: { strictPlace: true, strictDate: true, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1941-requisitions-et-marche-noir",
    countryQid: "Q142", lang: "fr",
    itemKey: "se-debrouiller-avec-les-tickets-de-rationnement",
    itemLabel: "se débrouiller avec les tickets de rationnement sous l'Occupation",
    theme: "maison", gestureRoot: "rationnement_occupation",
    editorialScore: 84,
    objectType: "service", category: "service",
    releaseDate: "1940-09-01", releaseYear: 1941, datePrecision: "year",
    placeName: "Épiceries et marchés, France occupée", placeType: "country", placeQid: "Q142",
    triggerLabel: "Généralisation du rationnement alimentaire sous l'Occupation",
    beforeState: "Avant l'Occupation, les Français font leurs courses librement selon leurs moyens.",
    afterState: "Dès l'automne 1940, les cartes et tickets de rationnement conditionnent l'accès à la nourriture, au charbon et à l'habillement.",
    objectChanged: "Tu dois présenter tes tickets de rationnement pour acheter pain, sucre, beurre ou viande — et gérer pénurie et troc.",
    materialAnchor: "Carnet de tickets, comptoir de l'épicier et queue devant la boulangerie",
    sceneText: "1941, épicerie française. Les étagères sont à moitié vides. Tu présentes tes tickets pour un peu de beurre et de sucre. Derrière le comptoir, l'épicier coupe les coupons. La vie quotidienne se mesure en points de rationnement.",
    fact: "Dès 1940, le régime de Vichy organise le rationnement alimentaire en France occupée : pain, sucre, viande et charbon sont distribués par tickets.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Rationnement_alimentaire_en_France_(1939-1949)", authority: false }
    ],
    tags: ["rationnement", "occupation", "guerre", "alimentation"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1942-debarquement-allies-afrique-nord",
    countryQid: "Q142", lang: "fr",
    itemKey: "apprendre-le-debarquement-allie-en-afrique-du-nord",
    itemLabel: "apprendre le débarquement allié en Afrique du Nord",
    theme: "administration", gestureRoot: "debarquement_afn",
    editorialScore: 82,
    objectType: "service", category: "service",
    releaseDate: "1942-11-08", releaseYear: 1942, datePrecision: "day",
    placeName: "Algérie et Maroc français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Opération Torch — débarquement allié en Afrique du Nord française",
    beforeState: "Avant novembre 1942, l'Afrique du Nord française reste sous contrôle de Vichy.",
    afterState: "Après l'opération Torch, l'Afrique du Nord bascule progressivement dans le camp allié.",
    objectChanged: "Les populations d'Afrique du Nord française voient des soldats américains et britanniques sur leur sol — le vent tourne.",
    materialAnchor: "Carte militaire, drapeaux alliés et annonce radiophonique",
    sceneText: "8 novembre 1942. Des soldats américains et britanniques débarquent en Algérie et au Maroc. L'opération Torch ouvre un nouveau front. Pour la France libre, c'est le signe que la libération est possible.",
    fact: "Le 8 novembre 1942, l'opération Torch voit les Alliés débarquer en Afrique du Nord française, retournant la situation en faveur des Alliés.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Op%C3%A9ration_Torch", authority: false }
    ],
    tags: ["guerre", "allies", "debarquement", "afrique-du-nord"],
    quality: { strictPlace: false, strictDate: true, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1943-milice-sto-organisation",
    countryQid: "Q142", lang: "fr",
    itemKey: "eviter-le-service-du-travail-obligatoire-sto",
    itemLabel: "éviter ou subir le Service du travail obligatoire (STO)",
    theme: "travail", gestureRoot: "sto_travail_obligatoire",
    editorialScore: 84,
    objectType: "service", category: "service",
    releaseDate: "1943-02-16", releaseYear: 1943, datePrecision: "day",
    placeName: "France occupée", placeType: "country", placeQid: "Q142",
    triggerLabel: "Instauration du Service du travail obligatoire (STO)",
    beforeState: "Avant le 16 février 1943, certains Français partent volontairement travailler en Allemagne.",
    afterState: "Après la création du STO, des centaines de milliers de Français sont contraints de travailler dans les usines allemandes.",
    objectChanged: "Tu risques d'être convoqué au STO et d'être envoyé travailler en Allemagne sous peine d'emprisonnement.",
    materialAnchor: "Convocation STO, carte d'identité et usine allemande",
    sceneText: "16 février 1943. La loi STO est signée. Des jeunes hommes reçoivent des convocations. Certains partent en Allemagne ; d'autres rejoignent le maquis pour échapper à la réquisition. Le STO alimente la Résistance autant qu'il pille la main-d'œuvre française.",
    fact: "Le 16 février 1943, le Service du travail obligatoire (STO) est instauré en France, envoyant des centaines de milliers de travailleurs en Allemagne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Service_du_travail_obligatoire", authority: false }
    ],
    tags: ["sto", "occupation", "travail", "guerre"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1945-plan-monnet-reconstruction",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-la-france-se-reconstruire-sous-le-plan-monnet",
    itemLabel: "voir la France se reconstruire sous le Plan Monnet",
    theme: "travail", gestureRoot: "plan_monnet",
    editorialScore: 84,
    objectType: "service", category: "service",
    releaseDate: "1946-01-03", releaseYear: 1945, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Création du Commissariat général du Plan (Plan Monnet)",
    beforeState: "Avant 1946, la France sort dévastée de la guerre sans stratégie économique nationale coordonnée.",
    afterState: "Après le plan Monnet, la France dispose d'un cadre de reconstruction planifiée qui guidera les Trente Glorieuses.",
    objectChanged: "Les entreprises et les ménages peuvent espérer une reconstruction ordonnée avec des priorités définies par l'État.",
    materialAnchor: "Rapport du Plan, usine en reconstruction et carte des chantiers",
    sceneText: "Janvier 1946. Jean Monnet prend la tête du Commissariat général du Plan. L'État fixe des priorités de reconstruction : industrie lourde, transports, énergie. Les Trente Glorieuses commencent ici, dans un bureau, avec un tableau de bord.",
    fact: "Le 3 janvier 1946, le Commissariat général du Plan est créé sous la direction de Jean Monnet, posant les bases de la reconstruction économique française.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Plan_Monnet", authority: false }
    ],
    tags: ["reconstruction", "plan-monnet", "economie", "trente-glorieuses"],
    quality: { strictPlace: false, strictDate: true, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1946-electricite-nationalisation",
    countryQid: "Q142", lang: "fr",
    itemKey: "payer-son-electricite-a-edf",
    itemLabel: "payer son électricité à EDF après la nationalisation",
    theme: "science", gestureRoot: "nationalisation_edf",
    editorialScore: 86,
    objectType: "infrastructure", category: "service",
    releaseDate: "1946-04-08", releaseYear: 1946, datePrecision: "day",
    placeName: "Foyers français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Nationalisation de l'électricité et création d'EDF",
    beforeState: "Avant le 8 avril 1946, l'électricité est distribuée par des centaines de sociétés privées avec des tarifs disparates.",
    afterState: "Après la nationalisation, EDF unifie la distribution et les tarifs de l'électricité dans toute la France.",
    objectChanged: "Tu reçois une facture EDF avec un tarif unifié, quel que soit le village ou la ville où tu habites.",
    materialAnchor: "Compteur électrique, facture EDF et pylône à haute tension",
    sceneText: "8 avril 1946. La loi nationalise l'électricité et crée EDF. Désormais un seul organisme fournit le courant à toute la France. La facture s'unifie. Pour des millions de foyers ruraux mal desservis, la promesse d'un accès égal à l'électricité.",
    fact: "Le 8 avril 1946, la loi nationalise l'électricité française et crée EDF, unifiant la distribution sous un monopole public.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/%C3%89lectricit%C3%A9_de_France", authority: false },
      { label: "EDF", url: "https://www.edf.fr/groupe-edf/nos-energies/histoire", authority: true }
    ],
    tags: ["electricite", "edf", "nationalisation", "energie"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
];
