import type { InventionEntry } from "../../../types";

export const FR_INVENTION_BACKFILL_1970_1989: InventionEntry[] = [
  {
    id: "fr-1970-cii-ordinateur-plan-calcul",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-un-ordinateur-cii-plan-calcul",
    itemLabel: "utiliser un ordinateur de la CII (Plan calcul)",
    theme: "travail", gestureRoot: "plan_calcul_cii",
    editorialScore: 82,
    objectType: "device", category: "device",
    releaseDate: "1970-01-01", releaseYear: 1970, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Production en série des ordinateurs CII dans le cadre du Plan calcul",
    beforeState: "Avant 1970, la France dépend des ordinateurs IBM pour la quasi-totalité de son traitement de données.",
    afterState: "À partir de 1970, la CII commercialise des ordinateurs 100 % français, fruits du Plan calcul.",
    objectChanged: "Des grandes administrations et entreprises peuvent s'équiper d'ordinateurs fabriqués en France.",
    materialAnchor: "Unité centrale CII Iris, bande magnétique et salle climatisée",
    sceneText: "1970, salle informatique d'une grande administration. Les armoires portent le logo CII. Résultat du Plan calcul lancé par de Gaulle, les premiers ordinateurs français de série réduisent la dépendance à IBM. L'indépendance technologique prend une forme concrète.",
    fact: "Dans les années 1970, la CII (Compagnie internationale pour l'informatique) commercialise les premiers ordinateurs entièrement français, issus du Plan calcul.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Plan_Calcul", authority: false }
    ],
    tags: ["informatique", "plan-calcul", "cii", "technologie-nationale"],
    quality: { strictPlace: false, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1976-concorde-vol-commercial",
    countryQid: "Q142", lang: "fr",
    itemKey: "monter-dans-le-concorde-paris-new-york",
    itemLabel: "monter dans le Concorde entre Paris et New York",
    theme: "transport", gestureRoot: "concorde",
    editorialScore: 90,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1976-01-21", releaseYear: 1976, datePrecision: "day",
    placeName: "Aéroport de Roissy CDG, Paris", placeType: "site", placeQid: "Q90600",
    triggerLabel: "Entrée en service commercial du Concorde (premiers vols passagers)",
    beforeState: "Avant les années 1970, traverser l'Atlantique prend plus de sept heures en avion de ligne.",
    afterState: "Avec le Concorde, la traversée Paris-New York peut se faire en 3h30 à deux fois la vitesse du son.",
    objectChanged: "Tu peux théoriquement traverser l'Atlantique avant même d'être arrivé à destination selon l'heure locale.",
    materialAnchor: "Fuselage blanc effilé, hublots ovales et cockpit supersonique",
    sceneText: "1976, aéroport de Roissy. L'engin blanc et effilé s'élance. Trois heures trente plus tard, New York. Deux fois la vitesse du son. Le Concorde transforme le temps de traversée en exploit de vitesse — symbole de la coopération franco-britannique et du savoir-faire aéronautique.",
    fact: "Le Concorde, fruit de la coopération franco-britannique, entre en service commercial en 1976 avec des liaisons Paris-New York et Londres-New York.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Concorde", authority: false },
      { label: "Air France", url: "https://www.airfranceklm.com/fr/news/histoire-du-concorde", authority: true }
    ],
    tags: ["concorde", "aviation", "supersonique", "transatlantique"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1973-premiere-chaine-couleur",
    countryQid: "Q142", lang: "fr",
    itemKey: "regarder-la-television-en-couleur",
    itemLabel: "regarder la télévision en couleur sur TF1 ou Antenne 2",
    theme: "loisirs", gestureRoot: "tele_couleur",
    editorialScore: 86,
    objectType: "device", category: "media",
    releaseDate: "1975-01-06", releaseYear: 1973, datePrecision: "year",
    placeName: "Salon familial, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Généralisation de la télévision couleur en France",
    beforeState: "Avant 1973, la plupart des Français regardent la télévision en noir et blanc.",
    afterState: "Dans les années 1973-1976, la télévision couleur SECAM se généralise dans les foyers français.",
    objectChanged: "Tu peux regarder le journal télévisé et voir les visages, les drapeaux et les paysages en couleur pour la première fois.",
    materialAnchor: "Téléviseur couleur à boutons, antenne intérieure et programme TV",
    sceneText: "1973, salon. Le téléviseur couleur trône dans le coin. Les visages du JT ont maintenant une couleur de peau, les pelouses de football sont vertes. La transition du noir et blanc à la couleur ne se fait pas en un jour — mais elle change tout.",
    fact: "Dans les années 1970, la télévision couleur (norme SECAM) se diffuse dans les foyers français, transformant le rapport à l'image télévisée.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9vision_en_couleur_en_France", authority: false },
      { label: "INA", url: "https://www.ina.fr/ina-eclaire-actu/la-couleur-a-la-television-1967-1975", authority: true }
    ],
    tags: ["television", "couleur", "secam", "medias"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1974-carte-puce-roland-moreno",
    countryQid: "Q142", lang: "fr",
    itemKey: "inventer-la-carte-a-puce-roland-moreno",
    itemLabel: "brevet de la carte à puce par Roland Moreno",
    theme: "travail", gestureRoot: "carte_puce_invention",
    editorialScore: 90,
    objectType: "device", category: "payment",
    releaseDate: "1974-03-14", releaseYear: 1974, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Dépôt du brevet de la carte à mémoire par Roland Moreno",
    beforeState: "Avant 1974, aucune carte portable ne peut stocker et traiter des informations de manière sécurisée.",
    afterState: "Après le 14 mars 1974, le brevet de Moreno pose les bases de la carte à puce qui équipera des milliards de personnes.",
    objectChanged: "Le principe technologique qui permettra plus tard d'insérer une puce dans une carte bancaire ou une SIM vient d'être inventé en France.",
    materialAnchor: "Schéma de brevet, prototype de carte et circuit intégré",
    sceneText: "14 mars 1974, France. Roland Moreno dépose le brevet d'une carte portant un circuit intégré. L'idée semble anecdotique — elle va équiper des milliards de cartes bancaires, SIM, et passeports dans le monde entier.",
    fact: "Le 14 mars 1974, l'inventeur français Roland Moreno dépose le brevet fondateur de la carte à puce.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Roland_Moreno", authority: false },
      { label: "INPI", url: "https://www.inpi.fr/", authority: true }
    ],
    tags: ["carte-puce", "invention", "moreno", "brevet"],
    quality: { strictPlace: false, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1975-loi-informatique-projet",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-le-rapport-nora-minc-sur-informatique",
    itemLabel: "préparer la société française à l'informatisation (rapport Nora-Minc)",
    theme: "travail", gestureRoot: "rapport_nora_minc",
    editorialScore: 80,
    objectType: "service", category: "service",
    releaseDate: "1978-01-01", releaseYear: 1975, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Débats sur l'informatisation de la société et rapport Nora-Minc",
    beforeState: "Avant 1975, la question de l'impact de l'informatique sur la société n'est pas encore une priorité politique.",
    afterState: "Dans la seconde moitié des années 1970, la France débat activement de son avenir numérique et commande un rapport stratégique.",
    objectChanged: "Les décideurs et citoyens peuvent lire un diagnostic officiel sur ce que l'informatique va changer dans leur vie quotidienne.",
    materialAnchor: "Rapport imprimé, ordinateur de bureau et salle de réunion ministérielle",
    sceneText: "Années 1975-1978, ministère. Le rapport Nora-Minc est en préparation. La question n'est plus de savoir si l'informatique va changer la société, mais comment. La France commence à planifier sa transition numérique — dix ans avant les autres.",
    fact: "Le rapport Nora-Minc (1978) est commandé au milieu des années 1970 pour anticiper l'informatisation de la société française.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Rapport_Nora-Minc", authority: false }
    ],
    tags: ["informatique", "numerique", "rapport", "politique"],
    quality: { strictPlace: false, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1977-centrale-nucleaire-fessenheim",
    countryQid: "Q142", lang: "fr",
    itemKey: "consommer-electricite-nucleaire-fessenheim",
    itemLabel: "consommer de l'électricité produite par la centrale nucléaire de Fessenheim",
    theme: "travail", gestureRoot: "nucleaire_fessenheim",
    editorialScore: 88,
    objectType: "infrastructure", category: "device",
    releaseDate: "1977-04-01", releaseYear: 1977, datePrecision: "year",
    placeName: "Fessenheim, Alsace", placeType: "site", placeQid: null,
    triggerLabel: "Mise en service de la centrale nucléaire de Fessenheim (premier réacteur)",
    beforeState: "Avant 1977, la France produit son électricité surtout par des barrages hydroélectriques et des centrales thermiques.",
    afterState: "Après la mise en service de Fessenheim, l'électricité nucléaire entre dans les prises des foyers alsaciens, puis français.",
    objectChanged: "L'électricité qui alimente ta maison peut venir d'une fission d'atomes d'uranium à Fessenheim.",
    materialAnchor: "Dôme de réacteur, pylônes à haute tension et compteur EDF",
    sceneText: "1977, Fessenheim. Le premier réacteur est couplé au réseau. L'électricité nucléaire commence à circuler dans les foyers. La France vient de choisir son modèle énergétique pour un demi-siècle.",
    fact: "En 1977, la centrale nucléaire de Fessenheim (Alsace) est couplée au réseau électrique — la première centrale de puissance entièrement nucléaire en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Centrale_nucl%C3%A9aire_de_Fessenheim", authority: false },
      { label: "EDF", url: "https://www.edf.fr/groupe-edf/nos-energies/nucleaire", authority: true }
    ],
    tags: ["nucleaire", "electricite", "fessenheim", "energie"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1978-bicentenaire-vaccin-variole",
    countryQid: "Q142", lang: "fr",
    itemKey: "ne-plus-etre-vaccine-contre-la-variole",
    itemLabel: "ne plus être obligé de se vacciner contre la variole",
    theme: "santé", gestureRoot: "vaccination_variole_fin",
    editorialScore: 82,
    objectType: "service", category: "service",
    releaseDate: "1979-12-09", releaseYear: 1978, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Fin de la vaccination obligatoire contre la variole en France",
    beforeState: "Avant 1979, tout enfant français doit être vacciné contre la variole — une pratique en vigueur depuis Napoléon.",
    afterState: "Après l'éradication mondiale de la variole déclarée par l'OMS, la vaccination n'est plus imposée.",
    objectChanged: "Tu n'as plus à montrer ton carnet de vaccin avec la marque de variole pour entrer à l'école.",
    materialAnchor: "Carnet de santé, cicatrice vaccinale et décret ministériel",
    sceneText: "1979, école. Plus besoin de montrer la marque au bras. La France lève l'obligation de vaccination contre la variole, maladie éradiquée. C'est la première fois dans l'histoire qu'une maladie humaine est définitivement vaincue.",
    fact: "En 1979, la France met fin à la vaccination obligatoire contre la variole, après que l'OMS a déclaré la maladie éradiquée en mai 1980.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/%C3%89radication_de_la_variole", authority: false },
      { label: "OMS", url: "https://www.who.int/fr/news-room/fact-sheets/detail/smallpox", authority: true }
    ],
    tags: ["sante", "vaccination", "variole", "eradication"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1980-scanner-radiologie-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "passer-un-scanner-radiologique-en-france",
    itemLabel: "passer un scanner radiologique dans un grand CHU français",
    theme: "santé", gestureRoot: "scanner_chu_france",
    editorialScore: 84,
    objectType: "device", category: "device",
    releaseDate: "1980-01-01", releaseYear: 1980, datePrecision: "year",
    placeName: "CHU, France", placeType: "institution", placeQid: null,
    triggerLabel: "Déploiement du scanner (tomodensitomètre) dans les CHU français",
    beforeState: "Avant 1980, le scanner médical est une rareté en France, réservé à quelques centres pionniers.",
    afterState: "À partir de 1980, les grands CHU français s'équipent progressivement et le scanner devient un outil diagnostique standard.",
    objectChanged: "Tu peux être envoyé en scanner par ton médecin dans un hôpital public sans que ce soit exceptionnel.",
    materialAnchor: "Anneau scanner, table d'examen et images en coupe",
    sceneText: "1980, service de radiologie d'un CHU. La table glisse dans l'anneau. Les coupes s'affichent. Ce qui n'existait pas en France il y a dix ans est devenu un outil ordinaire du diagnostic médical. L'imagerie en coupe entre dans la médecine courante.",
    fact: "Dans les années 1980, les CHU français déploient massivement le scanner médical, généralisant l'imagerie en coupe dans la pratique hospitalière.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Tomodensitom%C3%A9trie", authority: false }
    ],
    tags: ["scanner", "sante", "imagerie", "chu"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1977-ariane-programme",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-le-lanceur-ariane-se-preparer",
    itemLabel: "voir le lanceur européen Ariane se préparer",
    theme: "travail", gestureRoot: "ariane_lanceur",
    editorialScore: 88,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1979-12-24", releaseYear: 1977, datePrecision: "year",
    placeName: "Centre spatial guyanais, Kourou", placeType: "site", placeQid: null,
    triggerLabel: "Mise au point du lanceur européen Ariane sous leadership français",
    beforeState: "Avant 1977, l'Europe dépend des États-Unis ou de l'URSS pour lancer ses satellites.",
    afterState: "Le programme Ariane, sous impulsion française, aboutit en 1979 au premier vol d'Ariane 1.",
    objectChanged: "L'Europe dispose de sa propre fusée pour lancer des satellites — une autonomie stratégique acquise grâce à la France.",
    materialAnchor: "Fusée Ariane, tour de lancement et logo ESA-CNES",
    sceneText: "1977-1979, Kourou. Les ingénieurs d'Arianespace mettent au point le lanceur européen. Financé en grande partie par la France, Ariane vole pour la première fois en décembre 1979 et change la donne pour l'accès à l'espace.",
    fact: "Le programme Ariane, lancé en 1973 sous impulsion française, débouche en 1979 sur le premier vol d'Ariane 1 — premier lanceur spatial européen.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Ariane_(fus%C3%A9e)", authority: false },
      { label: "CNES", url: "https://cnes.fr/fr/ariane", authority: true }
    ],
    tags: ["ariane", "espace", "fusee", "kourou"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1979-carte-vitale-puce-brevet",
    countryQid: "Q142", lang: "fr",
    itemKey: "recevoir-une-carte-de-paiement-a-puce-en-banque",
    itemLabel: "recevoir une carte bancaire à puce",
    theme: "communication", gestureRoot: "carte_bancaire_puce",
    editorialScore: 84,
    objectType: "payment_tool", category: "payment",
    releaseDate: "1979-01-01", releaseYear: 1979, datePrecision: "year",
    placeName: "Banques françaises", placeType: "institution", placeQid: "Q142",
    triggerLabel: "Développement du système de paiement par carte à puce en France",
    beforeState: "Avant 1979, les cartes bancaires utilisent une piste magnétique facilement copiable et peu sécurisée.",
    afterState: "À partir des expérimentations de 1979-1982, les banques françaises déploient la carte à puce — une première mondiale.",
    objectChanged: "Tu insères ta carte dans un lecteur et une puce remplace la signature : plus sécurisé, plus rapide.",
    materialAnchor: "Carte à puce, lecteur de puce et imprimante de relevé",
    sceneText: "1979, banque française. Les ingénieurs testent une carte avec un petit circuit doré. La piste magnétique est trop facile à copier. La puce, invention de Roland Moreno, rend la fraude impossible. La France va équiper ses cartes avant tout le monde.",
    fact: "En 1979-1982, la France expérimente puis déploie les premières cartes bancaires à puce au monde, basées sur le brevet de Roland Moreno.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Carte_%C3%A0_puce", authority: false }
    ],
    tags: ["carte", "puce", "banque", "paiement"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1986-tva-privatisations",
    countryQid: "Q142", lang: "fr",
    itemKey: "acheter-des-actions-d-une-entreprise-privatisee",
    itemLabel: "acheter des actions d'une entreprise privatisée",
    theme: "travail", gestureRoot: "privatisations_1986",
    editorialScore: 82,
    objectType: "service", category: "service",
    releaseDate: "1986-07-01", releaseYear: 1986, datePrecision: "year",
    placeName: "Bourse de Paris", placeType: "institution", placeQid: null,
    triggerLabel: "Vague de privatisations sous le gouvernement Chirac (1986)",
    beforeState: "Avant 1986, la plupart des grandes entreprises françaises (TF1, Saint-Gobain, Paribas…) sont nationalisées.",
    afterState: "Après 1986, les privatisations ouvrent le capital de grandes entreprises au grand public.",
    objectChanged: "Tu peux acheter des actions de Saint-Gobain, de Paribas ou de TF1 à la Bourse — pour la première fois pour des millions de Français.",
    materialAnchor: "Carnet d'actionnaire, cours de bourse et prospectus d'introduction",
    sceneText: "1986, agence bancaire. Des millions de Français achètent pour la première fois des actions. Les privatisations ouvrent le capital des grandes entreprises. Une France actionnaire fait son apparition — symboliquement au moins.",
    fact: "En 1986-1988, le gouvernement Chirac lance une vague de privatisations (Saint-Gobain, Paribas, TF1…) qui popularise la détention d'actions.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Privatisation_en_France", authority: false }
    ],
    tags: ["privatisation", "bourse", "actions", "economie"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1989-mur-berlin-france-reaction",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-la-chute-du-mur-de-berlin-en-direct-a-la-television",
    itemLabel: "voir la chute du Mur de Berlin à la télévision française",
    theme: "administration", gestureRoot: "chute_mur_berlin",
    editorialScore: 90,
    objectType: "service", category: "service",
    releaseDate: "1989-11-09", releaseYear: 1989, datePrecision: "day",
    placeName: "Salons et cafés, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Chute du Mur de Berlin — diffusion en direct sur les télévisions françaises",
    beforeState: "Avant le 9 novembre 1989, l'Europe est coupée en deux par le Rideau de fer depuis 1961.",
    afterState: "Après la chute du Mur, la réunification allemande et la fin de la guerre froide reconfigurent la géopolitique européenne.",
    objectChanged: "Tu peux regarder à la télévision des citoyens qui démolissent à la pioche le symbole de la division de l'Europe.",
    materialAnchor: "Écran de télévision, marteau sur le mur et foule berlinoise",
    sceneText: "9 novembre 1989, France. Les téléviseurs montrent des images de Berlin. Des gens frappent le mur à coups de marteau. Les gardes ne tirent pas. L'Europe vient de changer. La guerre froide — dont la France est un enjeu majeur — touche à sa fin.",
    fact: "Le 9 novembre 1989, la chute du Mur de Berlin est diffusée en direct sur les télévisions françaises, marquant la fin de la guerre froide.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Chute_du_mur_de_Berlin", authority: false }
    ],
    tags: ["berlin", "mur", "histoire", "europe"],
    quality: { strictPlace: false, strictDate: true, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1971-scanner-medical",
    countryQid: "Q142", lang: "fr",
    itemKey: "passer-un-scanner",
    itemLabel: "passer un scanner médical",
    theme: "santé", gestureRoot: "scanner_medical",
    editorialScore: 88,
    objectType: "device", category: "device",
    releaseDate: "1971-10-01", releaseYear: 1971, datePrecision: "month",
    placeName: "Hôpital Atkinson Morley, Londres", placeType: "site", placeQid: null,
    triggerLabel: "Premier scanner médical (tomodensitomètre) utilisé cliniquement",
    beforeState: "Avant 1971, voir l'intérieur du corps en coupes fines sans ouvrir le patient reste inaccessible en routine hospitalière, en France comme ailleurs.",
    afterState: "Après les premiers examens à Londres puis la diffusion de la technique, les grands CHU français s'équipent à leur tour dans les années 1970.",
    objectChanged: "Tu peux t'allonger dans un anneau et obtenir des coupes du corps sans chirurgie ouverte — une pratique qui gagne les hôpitaux français après les premiers essais outre-Manche.",
    materialAnchor: "Table de scanner, anneau rotatif et images en coupe",
    sceneText: "Octobre 1971, Londres. À l'hôpital Atkinson Morley, le premier tomodensitomètre d'EMI transforme un crâne en couches de densité. L'invention de Godfrey Hounsfield révolutionne la radiologie ; dans les années suivantes, la France aligne ses centres hospitaliers sur cette nouvelle norme d'imagerie.",
    fact: "En octobre 1971, le premier scanner médical est utilisé cliniquement à Londres ; la France déploie ensuite ses premiers appareils dans les grands CHU.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Tomodensitom%C3%A9trie", authority: false },
      { label: "Fondation Nobel (Hounsfield)", url: "https://www.nobelprize.org/prizes/medicine/1979/hounsfield/biographical/", authority: true }
    ],
    tags: ["sante", "scanner", "imagerie", "medecine", "londres"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1972-tgv-001-prototype-essais",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-le-tgv-001-en-essais-grande-vitesse",
    itemLabel: "voir le TGV 001 en essais à grande vitesse sur le réseau français",
    theme: "transport", gestureRoot: "tgv_prototype_001",
    editorialScore: 87,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1972-12-08", releaseYear: 1972, datePrecision: "day",
    placeName: "Réseau SNCF (lignes d'essais), France", placeType: "country", placeQid: "Q142",
    editorialCluster: "tgv_001_prototype_1972",
    triggerLabel: "Essais du turbotrain expérimental TGV 001 (records de vitesse sur lignes classiques)",
    beforeState: "Avant 1972, aucune rame française ne dépasse systématiquement 200 km/h sur lignes classiques pour préparer un futur réseau grande vitesse.",
    afterState: "En 1972, le TGV 001 enchaîne les essais et fixe un record mondial pour un automoteur — preuve de faisabilité du futur TGV.",
    objectChanged: "Tu peux suivre dans la presse et les essais SNCF une rame orange et grise qui pousse les limites du ferroviaire avant la ligne dédiée Paris–Lyon.",
    materialAnchor: "Rame TGV 001, voie d'essai et chronomètre de vitesse",
    sceneText: "1972, France. Le TGV 001 quitte Belfort pour enchaîner essais et expositions. En décembre, la rame frôle les 320 km/h sur rail : ce n'est pas encore le service voyageurs, mais le futur TGV est déjà en train de naître sur les lignes existantes.",
    fact: "En 1972, le turbotrain expérimental TGV 001 de la SNCF bat plusieurs records de vitesse sur le réseau français, préfigurant le TGV commercial.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/TGV_001", authority: false },
      { label: "SNCF — Histoire du TGV", url: "https://www.sncf.com/fr/groupe/histoire-du-groupe/histoire-tgv", authority: true }
    ],
    tags: ["tgv", "sncf", "grande-vitesse", "essais", "1972"],
    quality: { strictPlace: false, strictDate: true, everydayUse: false, sourceCount: 2 }
  },
  {
    id: "fr-1979-tgv-paris-lyon",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-le-tgv",
    itemLabel: "prendre le TGV entre Paris et Lyon",
    theme: "transport", gestureRoot: "tgv",
    editorialScore: 94,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1981-09-27", releaseYear: 1981, datePrecision: "day",
    placeName: "Paris — Gare de Lyon", placeType: "site", placeQid: "Q746273",
    triggerLabel: "Inauguration de la ligne Paris-Lyon du TGV",
    beforeState: "Avant septembre 1981, Paris-Lyon prend 3h40 en train rapide.",
    afterState: "Après septembre 1981, le TGV relie Paris à Lyon en 2h40, puis en 2h en 1983.",
    objectChanged: "Tu peux aller à Lyon le matin, déjeuner sur place et rentrer à Paris le soir.",
    materialAnchor: "TGV orange, quai de départ et indicateur de vitesse",
    sceneText: "27 septembre 1981, gare de Lyon. Le train orange glisse sans bruit au départ. Deux heures quarante plus tard, Lyon. La France vient de changer d'échelle — les distances rétrécissent.",
    fact: "Le 27 septembre 1981, la ligne TGV Paris-Lyon est inaugurée, portant la France à la pointe du train à grande vitesse.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Ligne_%C3%A0_grande_vitesse_Paris%E2%80%93Lyon", authority: false },
      { label: "SNCF", url: "https://www.sncf.com/fr/groupe/histoire-du-groupe/histoire-tgv", authority: true }
    ],
    tags: ["tgv", "train", "paris", "lyon"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1983-carte-vitale-precurseur",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-une-carte-a-puce",
    itemLabel: "utiliser une carte à puce dans la vie quotidienne",
    theme: "communication", gestureRoot: "carte_a_puce",
    editorialScore: 88,
    objectType: "payment_tool", category: "payment",
    releaseDate: "1982-01-01", releaseYear: 1982, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Déploiement de la carte à puce bancaire en France",
    beforeState: "Avant 1982, les cartes bancaires françaises utilisent une piste magnétique facilement copiable.",
    afterState: "Après 1982, la France est le premier pays au monde à déployer massivement la carte bancaire à puce.",
    objectChanged: "Tu pagues avec une carte dont la puce est plus sûre que la piste magnétique — une première mondiale.",
    materialAnchor: "Carte bancaire dorée, lecteur de puce et terminal de paiement",
    sceneText: "1982, caisse d'un commerce. La carte s'insère dans le lecteur, côté puce. Le paiement est sécurisé différemment. La France invente le standard mondial qui sera adopté partout trente ans plus tard.",
    fact: "En 1982, la France déploie la première carte bancaire à puce au monde, inventée par Roland Moreno en 1974.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Carte_%C3%A0_puce", authority: false },
      { label: "Banque de France", url: "https://www.banque-france.fr", authority: true }
    ],
    tags: ["carte-puce", "paiement", "banque", "invention-francaise"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1984-cd-audio",
    countryQid: "Q142", lang: "fr",
    itemKey: "ecouter-un-cd-audio",
    itemLabel: "écouter de la musique sur un CD audio",
    theme: "loisirs", gestureRoot: "cd_audio",
    editorialScore: 86,
    objectType: "device", category: "media",
    releaseDate: "1982-10-01", releaseYear: 1982, datePrecision: "month",
    placeName: "Salon et chaîne hi-fi", placeType: "country", placeQid: "Q142",
    triggerLabel: "Lancement du CD audio (Sony et Philips)",
    beforeState: "Avant 1982, la musique se stocke sur disque vinyle ou cassette — fragile, dégradable, avec des craquements.",
    afterState: "Après 1982, le CD numérique offre un son parfait et un support quasi-indestructible.",
    objectChanged: "Tu peux poser un disque argenté sur le plateau et entendre ta musique sans aucun craquement.",
    materialAnchor: "Lecteur CD, plateau à ventouse et boîtier transparent",
    sceneText: "1982, salon. Le disque argenté glisse sur le plateau. La tête laser part, et le son sort sans souffle ni craquement. La musique vient d'entrer dans l'ère numérique — imperceptiblement, dans le silence.",
    fact: "En octobre 1982, le CD audio est lancé en Europe par Sony et Philips, avec une présentation commune des deux firmes.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Disque_compact", authority: false }
    ],
    tags: ["cd", "musique", "numerique", "audio"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1989-internet-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "se-connecter-a-internet-en-france",
    itemLabel: "accéder à Internet depuis la France",
    theme: "communication", gestureRoot: "internet_france",
    editorialScore: 92,
    objectType: "infrastructure", category: "network",
    releaseDate: "1988-01-01", releaseYear: 1988, datePrecision: "year",
    placeName: "France — réseau Renater", placeType: "country", placeQid: "Q142",
    triggerLabel: "Connexion de la France à Internet",
    beforeState: "Avant 1988, Internet est un réseau réservé à l'armée et à quelques universités américaines.",
    afterState: "Après 1988, des universités et centres de recherche français sont connectés à Internet.",
    objectChanged: "Tu peux envoyer un email à un chercheur américain en quelques secondes depuis un laboratoire français.",
    materialAnchor: "Terminal réseau, câble RJ45 et écran noir ligne de commande",
    sceneText: "1988, laboratoire de recherche français. Le terminal affiche une connexion. Un email part vers Berkeley. La réponse arrive en quelques secondes depuis l'autre côté de l'Atlantique. Internet vient d'atterrir en France.",
    fact: "En 1988, la France se connecte à Internet via le réseau académique, dix ans avant sa diffusion grand public.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Histoire_de_l%27Internet_en_France", authority: false }
    ],
    tags: ["internet", "reseau", "numerique", "universite"],
    quality: { strictPlace: false, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
];
