import type { InventionEntry } from "../../../types";

export const FR_INVENTION_BACKFILL_1990_2009: InventionEntry[] = [
  {
    id: "fr-1991-world-wide-web",
    countryQid: "Q142", lang: "fr",
    itemKey: "naviguer-sur-le-web",
    itemLabel: "naviguer sur le World Wide Web",
    theme: "communication", gestureRoot: "world_wide_web",
    editorialScore: 96,
    objectType: "infrastructure", category: "network",
    releaseDate: "1991-08-06", releaseYear: 1991, datePrecision: "day",
    placeName: "CERN, Genève", placeType: "site", placeQid: "Q42970",
    triggerLabel: "Mise en ligne du premier site web par Tim Berners-Lee",
    beforeState: "Avant le 6 août 1991, Internet existe mais naviguer de page en page avec des liens n'est pas possible.",
    afterState: "Après le 6 août 1991, le Web existe : on peut cliquer sur un lien et atterrir sur une autre page.",
    objectChanged: "Tu peux cliquer sur un lien hypertexte et passer d'un document à un autre n'importe où dans le monde.",
    materialAnchor: "Navigateur web, URL dans la barre d'adresse et lien bleu souligné",
    sceneText: "6 août 1991, CERN. Tim Berners-Lee met en ligne le premier site web de l'histoire. Le clic sur un lien envoie vers une autre page. Ce geste — pointer, cliquer, lire — va devenir le geste numérique du XXIe siècle.",
    fact: "Le 6 août 1991, Tim Berners-Lee publie le premier site web de l'histoire depuis le CERN à Genève.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/World_Wide_Web", authority: false },
      { label: "CERN", url: "https://home.cern/fr/science/computing/birth-web", authority: true }
    ],
    tags: ["web", "internet", "berners-lee", "cern"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1995-dvd-annonce",
    countryQid: "Q142", lang: "fr",
    itemKey: "regarder-un-dvd",
    itemLabel: "regarder un film en DVD chez soi",
    theme: "loisirs", gestureRoot: "dvd",
    editorialScore: 84,
    objectType: "device", category: "media",
    releaseDate: "1997-03-01", releaseYear: 1997, datePrecision: "month",
    placeName: "Salon français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Lancement du DVD en France",
    beforeState: "Avant 1997, regarder un film à la maison passe par la cassette VHS, volumineuse et de qualité dégradée.",
    afterState: "Après 1997, le DVD offre une image et un son de qualité cinéma dans le salon.",
    objectChanged: "Tu peux regarder un film en qualité quasi-cinéma depuis ton canapé, avec accès aux scènes supprimées.",
    materialAnchor: "Boîtier DVD, lecteur et menu de navigation",
    sceneText: "1997, salon. Le disque fin glisse dans le lecteur. Le menu apparaît. Les bonus, les langues, les sous-titres — tout est là. La VHS prend la poussière dans le placard.",
    fact: "En mars 1997, les premiers lecteurs et films DVD sont commercialisés en France.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/DVD", authority: false }
    ],
    tags: ["dvd", "cinema", "salon", "video"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-1998-google",
    countryQid: "Q142", lang: "fr",
    itemKey: "chercher-quelque-chose-sur-google",
    itemLabel: "chercher quelque chose sur Google",
    theme: "communication", gestureRoot: "moteur_de_recherche",
    editorialScore: 94,
    objectType: "service", category: "network",
    releaseDate: "1998-09-04", releaseYear: 1998, datePrecision: "day",
    placeName: "Garage de Menlo Park, Californie", placeType: "site", placeQid: null,
    triggerLabel: "Fondation de Google",
    beforeState: "Avant 1998, trouver une information sur le web nécessite de naviguer dans des annuaires ou des moteurs moins pertinents.",
    afterState: "Après 1998, Google indexe le web et retourne les résultats les plus pertinents en quelques millisecondes.",
    objectChanged: "Tu peux taper n'importe quelle question dans une barre blanche et obtenir des milliers de réponses classées.",
    materialAnchor: "Barre de recherche blanche, logo coloré et résultats listés",
    sceneText: "4 septembre 1998, Californie. Larry Page et Sergey Brin fondent Google dans un garage. Dans quelques années, 'chercher sur Google' deviendra synonyme de 'chercher' — dans toutes les langues du monde.",
    fact: "Le 4 septembre 1998, Google est fondé par Larry Page et Sergey Brin, révolutionnant la recherche d'information en ligne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Google", authority: false }
    ],
    tags: ["google", "recherche", "internet", "web"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2001-wikipedia",
    countryQid: "Q142", lang: "fr",
    itemKey: "consulter-wikipedia",
    itemLabel: "consulter une encyclopédie en ligne gratuite",
    theme: "communication", gestureRoot: "wikipedia",
    editorialScore: 88,
    objectType: "service", category: "network",
    releaseDate: "2001-01-15", releaseYear: 2001, datePrecision: "day",
    placeName: "Web mondial", placeType: "country", placeQid: "Q142",
    triggerLabel: "Lancement de Wikipedia",
    beforeState: "Avant 2001, accéder à une encyclopédie complète demande d'acheter la Britannica ou le Larousse.",
    afterState: "Après 2001, Wikipedia offre gratuitement des millions d'articles dans toutes les langues.",
    objectChanged: "Tu peux accéder à une encyclopédie universelle gratuite depuis n'importe quel écran connecté.",
    materialAnchor: "Écran, lien Wikipedia et logo globe puzzle",
    sceneText: "15 janvier 2001, web. Wikipedia publie ses premiers articles. Gratuit, ouvert, modifiable par tous. En quelques années, ce sera l'encyclopédie la plus consultée de l'histoire humaine.",
    fact: "Le 15 janvier 2001, Wikipedia est lancé par Jimmy Wales et Larry Sanger — encyclopédie collaborative gratuite ouverte à tous.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Wikip%C3%A9dia", authority: false }
    ],
    tags: ["wikipedia", "encyclopedie", "internet", "savoir"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2005-youtube",
    countryQid: "Q142", lang: "fr",
    itemKey: "regarder-une-video-sur-youtube",
    itemLabel: "regarder une vidéo sur YouTube",
    theme: "loisirs", gestureRoot: "youtube",
    editorialScore: 92,
    objectType: "service", category: "media",
    releaseDate: "2005-04-23", releaseYear: 2005, datePrecision: "day",
    placeName: "Web mondial", placeType: "country", placeQid: "Q142",
    triggerLabel: "Première vidéo mise en ligne sur YouTube",
    beforeState: "Avant 2005, partager une vidéo en ligne est complexe, coûteux et réservé aux professionnels.",
    afterState: "Après 2005, n'importe qui peut mettre en ligne une vidéo et la partager avec un public planétaire depuis son ordinateur.",
    objectChanged: "Tu peux mettre en ligne ta vidéo depuis ton ordinateur et la voir regardée par des milliers de personnes.",
    materialAnchor: "Barre de lecture YouTube, icône lecture rouge et barre de progression",
    sceneText: "23 avril 2005, San José. Jawed Karim poste la première vidéo YouTube — 18 secondes devant des éléphants. En quelques mois, des millions de personnes partagent leurs films amateurs. La vidéo grand public devient un geste ordinaire.",
    fact: "Le 23 avril 2005, la première vidéo est publiée sur YouTube, qui deviendra le plus grand site de vidéos du monde.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/YouTube", authority: false }
    ],
    tags: ["youtube", "video", "internet", "partage"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2007-iphone",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-un-iphone",
    itemLabel: "utiliser un smartphone à écran tactile",
    theme: "communication", gestureRoot: "iphone_smartphone",
    editorialScore: 96,
    objectType: "device", category: "device",
    releaseDate: "2007-01-09", releaseYear: 2007, datePrecision: "day",
    placeName: "Macworld, San Francisco", placeType: "site", placeQid: null,
    triggerLabel: "Présentation du premier iPhone par Steve Jobs",
    beforeState: "Avant janvier 2007, téléphone, lecteur MP3 et navigateur web sont trois appareils séparés.",
    afterState: "Après janvier 2007, l'iPhone fusionne tout dans une dalle de verre tactile.",
    objectChanged: "Tu peux tenir l'internet, ta musique et ton téléphone dans une plaque de verre tenue à une main.",
    materialAnchor: "iPhone argenté, écran tactile et geste de défilement",
    sceneText: "9 janvier 2007, Macworld. Steve Jobs sort un rectangle de verre de sa poche. 'Un iPod, un téléphone, un communicateur internet.' La salle applaudit. Le monde qu'on connaît vient de changer.",
    fact: "Le 9 janvier 2007, Steve Jobs présente le premier iPhone — fusionnant téléphone, iPod et navigateur web dans un écran tactile.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/IPhone", authority: false },
      { label: "Apple", url: "https://www.apple.com/fr/iphone/", authority: true }
    ],
    tags: ["iphone", "smartphone", "apple", "tactile"],
    quality: { strictPlace: true, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1990-tunnel-manche-avancement",
    countryQid: "Q142", lang: "fr",
    itemKey: "traverser-la-manche-sous-les-eaux-par-le-tunnel",
    itemLabel: "traverser la Manche sous l'eau par l'Eurostar",
    theme: "transport", gestureRoot: "tunnel_manche",
    editorialScore: 90,
    objectType: "infrastructure", category: "transport",
    releaseDate: "1994-11-14", releaseYear: 1990, datePrecision: "year",
    placeName: "Tunnel sous la Manche, Coquelles", placeType: "site", placeQid: null,
    triggerLabel: "Chantier avancé du tunnel sous la Manche — jonction franco-britannique",
    beforeState: "Avant 1990, traverser la Manche exige un ferry ou un avion. Un tunnel est en chantier depuis 1988.",
    afterState: "En 1990, les deux équipes de creusement se rejoignent sous la mer — la liaison ferroviaire sous la Manche devient tangible.",
    objectChanged: "Tu peux imaginer — et bientôt prendre — un train pour Londres sans jamais voir la mer.",
    materialAnchor: "Tunnelière, casques de chantier et jonction sous la Manche",
    sceneText: "1990, sous la Manche. Les deux équipes de percement se rejoignent à 40 mètres sous les eaux. La jonction est symbolique : pour la première fois depuis 8 000 ans, la Grande-Bretagne est reliée à l'Europe par un passage solide.",
    fact: "En décembre 1990, les équipes française et britannique se rejoignent sous la Manche lors de la jonction du tunnel — ouvert en 1994.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Tunnel_sous_la_Manche", authority: false },
      { label: "Eurostar", url: "https://www.eurostar.com/fr-fr/a-propos/histoire", authority: true }
    ],
    tags: ["tunnel", "manche", "eurostar", "transport"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1993-traite-maastricht-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "voter-le-traite-de-maastricht-et-preparer-leuro",
    itemLabel: "voter le traité de Maastricht et préparer l'euro",
    theme: "administration", gestureRoot: "maastricht_europe",
    editorialScore: 88,
    objectType: "service", category: "service",
    releaseDate: "1992-09-20", releaseYear: 1993, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Entrée en vigueur du traité de Maastricht après le référendum français",
    beforeState: "Avant 1993, la construction européenne n'inclut pas la monnaie unique ni la citoyenneté européenne.",
    afterState: "Après Maastricht, l'Union européenne remplace la CEE et prépare le chemin vers l'euro.",
    objectChanged: "Tu peux te proclamer citoyen européen et voter aux élections municipales de ton pays d'adoption dans l'UE.",
    materialAnchor: "Traité imprimé, passeport européen et drapeau étoilé",
    sceneText: "1992-1993. Le référendum a dit oui de peu (51 %). Le traité de Maastricht entre en vigueur. La France devient membre de l'Union européenne. L'euro est une promesse sur le papier — dans dix ans, il sera dans les porte-monnaie.",
    fact: "En 1993, le traité de Maastricht entre en vigueur après le référendum français de septembre 1992, créant l'Union européenne et programm l'euro.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Trait%C3%A9_sur_l%27Union_europ%C3%A9enne", authority: false }
    ],
    tags: ["europe", "maastricht", "euro", "ue"],
    quality: { strictPlace: false, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-1995-tgv-eurostar-service",
    countryQid: "Q142", lang: "fr",
    itemKey: "prendre-leuropstar-paris-londres",
    itemLabel: "prendre l'Eurostar de Paris à Londres",
    theme: "transport", gestureRoot: "eurostar_paris_londres",
    editorialScore: 88,
    objectType: "vehicle", category: "transport",
    releaseDate: "1994-11-14", releaseYear: 1995, datePrecision: "year",
    placeName: "Gare du Nord, Paris", placeType: "site", placeQid: "Q207708",
    triggerLabel: "Mise en service commerciale de l'Eurostar (Paris-Londres)",
    beforeState: "Avant novembre 1994, aller de Paris à Londres nécessite un avion ou un ferry, avec au minimum 3-4 heures de trajet.",
    afterState: "Après l'ouverture de l'Eurostar, Paris-Londres se fait en moins de 3 heures en train direct sous la Manche.",
    objectChanged: "Tu peux partir de la Gare du Nord le matin, déjeuner à Londres et rentrer le soir en train.",
    materialAnchor: "Train Eurostar jaune, quai de la Gare du Nord et billet Paris-Londres",
    sceneText: "1994-1995, Gare du Nord. Le train jaune entre dans le tunnel. Sous la Manche, à grande vitesse. Londres apparaît en moins de trois heures. Paris et Londres viennent de devenir voisines.",
    fact: "En novembre 1994, l'Eurostar inaugure le service commercial Paris-Londres via le tunnel sous la Manche, en moins de 3 heures.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Eurostar", authority: false },
      { label: "Eurostar", url: "https://www.eurostar.com/fr-fr/a-propos/histoire", authority: true }
    ],
    tags: ["eurostar", "tunnel", "train", "londres"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-1996-telephone-portable-sfr-orange",
    countryQid: "Q142", lang: "fr",
    itemKey: "avoir-un-telephone-portable",
    itemLabel: "avoir un téléphone portable personnel",
    theme: "communication", gestureRoot: "telephone_portable",
    editorialScore: 90,
    objectType: "device", category: "device",
    releaseDate: "1996-01-01", releaseYear: 1996, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Démocratisation du téléphone portable en France",
    beforeState: "Avant 1996, le téléphone portable est un objet rare et coûteux, réservé aux professions libérales et cadres supérieurs.",
    afterState: "À partir de 1996, les abonnements bon marché font entrer le portable dans les poches de millions de Français.",
    objectChanged: "Tu peux porter dans ta poche un téléphone qui te joint n'importe où — et appeler n'importe qui.",
    materialAnchor: "Nokia 5110, façade amovible colorée et antenne télescopique",
    sceneText: "1996, France. Les boutiques SFR et Orange sont bondées. Les Nokia arrivent. Un portable, c'est encore un peu cher — mais ça devient possible. Le téléphone sort de la maison et entre dans la vie quotidienne.",
    fact: "Dans les années 1996-1998, le téléphone portable se démocratise en France avec la baisse des tarifs et les offres prépayées.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9phone_mobile_en_France", authority: false }
    ],
    tags: ["portable", "mobile", "sfr", "nokia"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2002-euro-monnaie-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "payer-en-euros-en-france",
    itemLabel: "payer en euros dans les magasins français",
    theme: "travail", gestureRoot: "euro_monnaie",
    editorialScore: 94,
    objectType: "payment_tool", category: "payment",
    releaseDate: "2002-01-01", releaseYear: 2002, datePrecision: "day",
    placeName: "Caisse d'un magasin, France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Entrée en circulation des billets et pièces en euros",
    beforeState: "Avant le 1er janvier 2002, on paye en France avec des francs — la monnaie nationale depuis des siècles.",
    afterState: "Après le 1er janvier 2002, l'euro remplace le franc dans les tiroirs-caisses et les porte-monnaie français.",
    objectChanged: "Tu poses pour la première fois une pièce d'un euro sur le comptoir et rends des centimes en échange.",
    materialAnchor: "Pièces en euros, billet de vingt euros et dernier franc",
    sceneText: "1er janvier 2002, caisse du supermarché. Le caissier rend la monnaie en euros. Le franc disparaît. Les porte-monnaie débordent de nouvelles pièces dorées et argentées. La France change de monnaie pour la première fois en plusieurs générations.",
    fact: "Le 1er janvier 2002, les billets et pièces en euros entrent en circulation en France, remplaçant définitivement le franc.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Euro", authority: false },
      { label: "Banque de France", url: "https://www.banque-france.fr/fr/lhistoire-de-leuro", authority: true }
    ],
    tags: ["euro", "monnaie", "europe", "franc"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-2003-canicule-plan-alerte",
    countryQid: "Q142", lang: "fr",
    itemKey: "beneficier-du-plan-canicule-apres-ete-2003",
    itemLabel: "bénéficier du plan canicule et du système d'alerte chaleur",
    theme: "santé", gestureRoot: "canicule_plan_alerte",
    editorialScore: 88,
    objectType: "service", category: "service",
    releaseDate: "2004-06-01", releaseYear: 2003, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Canicule d'août 2003 — création du plan canicule national",
    beforeState: "Avant l'été 2003, la France n'a pas de système d'alerte national face aux vagues de chaleur extrême.",
    afterState: "Après la canicule meurtrière de 2003, la France crée un plan canicule avec niveaux d'alerte, registres de personnes fragiles et déclenchement préfectoral.",
    objectChanged: "Tu peux recevoir une alerte officielle quand la chaleur dépasse un seuil dangereux — et les mairies ouvrent des lieux frais.",
    materialAnchor: "Carafe d'eau, ventilateur et affiche du plan canicule en mairie",
    sceneText: "Été 2003, France. La canicule tue 15 000 personnes en deux semaines. L'État est pris de court. L'année suivante, le plan canicule naît : niveaux d'alerte, registres de personnes vulnérables, salles climatisées. Une leçon tragique devient un dispositif.",
    fact: "La canicule d'août 2003, qui tue près de 15 000 personnes en France, conduit à la création du plan canicule national en 2004.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Canicule_europ%C3%A9enne_de_2003", authority: false },
      { label: "Santé Publique France", url: "https://www.santepubliquefrance.fr/", authority: true }
    ],
    tags: ["canicule", "sante", "alerte", "chaleur"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-2004-loi-voile-laicite",
    countryQid: "Q142", lang: "fr",
    itemKey: "appliquer-la-loi-sur-les-signes-religieux-a-lecole",
    itemLabel: "appliquer la loi sur les signes religieux ostensibles à l'école",
    theme: "école", gestureRoot: "loi_voile_laicite",
    editorialScore: 88,
    objectType: "service", category: "service",
    releaseDate: "2004-09-01", releaseYear: 2004, datePrecision: "day",
    placeName: "Établissements scolaires publics, France", placeType: "institution", placeQid: null,
    triggerLabel: "Application de la loi du 15 mars 2004 sur les signes religieux à l'école",
    beforeState: "Avant 2004, le port du voile ou d'autres signes religieux à l'école est au cœur d'un débat juridique non tranché.",
    afterState: "Après la rentrée de septembre 2004, la loi interdit les signes religieux ostensibles dans les établissements scolaires publics.",
    objectChanged: "Un élève ne peut plus porter son voile, sa grande croix ou sa kippa à l'école publique — la laïcité est réaffirmée par la loi.",
    materialAnchor: "Règlement intérieur, grille d'école et panneau «laïcité»",
    sceneText: "Rentrée de septembre 2004. Les proviseurs rappellent le règlement : pas de signe religieux ostensible. La loi votée en mars s'applique. Le débat avait divisé la France — la loi tranche, sans clore les discussions.",
    fact: "Le 15 mars 2004, la loi interdisant les signes religieux ostensibles dans les écoles publiques est promulguée, appliquée à la rentrée suivante.",
    sources: [
      { label: "Légifrance", url: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000417977", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Loi_sur_le_voile_islamique_en_France", authority: false }
    ],
    tags: ["laicite", "ecole", "loi", "religion"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-2008-crise-financiere-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "vivre-la-crise-financiere-en-france",
    itemLabel: "vivre la crise financière mondiale en France (2008)",
    theme: "travail", gestureRoot: "crise_2008_france",
    editorialScore: 86,
    objectType: "service", category: "service",
    releaseDate: "2008-10-01", releaseYear: 2008, datePrecision: "month",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Répercussions en France de la crise financière mondiale",
    beforeState: "Avant l'automne 2008, l'économie française tourne normalement ; les banques semblent solides.",
    afterState: "Après la chute de Lehman Brothers, la crise se propage en Europe et la France entre en récession.",
    objectChanged: "Tu peux lire chaque matin des nouvelles économiques qui parlent de faillites bancaires et de récession mondiale.",
    materialAnchor: "Écran de cotation boursière en rouge, journal économique et agence pour l'emploi",
    sceneText: "Automne 2008. Les écrans boursiers virent au rouge. Lehman Brothers est tombé. La France n'échappe pas : le chômage remonte, les banques sont soutenues par l'État. La crise mondiale n'est plus un phénomène américain.",
    fact: "À l'automne 2008, la crise financière mondiale frappe la France : récession, soutien public aux banques et hausse du chômage.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Crise_financi%C3%A8re_de_2007-2008", authority: false }
    ],
    tags: ["crise", "economie", "banque", "recession"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2009-taxe-carbone-projet",
    countryQid: "Q142", lang: "fr",
    itemKey: "payer-une-taxe-carbone-en-france",
    itemLabel: "payer une taxe carbone en France",
    theme: "administration", gestureRoot: "taxe_carbone",
    editorialScore: 82,
    objectType: "service", category: "service",
    releaseDate: "2009-09-01", releaseYear: 2009, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Annonce du projet de taxe carbone par le gouvernement français",
    beforeState: "Avant 2009, la France n'a pas de mécanisme fiscal direct sur les émissions de carbone des particuliers.",
    afterState: "En 2009, le gouvernement annonce une contribution carbone — même si le Conseil constitutionnel la censure, le principe s'impose progressivement.",
    objectChanged: "Tu peux entendre parler pour la première fois d'une taxe qui ferait payer les émissions de CO2 à la pompe et chez toi.",
    materialAnchor: "Pompe à essence, facture de chauffage et rapport environnemental",
    sceneText: "2009, France. Le gouvernement annonce la contribution carbone. La grande distribution, les automobilistes, les ménages — tout le monde calcule l'impact. Le principe est censuré par le Conseil constitutionnel, mais il reviendra. L'ère de la fiscalité verte a commencé.",
    fact: "En 2009, la France projette une contribution carbone sur les carburants fossiles — censurée mais préfigurant la future taxe carbone.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Taxe_carbone_en_France", authority: false }
    ],
    tags: ["carbone", "fiscalite", "environnement", "energie"],
    quality: { strictPlace: false, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
];
