import type { InventionEntry } from "../../../types";

export const FR_INVENTION_BACKFILL_2010_current: InventionEntry[] = [
  {
    id: "fr-2010-ipad-tablette",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-une-tablette-tactile",
    itemLabel: "utiliser une tablette tactile",
    theme: "communication", gestureRoot: "tablette_tactile",
    editorialScore: 84,
    objectType: "device", category: "device",
    releaseDate: "2010-04-03", releaseYear: 2010, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Lancement de l'iPad",
    beforeState: "Avant 2010, naviguer sur internet en position allongée ou dans le canapé suppose un ordinateur portable.",
    afterState: "Après 2010, la tablette tactile crée un nouvel usage intermédiaire entre le téléphone et l'ordinateur.",
    objectChanged: "Tu peux consulter internet, lire un livre ou regarder une vidéo avec un écran plat tenu dans les mains.",
    materialAnchor: "Tablette iPad, écran tactile et clavier virtuel",
    sceneText: "3 avril 2010, dans les magasins et salons francais. Une tablette lisse remplace tour a tour le journal, l'album photo et le lecteur video. L'ecran tactile grand format s'installe dans les usages domestiques.",
    fact: "Le 3 avril 2010, Apple lance l'iPad, créant la catégorie des tablettes tactiles grand public.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/IPad", authority: false },
      { label: "Apple", url: "https://www.apple.com/fr/ipad/", authority: true }
    ],
    tags: ["tablette", "ipad", "apple", "tactile"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-2012-uber-vtc",
    countryQid: "Q142", lang: "fr",
    itemKey: "commander-un-vtc-depuis-son-telephone",
    itemLabel: "commander un VTC depuis son téléphone",
    theme: "transport", gestureRoot: "vtc_application",
    editorialScore: 86,
    objectType: "service", category: "transport",
    releaseDate: "2012-01-01", releaseYear: 2012, datePrecision: "year",
    placeName: "France — Paris puis grandes villes", placeType: "city", placeQid: "Q90",
    triggerLabel: "Lancement d'Uber en France",
    beforeState: "Avant 2012, commander une voiture avec chauffeur nécessite d'appeler une centrale ou de héler un taxi dans la rue.",
    afterState: "Après 2012, une application permet de commander un VTC en quelques secondes, suivre son arrivée et payer sans espèces.",
    objectChanged: "Tu peux commander une voiture avec chauffeur sur ton écran, suivre son trajet en temps réel et régler automatiquement.",
    materialAnchor: "Téléphone, application Uber et voiture noire",
    sceneText: "2012, Paris. L'application s'ouvre, la carte affiche les voitures disponibles. Deux minutes plus tard, une berline arrive devant toi. Tu n'as ni appelé ni sorti de monnaie. Le taxi vient de changer de modèle.",
    fact: "En 2012, Uber lance son service de VTC en France, transformant la façon de commander une voiture avec chauffeur.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Uber_(entreprise)", authority: false }
    ],
    tags: ["vtc", "uber", "taxi", "application"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2016-pass-navigo-toutes-zones",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-le-navigo-toutes-zones",
    itemLabel: "voyager sur tout le réseau Île-de-France avec un seul pass",
    theme: "transport", gestureRoot: "navigo_toutes_zones",
    editorialScore: 82,
    objectType: "service", category: "transport",
    releaseDate: "2015-09-01", releaseYear: 2015, datePrecision: "month",
    placeName: "Réseau Île-de-France", placeType: "institution", placeQid: null,
    triggerLabel: "Navigo toutes zones au tarif unique",
    beforeState: "Avant 2015, le pass Navigo nécessite de choisir des zones et coûte plus cher pour les trajets banlieue-Paris.",
    afterState: "Après 2015, un seul tarif couvre l'ensemble du réseau francilien.",
    objectChanged: "Tu peux monter dans n'importe quel train ou métro d'Île-de-France avec ton pass sans vérifier la zone.",
    materialAnchor: "Pass Navigo, portique et réseau RER+métro",
    sceneText: "Septembre 2015, quai de RER. Le pass Navigo passe au portique comme d'habitude, mais cette fois tu viens de traverser cinq zones pour le même prix. La banlieue et Paris sont enfin à égalité tarifaire.",
    fact: "En septembre 2015, le pass Navigo toutes zones est lancé à tarif unique en Île-de-France.",
    sources: [
      { label: "Île-de-France Mobilités", url: "https://www.iledefrance-mobilites.fr", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Navigo", authority: false }
    ],
    tags: ["navigo", "transport", "idf", "pass"],
    quality: { strictPlace: true, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-2020-teletravail-generalise",
    countryQid: "Q142", lang: "fr",
    itemKey: "travailler-depuis-chez-soi-en-teletravail",
    itemLabel: "travailler depuis son domicile en télétravail",
    theme: "travail", gestureRoot: "teletravail",
    editorialScore: 90,
    objectType: "service", category: "service",
    releaseDate: "2020-03-17", releaseYear: 2020, datePrecision: "day",
    placeName: "Domicile français", placeType: "country", placeQid: "Q142",
    triggerLabel: "Confinement et généralisation du télétravail",
    beforeState: "Avant mars 2020, le télétravail reste marginal dans la grande majorité des entreprises françaises.",
    afterState: "Après mars 2020, des millions de salariés travaillent depuis leur domicile avec ordinateur et visioconférence.",
    objectChanged: "Tu peux ouvrir ton ordinateur depuis ta table de cuisine et rejoindre une réunion d'équipe en visio.",
    materialAnchor: "Ordinateur portable, fond Zoom et casque audio",
    sceneText: "17 mars 2020, confinement. Le bureau disparaît. La table de la cuisine devient le poste de travail. La réunion se tient en visio, les enfants passent derrière l'écran. Le travail ne sera plus jamais tout à fait le même.",
    fact: "Le 17 mars 2020, lors du premier confinement, des millions de salariés français basculent en télétravail forcé.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9travail", authority: false },
      { label: "Dares", url: "https://dares.travail-emploi.gouv.fr", authority: true }
    ],
    tags: ["teletravail", "covid", "domicile", "visio"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 2 }
  },
  {
    id: "fr-2011-instagram-france",
    countryQid: "Q142", lang: "fr",
    itemKey: "publier-une-photo-depuis-instagram",
    itemLabel: "publier une photo depuis Instagram",
    theme: "communication", gestureRoot: "instagram",
    editorialScore: 82,
    objectType: "service", category: "media",
    releaseDate: "2011-01-01", releaseYear: 2011, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Instagram gagne le grand public en France",
    beforeState: "Avant 2011, partager des photos filtrées sur mobile reste surtout l'apanage de quelques early adopters.",
    afterState: "Après 2011, Instagram devient une référence pour poster instantanément des images carrées depuis le smartphone.",
    objectChanged: "Tu peux appliquer un filtre, taguer un lieu et partager ton cliché dans un flux mondial.",
    materialAnchor: "Smartphone, application Instagram et filtre Valencia",
    sceneText: "2011, dans les transports et les cafes francais. L'ecran affiche une grille de photos carrees. Instagram s'impose comme le geste visuel du moment entre amis.",
    fact: "En 2011, Instagram connaît une croissance forte et s'impose comme l'application de partage photo sur mobile avant son rachat par Facebook.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Instagram", authority: false }
    ],
    tags: ["instagram", "photo", "mobile", "reseaux"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2013-chromecast",
    countryQid: "Q142", lang: "fr",
    itemKey: "envoyer-un-film-sur-la-televiseur-depuis-le-telephone",
    itemLabel: "envoyer une vidéo du téléphone vers la télévision",
    theme: "communication", gestureRoot: "chromecast",
    editorialScore: 80,
    objectType: "device", category: "device",
    releaseDate: "2013-07-24", releaseYear: 2013, datePrecision: "day",
    placeName: "Salon", placeType: "country", placeQid: "Q142",
    triggerLabel: "Lancement du Google Chromecast",
    beforeState: "Avant 2013, relier téléphone et téléviseur sans câble HDMI long reste souvent compliqué.",
    afterState: "Après 2013, une clé HDMI diffuse le flux Wi-Fi vers l'écran du salon.",
    objectChanged: "Tu peux lancer YouTube ou Netflix sur ton téléphone et le laisser sur la télé sans box propriétaire.",
    materialAnchor: "Clé Chromecast, port HDMI et smartphone",
    sceneText: "2013, salon francais. On branche la petite cle sur la television, on choisit une video sur le telephone, et l'image saute sur le grand ecran. Le partage familial du film change de geste.",
    fact: "Le 24 juillet 2013, Google présente le Chromecast, clé HDMI permettant d'envoyer du contenu depuis un smartphone vers une télévision.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Chromecast", authority: false }
    ],
    tags: ["chromecast", "streaming", "television", "wifi"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2014-apple-pay",
    countryQid: "Q142", lang: "fr",
    itemKey: "payer-avec-son-telephone-apple-pay",
    itemLabel: "payer avec son téléphone via Apple Pay",
    theme: "argent", gestureRoot: "apple_pay",
    editorialScore: 78,
    objectType: "payment_tool", category: "payment",
    releaseDate: "2014-09-09", releaseYear: 2014, datePrecision: "day",
    placeName: "États-Unis puis extension mondiale", placeType: "country", placeQid: null,
    triggerLabel: "Annonce d'Apple Pay",
    beforeState: "Avant 2014, payer en magasin avec le téléphone sans ouvrir une application bancaire reste rare.",
    afterState: "Après septembre 2014, Apple Pay montre la voie du paiement NFC intégré au mobile haut de gamme.",
    objectChanged: "Tu peux approcher ton téléphone du terminal comme une carte sans contact dématérialisée.",
    materialAnchor: "iPhone, Touch ID et terminal sans contact",
    sceneText: "Septembre 2014, keynote Apple. Apple Pay est annonce. Le telephone devient portefeuille pour des millions d'utilisateurs, et l'Europe suivra dans les extensions ulterieures.",
    fact: "Le 9 septembre 2014, Apple annonce Apple Pay, service de paiement mobile et sans contact intégré à l'iPhone.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Apple_Pay", authority: false }
    ],
    tags: ["apple-pay", "paiement", "nfc", "mobile"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2016-pokemon-go",
    countryQid: "Q142", lang: "fr",
    itemKey: "attraper-un-pokemon-dans-la-rue",
    itemLabel: "attraper un Pokémon dans la rue avec son téléphone",
    theme: "loisirs", gestureRoot: "pokemon_go",
    editorialScore: 82,
    objectType: "service", category: "service",
    releaseDate: "2016-07-06", releaseYear: 2016, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Sortie de Pokémon GO en France",
    beforeState: "Avant juillet 2016, aucun jeu de réalité augmentée ne pousse autant de monde à marcher dehors téléphone levé.",
    afterState: "Après Pokémon GO, les parcs et places se remplissent de joueurs qui chassent des créatures virtuelles.",
    objectChanged: "Tu peux voir un Pokémon sur le trottoir devant toi et le capturer en balayant l'écran.",
    materialAnchor: "Smartphone, GPS et Pokéball virtuelle",
    sceneText: "Ete 2016, en France. Les groupes se forment autour des arrets de bus et des fontaines pour des raids imaginaires. La ville devient terrain de jeu partage.",
    fact: "En juillet 2016, Pokémon GO est lancé en France et déclenche une fréquentation massive des espaces publics par les joueurs.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Pok%C3%A9mon_GO", authority: false }
    ],
    tags: ["pokemon", "jeu", "mobile", "realite-augmentee"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2017-airpods",
    countryQid: "Q142", lang: "fr",
    itemKey: "ecouter-sans-fil-avec-des-ecouteurs-boutons",
    itemLabel: "écouter de la musique avec des écouteurs sans fil en boutons",
    theme: "communication", gestureRoot: "airpods",
    editorialScore: 80,
    objectType: "device", category: "device",
    releaseDate: "2017-01-01", releaseYear: 2017, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Généralisation des AirPods",
    beforeState: "Avant 2017, les écouteurs sans fil restent encore minoritaires dans les transports.",
    afterState: "Après les AirPods, des millions de personnes portent des oreillettes discrètes sans câble.",
    objectChanged: "Tu ranges les deux boules dans leur boîtier qui recharge et tu oublies le nœud de fils.",
    materialAnchor: "Boîtier blanc, AirPods et Bluetooth",
    sceneText: "2017, RER et métro francais. Les fils disparaissent des oreilles. Les petits batons blancs deviennent le signe visible du son nomade.",
    fact: "En 2017, les AirPods d'Apple s'imposent comme référence des écouteurs véritablement sans fil grand public.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/AirPods", authority: false }
    ],
    tags: ["airpods", "audio", "bluetooth", "apple"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2018-rgpd",
    countryQid: "Q142", lang: "fr",
    itemKey: "accepter-les-cookies-sur-un-site",
    itemLabel: "voir apparaître les bandeaux cookies et le consentement RGPD",
    theme: "communication", gestureRoot: "rgpd",
    editorialScore: 78,
    objectType: "service", category: "service",
    releaseDate: "2018-05-25", releaseYear: 2018, datePrecision: "day",
    placeName: "Union européenne", placeType: "country", placeQid: null,
    triggerLabel: "Entrée en vigueur du RGPD",
    beforeState: "Avant mai 2018, les sites peuvent encore collecter des données sans bandeau explicite aussi systématique.",
    afterState: "Après le RGPD, chaque site européen affiche un choix de cookies et une politique détaillée.",
    objectChanged: "Tu dois cliquer pour accepter ou refuser le suivi avant de naviguer normalement.",
    materialAnchor: "Bandeau cookies, cases à cocher et mentions légales",
    sceneText: "25 mai 2018. Les ecrans europeens se couvrent de bandeaux gris. Le consentement aux donnees personnelles devient un geste quotidien du web.",
    fact: "Le 25 mai 2018, le règlement général sur la protection des données (RGPD) s'applique dans l'Union européenne.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/R%C3%A8glement_g%C3%A9n%C3%A9ral_sur_la_protection_des_donn%C3%A9es", authority: false }
    ],
    tags: ["rgpd", "donnees", "cookies", "web"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2019-tiktok",
    countryQid: "Q142", lang: "fr",
    itemKey: "defiler-des-videos-courtes-sur-tiktok",
    itemLabel: "défiler des vidéos courtes sur TikTok",
    theme: "loisirs", gestureRoot: "tiktok",
    editorialScore: 80,
    objectType: "media", category: "media",
    releaseDate: "2019-01-01", releaseYear: 2019, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Essor de TikTok en France",
    beforeState: "Avant 2019, la vidéo verticale addictive en boucle reste surtout associée à d'autres réseaux.",
    afterState: "Après 2019, TikTok devient un réflexe pour des millions d'adolescents et jeunes adultes.",
    objectChanged: "Tu fais défiler une succession infinie de clips courts algorithmiques.",
    materialAnchor: "Application TikTok, fil Pour toi et son vertical",
    sceneText: "2019, chambres et transports francais. Le defilement vertical rythme l'ennui. Les danses et les memes circulent a vitesse algorithmique.",
    fact: "En 2019, TikTok connaît une croissance explosive en France et dans le monde comme réseau de vidéos courtes.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/TikTok", authority: false }
    ],
    tags: ["tiktok", "video", "reseaux", "mobile"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2021-pass-sanitaire",
    countryQid: "Q142", lang: "fr",
    itemKey: "montrer-un-qr-code-pour-entrer",
    itemLabel: "montrer un QR code pour entrer dans un lieu",
    theme: "santé", gestureRoot: "pass_sanitaire",
    editorialScore: 82,
    objectType: "service", category: "service",
    releaseDate: "2021-07-21", releaseYear: 2021, datePrecision: "day",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Instauration du pass sanitaire en France",
    beforeState: "Avant juillet 2021, entrer au restaurant ne suppose pas de prouver son statut vaccinal ou un test récent.",
    afterState: "Après le pass sanitaire, de nombreux lieux exigent un QR code valide à l'entrée.",
    objectChanged: "Tu ouvres l'application TousAntiCovid et présentes ton QR code au contrôle.",
    materialAnchor: "QR code, application TousAntiCovid et contrôle d'accès",
    sceneText: "Ete 2021, terrasses et salles francaises. Le telephone affiche un carre noir et blanc. L'entree se joue a la validation du QR code.",
    fact: "Le 21 juillet 2021, le pass sanitaire devient obligatoire pour accéder à certains lieux en France dans le cadre de la lutte contre la Covid-19.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Passe_sanitaire_fran%C3%A7ais", authority: false }
    ],
    tags: ["pass-sanitaire", "covid", "qr-code", "sante"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2022-chatgpt-public",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-chatgpt-depuis-un-navigateur",
    itemLabel: "utiliser ChatGPT depuis un navigateur web",
    theme: "communication", gestureRoot: "chatgpt",
    editorialScore: 86,
    objectType: "service", category: "service",
    releaseDate: "2022-11-30", releaseYear: 2022, datePrecision: "day",
    placeName: "Internet", placeType: "country", placeQid: null,
    triggerLabel: "Lancement public de ChatGPT",
    beforeState: "Avant novembre 2022, peu de services grand public permettent de converser avec un grand modèle de langage.",
    afterState: "Après ChatGPT, des millions d'utilisateurs expérimentent la rédaction et le code assistés par IA.",
    objectChanged: "Tu peux poser une question en langage naturel et recevoir une réponse structurée instantanément.",
    materialAnchor: "Navigateur, fenêtre ChatGPT et invite de prompt",
    sceneText: "Novembre 2022. ChatGPT ouvre au public. Dans les bureaux francais, on teste resumes, lettres et bouts de code. L'outil devient un reflexe en quelques semaines.",
    fact: "Le 30 novembre 2022, OpenAI lance ChatGPT, rendant accessibles au grand public les conversations avec un modèle de langage avancé.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/ChatGPT", authority: false }
    ],
    tags: ["chatgpt", "ia", "openai", "texte"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2024-apple-vision-pro",
    countryQid: "Q142", lang: "fr",
    itemKey: "voir-un-casque-de-realite-mixte-grand-public",
    itemLabel: "voir arriver un casque de réalité mixte grand public",
    theme: "loisirs", gestureRoot: "vision_pro",
    editorialScore: 76,
    objectType: "device", category: "device",
    releaseDate: "2024-02-02", releaseYear: 2024, datePrecision: "day",
    placeName: "États-Unis", placeType: "country", placeQid: null,
    triggerLabel: "Commercialisation de l'Apple Vision Pro",
    beforeState: "Avant 2024, la réalité mixte haut de gamme reste surtout l'affaire de casques professionnels ou de niche.",
    afterState: "Après la Vision Pro, Apple pose un repère médiatique fort pour le spatial computing.",
    objectChanged: "Tu peux projeter des fenêtres et des films dans l'espace autour de toi avec un casque autonome.",
    materialAnchor: "Casque Vision Pro, passthrough vidéo et contrôle des yeux",
    sceneText: "2024, les vitrines et les revues tech francais commentent la Vision Pro. Le casque spatial devient le symbole d'une nouvelle couche entre reel et numerique.",
    fact: "Le 2 février 2024, Apple commercialise le Vision Pro, casque de réalité mixte positionné comme appareil spatial computing.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Apple_Vision_Pro", authority: false }
    ],
    tags: ["vision-pro", "realite-mixte", "apple", "spatial"],
    quality: { strictPlace: false, strictDate: true, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-2025-mistral-ai",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-un-modele-dia-europeen",
    itemLabel: "utiliser un grand modèle de langage européen (Mistral)",
    theme: "communication", gestureRoot: "mistral_ai",
    editorialScore: 78,
    objectType: "service", category: "service",
    releaseDate: "2025-01-01", releaseYear: 2025, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Montée en puissance de Mistral AI en France",
    beforeState: "Avant 2025, l'écosystème français des LLM reste encore moins visible que les géants américains.",
    afterState: "En 2025, Mistral AI s'impose comme acteur majeur de l'IA générative en Europe.",
    objectChanged: "Tu peux intégrer des modèles européens dans des produits et services avec une alternative à OpenAI.",
    materialAnchor: "API Mistral, console développeur et modèles ouverts",
    sceneText: "2025, startups et grands groupes francais integrent des modeles Mistral dans leurs produits. L'IA generative a aussi un visage europeen.",
    fact: "En 2025, Mistral AI continue de se développer comme entreprise française de référence en intelligence artificielle générative.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/Mistral_AI", authority: false }
    ],
    tags: ["mistral", "ia", "france", "llm"],
    quality: { strictPlace: false, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-2023-gpt-4-openai",
    countryQid: "Q142", lang: "fr",
    itemKey: "utiliser-gpt-4-pour-rediger",
    itemLabel: "utiliser GPT-4 pour rédiger ou analyser un texte",
    theme: "communication", gestureRoot: "gpt4",
    editorialScore: 88,
    objectType: "service", category: "service",
    releaseDate: "2023-03-14", releaseYear: 2023, datePrecision: "day",
    placeName: "Internet", placeType: "country", placeQid: null,
    triggerLabel: "Lancement de GPT-4 par OpenAI",
    beforeState: "Avant mars 2023, les modèles accessibles au grand public restent surtout associés à GPT-3.5.",
    afterState: "Après GPT-4, les usages professionnels de rédaction et d'analyse longue se multiplient.",
    objectChanged: "Tu peux soumettre des documents entiers et obtenir des réponses plus nuancées qu'avec le modèle précédent.",
    materialAnchor: "Interface OpenAI, modèle GPT-4 et fenêtre de chat",
    sceneText: "Mars 2023. OpenAI annonce GPT-4. Dans les bureaux francais, on teste resumes longs, tableaux et code sur de plus gros contextes. L'outil gagne en credibilite.",
    fact: "Le 14 mars 2023, OpenAI annonce GPT-4, modèle de langage multiforme présenté comme nettement plus performant que GPT-3.5.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/GPT-4", authority: false }
    ],
    tags: ["gpt-4", "openai", "ia", "2023"],
    quality: { strictPlace: false, strictDate: true, everydayUse: true, sourceCount: 1 }
  },
  {
    id: "fr-2026-iter-jalon",
    countryQid: "Q142", lang: "fr",
    itemKey: "suivre-iter-pour-la-fusion",
    itemLabel: "suivre les jalons du projet ITER sur la fusion nucléaire",
    theme: "loisirs", gestureRoot: "iter_fusion",
    editorialScore: 70,
    objectType: "infrastructure", category: "device",
    releaseDate: "2026-01-01", releaseYear: 2026, datePrecision: "year",
    placeName: "Cadarache, Bouches-du-Rhône", placeType: "site", placeQid: null,
    triggerLabel: "Poursuite du programme expérimental ITER en 2026",
    beforeState: "Avant 2026, le tokamak reste un chantier colossal encore en montée en puissance.",
    afterState: "En 2026, les étapes du programme ITER continuent de structurer la recherche mondiale sur la fusion.",
    objectChanged: "Tu peux suivre les annonces scientifiques et les expériences de plasma comme un jalon du futur énergétique.",
    materialAnchor: "Tokamak, cryostat et annonces du consortium ITER",
    sceneText: "2026, actualite scientifique. Le projet ITER au Cadarache reste le plus grand laboratoire de fusion au monde. Chaque jalon alimente le debat sur l'energie de demain.",
    fact: "Le projet ITER, près de Cadarache en France, poursuit dans les années 2020 son programme de recherche sur la fusion nucléaire contrôlée.",
    sources: [
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/ITER", authority: false }
    ],
    tags: ["iter", "fusion", "energie", "2026"],
    quality: { strictPlace: true, strictDate: false, everydayUse: false, sourceCount: 1 }
  },
  {
    id: "fr-2026-reseau-5g-densification",
    countryQid: "Q142", lang: "fr",
    itemKey: "beneficier-du-5g-en-zone-dense",
    itemLabel: "bénéficier de la 5G densifiée en ville",
    theme: "communication", gestureRoot: "reseau_5g",
    editorialScore: 72,
    objectType: "service", category: "network",
    releaseDate: "2026-01-01", releaseYear: 2026, datePrecision: "year",
    placeName: "France", placeType: "country", placeQid: "Q142",
    triggerLabel: "Densification des réseaux 5G en France",
    beforeState: "Avant 2026, la 5G reste encore inégale selon les territoires et les opérateurs.",
    afterState: "En 2026, la couverture 5G continue de se densifier dans les grandes agglomérations françaises.",
    objectChanged: "Tu peux télécharger plus vite en mobilité et utiliser des usages data lourds en extérieur.",
    materialAnchor: "Antenne 5G, smartphone compatible et carte de couverture",
    sceneText: "2026, centres-villes francais. La 5G se banalise sur les smartphones recents. Le debat sur les antennes et la consommation data reste au premier plan.",
    fact: "Au milieu des années 2020, les opérateurs français poursuivent le déploiement et la densification de la 5G sur le territoire.",
    sources: [
      { label: "Arcep", url: "https://www.arcep.fr", authority: true },
      { label: "Wikipedia", url: "https://fr.wikipedia.org/wiki/5G", authority: false }
    ],
    tags: ["5g", "mobile", "reseau", "2026"],
    quality: { strictPlace: false, strictDate: false, everydayUse: true, sourceCount: 2 }
  },
];
